zanata/zanata-platform

server/zanata-frontend/src/editor/app/actions/phrases.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1511
Languages with nplurals=1 would not have plural translations displayed in the React editor. This fixes the display.
Just needs a document with one plural form, and a language with nplurals=1 (e.g. Japanese). I used the document linked in a JIRA comment to reproduce it before the fix.
When the bug is present, the translation area is blank (no "Singular form" label and no text).
Use the …
=> fix(editor): display plural translations when nplurals=1

server/functional-test/src/main/java/org/zanata/util/TestEventForScreenshotListener.java
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1576
Overlay the driver's current url in text on the test screenshot.
Include url in log notification.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-techno …
=> fix(ZNTA-1576): Include url in functional test screenshots

server/gwt-editor/pom.xml
Draft mode saves about 13 seconds in my unscientific tests running `mvn clean package` (with soft permutations - https://github.com/zanata/zanata-platform/pull/73), compared to `mvn clean package -Doptimise`.
Running `mvn clean package -Dgwt.validateOnly` only saves another 3, but `mvn clean package -Dgwt.compiler.skip` saves 39 seconds (compared to draft) - note that this doesn't run the GWT compiler at all, although it still runs the Java compiler.
Use …
=> Enable GWT draft mode by default

server/zanata-frontend/src/frontend/app/styles/style.less, server/zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1647
Long file names in languages panel of documents tab do not appear on one line and file name overlays languages panel content. 
Issue:
Fix:
- Code quality
- Testing …
=> fix: fixed long file name wrapping in language panel of documents tab (ZNTA-1647)

build-tools/src/main/resources/zanata-build-tools/checkstyle.xml, parent/eclipse-code-formatter.xml
The Eclipse formatter doesn't have the ability to reformat `if`/`for`/`do`/`while` statements[1] with added braces[2], because that ability is part of the Code Cleanup feature instead. However, its formatter does support the style where control statements are put in a single line where possible[3].
1. Eclipse code formatter profile changed to allow style [3] below.
2. Checkstyle rules changed to check that control statements follow these rules: braces for multiple lines, but optional for single lines.
3. Profile changed to ensure newline at end of file.
4. Allow formatter to join lines. Disallowing joined lines has been crippling the formatter's ability to format nicely. This should produce better results, and in particular, it will enable it to convert style [1] into style [3]. We'll …
=> style: braces for multiline control statements

server/zanata-frontend/src/frontend/app/styles/style.less, server/zanata-war/src/main/webapp/tm/home.xhtml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1776
The last dropdown in the list of the admin translation memory page was not showing correctly - needed some specific css to make the parent block bigger (.g--padded with padding-bottom:4.2em).
- Code quality
- Testing
[Considerations for …
=> fix: padding added to admin TM page so that dropdown shows (ZNTA-1776)

server/zanata-frontend/src/editor/__tests__/utils/UtilTest.js, server/zanata-frontend/src/editor/__tests__/utils/phraseTest.js, server/zanata-frontend/src/editor/app/actions/phrases.js, server/zanata-frontend/src/editor/app/utils/Util.js, server/zanata-frontend/src/editor/app/utils/phrase.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1767
Ensured the redux backend populates empty translation objects so that the frontend will allow adding translations.
Also includes an incidental fix for the save buttons - they weren't selecting "Translated" button automatically upon change like they should have been.
- Code quality
- …
=> Allow translating previously untranslated strings in React editor (ZNTA-1767)

server/zanata-frontend/src/frontend/__tests__/utils/UtilTest.js, server/zanata-frontend/src/frontend/__tests__/utils/phraseTest.js, server/zanata-frontend/src/frontend/app/editor/actions/phrases.js, server/zanata-frontend/src/frontend/app/editor/utils/Util.js, server/zanata-frontend/src/frontend/app/editor/utils/phrase.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1767
Ensured the redux backend populates empty translation objects so that the frontend will allow adding translations.
Also includes an incidental fix for the save buttons - they weren't selecting "Translated" button automatically upon change like they should have been.
- Code quality
- …
=> fix(ZNTA-1767): allow adding new translations in React editor

server/zanata-war/src/main/java/org/zanata/i18n/Messages.java, server/zanata-war/src/main/java/org/zanata/ui/faces/FacesContextProducer.java, server/zanata-war/src/main/java/org/zanata/ui/faces/FacesMessages.java, server/zanata-war/src/test/java/org/zanata/cdi/WithActiveWindow.java, server/zanata-war/src/test/java/org/zanata/cdi/WithActiveWindowInterceptor.java, server/zanata-war/src/test/java/org/zanata/ui/faces/FacesMessagesTest.java
This logging isn't useful:
```
2017-02-27 07:01:14,607 INFO  [org.zanata.ui.faces.FacesMessages] (default task-25) message to user (wid: 1): Please log in first)
2017-02-27 07:01:16,561 INFO  [org.zanata.ui.faces.FacesMessages] (default task-27) message to user (wid: 1): Please log in first)
2017-02-27 07:01:16,564 INFO  [org.zanata.ui.faces.FacesMessages] (default task-27) message to user (wid: 1): Please log in first)
2017-02-27 07:01:44,621 INFO  [org.zanata.ui.faces.FacesMessages] (default task-30) message to user (wid: 1): Please log in first)
2017-02-27 07:01:44,624 INFO  [org.zanata.ui.faces.FacesMessages] (default task-30) message to user (wid: 1): Please log in first)
2017-02-27 07:01:46,593 INFO  [org.zanata.ui.faces.FacesMessages] (default task-31) message to user (wid: 1): …
```
=> Reduce log verbosity in FacesMessages

client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PropertiesStrategy.java, client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/UTF8PropertiesStrategy.java, client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/XliffStrategy.java
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1729
- property and xliff projects will ignore how file mapping rules are set in turns of the translation file name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/260)
=> ZNTA-1729 - fix translation file ignore mapping rules

Jenkinsfile, build-tools/src/test/java/TestJenkinsfile.java
Using [locks](https://plugins.jenkins.io/lockable-resources) will allow us to control the number of concurrent integration tests for (a) mainline branches (`master`, `release`, `legacy`), (b) other, non-mainline branches and (c) pull requests. Unit tests will not be affected.
When multiple integration tests for a pipeline are delayed by locking, the earlier tests will be aborted by the later tests (using [milestones](https://plugins.jenkins.io/pipeline-milestone-step)), which will reduce the resource requirements considerably.
The reviewer can use this …
=> chore: limit concurrency for integration tests

Jenkinsfile
- Code quality
- Testing
----
--- …
=> chore(Jenkinsfile) add workaround for JENKINS-38813

server/functional-test/src/main/java/org/zanata/page/AbstractPage.java, server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java, server/functional-test/src/main/java/org/zanata/page/utility/PageSource.kt
- Code quality
- Testing
----
--- …
=> chore: shorten HTML for test logs (dino game)

server/zanata-frontend/src/frontend/package.json, server/zanata-frontend/src/frontend/scripts/build-icon-spritesheet.js, server/zanata-frontend/src/frontend/scripts/build.js, server/zanata-frontend/src/frontend/scripts/createIconsComponent.js, server/zanata-frontend/src/frontend/scripts/generateIconList.js, server/zanata-frontend/src/frontend/webpack.config.js, server/zanata-frontend/src/frontend/webpack.prod.config.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1829
Changes `make build` and `make draft` to use separate script files. Some helper scripts are updated and removed from package.json since they can be imported directly to the new build script.
The commands `make build` and `make draft` are affected. Both should still generate the same files in `dist`. The commands and directory are all from zanata-platform/server/zanata-frontend/src/frontend.
The ultimate test is to run a full build of zanata server (with and without the `optimise` flag) and make sure the editor still works.
As a reviewer, you should check the guidelines regularly for updates, and …
=> Split build commands to a separate file (ZNTA-1829)

Jenkinsfile
- Code quality
- Testing
----
--- …
=> chore(Jenkinsfile): use more locks, more concurrent builds

Jenkinsfile
https://github.com/jenkinsci/github-pr-coverage-status-plugin
- Code quality
- Testing
---- …
=> chore(Jenkinsfile): compare PR coverage

server/zanata-model/src/main/java/org/zanata/hibernate/search/ContainingWorkspaceBridge.java, server/zanata-model/src/main/java/org/zanata/hibernate/search/EntityStatusIndexingInterceptor.java, server/zanata-model/src/main/java/org/zanata/hibernate/search/IndexFieldLabels.java, server/zanata-model/src/main/java/org/zanata/hibernate/search/TextFlowTargetEntityIndexingInterceptor.java, server/zanata-model/src/main/java/org/zanata/model/HTextFlowTarget.java, server/zanata-war/src/main/java/org/zanata/events/TransMemoryMergeEvent.java, server/zanata-war/src/main/java/org/zanata/search/HTextFlowTargetIndexingStrategy.java, server/zanata-war/src/main/java/org/zanata/service/impl/EntityListenerUtil.java, server/zanata-war/src/main/java/org/zanata/service/impl/ReindexChildrenEntityEventListener.java, server/zanata-war/src/main/java/org/zanata/service/impl/SlugEntityUpdatedListener.java, server/zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java, server/zanata-war/src/main/java/org/zanata/webtrans/server/HibernateIntegrator.java, server/zanata-war/src/test/java/org/zanata/service/impl/SlugEntityUpdatedListenerTest.java, server/zanata-war/src/test/java/org/zanata/service/impl/TranslationMemoryServiceImplTest.java
- exclude HTextFlowTargets from obsolete project or version
- index project id instead of slug (so it's immutable)
- index version id instead of slug (so it's immutable)
- reindex when project or version become obsolete
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2022
note to QA:
- need to perform re-index HTextFlowTarget in administration-> manage search
- if a project or version is deleted (status become obsolete in database), there should be a re-index log message in console. It should be transparent to user
- TM merge should still work as before. Need to make sure when rejecting TM from different project, it does what it says. e.g. when you choose reject TM from different project, you should not get TM from different project
--- …
=> ZNTA-2022 - change HTextFlowTarget index strategy

server/gwt-editor/src/main/webapp/webtrans/Application.xhtml, server/zanata-frontend/src/frontend/app/actions/common-actions.js, server/zanata-frontend/src/frontend/app/actions/explore-actions.js, server/zanata-frontend/src/frontend/app/actions/glossary-actions.js, server/zanata-frontend/src/frontend/app/actions/languages-actions.js, server/zanata-frontend/src/frontend/app/actions/profile-actions.js, server/zanata-frontend/src/frontend/app/components/Nav/index.jsx, server/zanata-frontend/src/frontend/app/config.js, server/zanata-frontend/src/frontend/app/containers/App.js, server/zanata-frontend/src/frontend/app/containers/Explore/GroupTeaser.jsx, server/zanata-frontend/src/frontend/app/containers/Explore/LanguageTeamTeaser.jsx, server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx, server/zanata-frontend/src/frontend/app/containers/Root.js, server/zanata-frontend/src/frontend/app/containers/UserProfile/index.jsx, server/zanata-frontend/src/frontend/app/history.js, server/zanata-frontend/src/frontend/app/index.js, server/zanata-frontend/src/frontend/app/legacy.js, server/zanata-frontend/src/frontend/app/utils/UrlHelper.js, server/zanata-frontend/src/frontend/index.html, server/zanata-war/src/main/webapp/WEB-INF/template/template.xhtml, server/zanata-war/src/main/webapp/a/index.xhtml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2004
This also splits the base URL config into 3 separate URLs to allow finer control, such as allowing search and navigation in the watch mode (`make watch`) by passing in the relevant URLs.
There were many places accessing `window.config`, which makes this a bigger change than it should have been. This moves config loading to a single place (`config.js`), which will make it far easier to change the config in future, and easier to mock in testing.
This could impact API requests and navigation from the frontend app pages:
- /explore
- /glossary
- /glossary/project/{projectSlug}
- /languages
- /profile/view/{username}
Check that those pages can do all their operations that load data from the server (such as searching, opening …
=> chore: split frontend URL config to multiple URLs

parent/pom.xml
When running build -Q --server, it will also skip checkstyle and animal sniffer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/386)
=> quick build also skips checkstyle and animal sniffer

server/gwt-editor/src/main/java/org/zanata/webtrans/client/util/ContentStateToStyleUtil.java, server/zanata-war/src/test/java/org/zanata/webtrans/client/util/ContentStateToStyleUtilTest.java
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2061
Change colour of rejected text in translation history modal of GWT editor to be orange instead of red.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#n …
=> fix(ZNTA-2061) corrected colour of translation history rejected text

server/functional-test/src/test/java/org/zanata/feature/search/comp/GroupSearchCTest.java
Workaround: Sometimes data is not cleared properly. Alter test to search for 'groop' to match nothing.
- Code quality
- Testing
---- …
=> fix(test): Workaround flake in test suite

.gitattributes, server/zanata-frontend/.gitattributes
Otherwise the linter complains about CR-LF when building on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/422)
=> Add .gitattributes for scripts and JS files

server/zanata-frontend/src/frontend/jest.config.json, server/zanata-frontend/src/frontend/package.json
Right click on a test and choose "Create ... test" (with jest icon next to it). Then all you need to do is fill in jest.config.json file path as Configuration file , node path as Node interpreter (if it can't find it)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/432)
=> externalize jest config so that tests can be run in IDE

server/zanata-frontend/src/frontend/app/styles/style.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2159
Other issue needing urgent fix in release: https://zanata.atlassian.net/browse/ZNTA-2158
Added css to make sure the version-group dropdown shows the entire list of options instead of being cut off in the parent container.
Before:
After:
Another issue (ZNTA-2158) which I have fixed in master but not in release correctly has been resolved in this issue since it only involved removing one word from a css rule. This is to make sure the GWT editor does not break words across multiple lines in the TM panel.
It now looks like this:
As a reviewer, you should check the guidelines regularly for updates, …
=> fixes:(ZNTA-2159) version-group dropdown now showing correctly (ZNTA-2158) words no longer breaking over multiple lines in GWT

client/zanata-rest-client/src/main/java/org/zanata/rest/client/AsyncProcessClient.java, client/zanata-rest-client/src/main/java/org/zanata/rest/client/ResponseStatusFilter.java, client/zanata-rest-client/src/main/java/org/zanata/rest/client/SourceDocResourceClient.java, client/zanata-rest-client/src/main/java/org/zanata/rest/client/StatisticsResourceClient.java, client/zanata-rest-client/src/main/java/org/zanata/rest/client/TransDocResourceClient.java
https://zanata.atlassian.net/browse/ZNTA-2178
- Code quality
- Testing …
=> fix: handle old rest endpoint

Jenkinsfile
Fixes error when build fails:
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object (org.zanata.jenkins.Notifier error hudson.AbortException)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/505)
=> fix(Jenkinsfile): RejectedAccessException

server/services/src/main/java/org/zanata/ZanataInit.java
This avoids the need to manually delete lock files, which is nearly
always too paranoid for a non-clustered application. Until we set up
clustering, it should be safe to delete the lock files, even on NFS, as
long as there are other ways of avoiding multiple instances of Zanata
(eg some sort of native process/service management). But we log a
warning just in case.
https://zanata.atlassian.net/browse/ZNTA-1786
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/513)
=> fix(ZNTA-1786): just warn if lock files are found on NFS

Jenkinsfile
This should make it easier to find the cause if build fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/532)
=> Reduce verbosity at tail of build log

docs/user-guide/projects/project-settings.md
This change fixes the event names in the webhook doc.
Not sure if I need an issue to fix the doc, let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/531)
=> Update the webhook event names

.mvn/extensions.xml, Jenkinsfile
This should help to prevent build timings from pushing important information off the screen when builds fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/523)
=> Move build timings to CSV file

server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css, server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2240
Changed the css classname of SidebarEditor to 'sidebar-editor' so that the react sidebar component works correctly. I have tested this and it resolves the bug in master
- JIRA link
----
--- …
=> fix(ZNTA-2240) editor sidebar now works as expected

server/zanata-frontend/src/frontend/app/editor/components/Button/index.css, server/zanata-frontend/src/frontend/app/editor/components/SplitDropdown/index.css, server/zanata-frontend/src/frontend/app/editor/components/SplitDropdown/index.js, server/zanata-frontend/src/frontend/app/editor/components/SuggestionTranslationDetails.js, server/zanata-frontend/src/frontend/app/editor/components/TransUnitTranslationFooter.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2241
fix(ZNTA-2241) change css classnames for dropdown buttons in editor which were broken in refactor of editor css
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/588)
=> fix(ZNTA-2241) change css classnames for dropdown buttons 

server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, server/zanata-frontend/src/frontend/app/editor/components/GlossaryTerm/index.js, server/zanata-frontend/src/frontend/app/editor/containers/ActivityTab.js, server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css, server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css, server/zanata-frontend/src/frontend/app/editor/containers/TranslationInfoPanel/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2219
Alongside changing to a badge (which required adding badge css to the editor css files), padding has been added to the bottom of the glossary table to improve spacing + minor tweaks to improve mobile view (show count).
- JIRA link
----
--- …
=> fix(ZNTA-2219: glossary count in editor now uses badge styling

server/docker/conf/zanata-config.cli, server/services/src/main/java/org/zanata/security/AuthenticationManager.java, server/services/src/main/java/org/zanata/security/SamlAccountService.kt, server/services/src/main/java/org/zanata/servlet/SAMLFilter.kt, server/services/src/test/java/org/zanata/security/SamlAccountServiceTest.kt, server/services/src/test/java/org/zanata/servlet/SAMLFilterTest.kt
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2227
If you have an internal account already, when you choose to sign in using Single Sign On, it will try to match existing account with email. If there is a match, the SSO process will reuse that account (e.g. you won't need to create a new user and do the activation email thing)
- JIRA link
----
--- …
=> ZNTA-2227 auto merge saml user to existing account

server/services/src/main/java/org/zanata/rest/service/ResourceUtils.java, server/services/src/test/java/org/zanata/rest/service/ResourceUtilsTest.java
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2100
Language field locale in gettext file headers should always be underscore-separated.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-an …
=> fix(ZNTA-2100): Gettext "Language" header field inconsistent format

server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/GlossaryDetailsPresenter.java, server/gwt-editor/src/main/java/org/zanata/webtrans/client/resources/UiMessages.java, server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/GlossaryView.java, server/gwt-editor/src/test/java/org/zanata/webtrans/client/presenter/GlossaryDetailsPresenterTest.java, server/services/src/main/java/org/zanata/service/impl/GlossarySearchServiceImpl.java, server/services/src/test/java/org/zanata/webtrans/server/rpc/GetGlossaryHandlerJpaTest.java, server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, server/zanata-frontend/src/frontend/app/editor/components/GlossaryTerm/GlossaryTerm.story.js, server/zanata-frontend/src/frontend/app/editor/components/GlossaryTerm/index.js, server/zanata-frontend/src/frontend/app/editor/components/GlossaryTermModal/component.js, server/zanata-frontend/src/frontend/app/editor/containers/GlossaryTab.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1668
Glossary entries have value, even if they are not translated. Show all
matching entries with translations if available.
Tester notes:
- Entries in system and project glossary that match the source, or search term, will show
- Entries that have a translation for the current language will show it
- Entries that do not have a translation for the current language show `-none-` in lighter text and a disabled copy button
- Source / Target in glossary search now shows Source / Translation
The reviewer …
=> fix(ZNTA-1668): Allow translator to see untranslated glossary entries

server/functional-test/src/main/java/org/zanata/page/webtrans/EditorPage.java
Fix a click action in functional test that was not controlled or pointing to the appropriate element.
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/614)
=> fix(test): Fix validation box click in test

server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, server/zanata-frontend/src/frontend/app/editor/components/ActivityFeedItem/index.js
Storybook - see Activity Feed Item
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-53
Should be able to copy translation history/revisions to Editor - this is achieved through adding a copy button to each translation in the Activity Tab
- JIRA link
----
--- …
=> feat(ZNTA-53) allow copy of translations from Activity Panel in Editor

server/docker/conf/zanata-config.cli, server/services/src/main/java/org/zanata/servlet/UrlRewriteConfig.java, server/services/src/test/java/org/zanata/servlet/UrlRewriteConfigTest.kt
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2303
Instance with single openid provider enabled will land on 404 page instead of dashboard.
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/630)
=> ZNTA-2303 fix single openid provider landing on 404

server/docker/conf/zanata-config.cli
[LOGMGR-45](https://issues.jboss.org/browse/LOGMGR-45) implies that we should now be able to inherit the filters as we were trying to do, but it's unclear if it can be done in the appserver configuration: https://developer.jboss.org/message/978927#978927
This configuration change adds the filter to each of the log categories which Weld might use for logging exceptions as DEBUG.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/565)
=> Log all Weld exceptions in Docker runs

server/zanata-frontend/src/frontend/.babelrc
We shouldn't be using Stage 0/1/2 features unless we have a good reason for accepting the risk; in my opinion anything less than Stage 3 is too unstable for our maintenance requirements. Even with Stage 3 there's a certain risk of breakage.
- https://babeljs.io/docs/plugins#presets-stage-x-experimental-presets-
- https://thefeedbackloop.xyz/tc39-process-sketch-stage-2/
This change replaces the Babel preset `stage-0` with `stage-3`. Those plugins from Stages 0, 1 and 2 which we currently use have then been added back in (for now). 
This change also replaces the preset `es2015` with [`env`](https://babeljs.io/docs/plugins/preset-env/), which will pick up new versions as they are standardised (currently up to `es2017`).
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Minimise use of draft Babel plugins

server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, server/zanata-frontend/src/frontend/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap, server/zanata-frontend/src/frontend/app/components/Icon/Icon.story.js, server/zanata-frontend/src/frontend/app/components/Icon/index.jsx, server/zanata-frontend/src/frontend/app/components/Notification/component.js, server/zanata-frontend/src/frontend/app/editor/components/TransUnitStatus.js, server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/ImportedTMDetailPanel.js, server/zanata-frontend/src/frontend/app/styles/style.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2312
- Props for Icon component corrected so className is used everywhere instead of size
- Updated snapshot tests
- Fixed alignment and size of notification modal icons
- JIRA link
----
--- …
=> fix(ZNTA-2312) props for Icon component

server/zanata-frontend/src/frontend/app/editor/app.css, server/zanata-frontend/src/frontend/app/editor/components/TransUnitSourcePanel.js, server/zanata-frontend/src/frontend/app/editor/selectors/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-68
When a filter is active and the "text" key is one of the keys in the filter, highlight the appropriate matching parts of text in the search results. Text in the source text that matches the value for "text" should be highlighted.
Highlighting of the translation text may not be possible due to this text being editable as part of a text-area.
- JIRA link
---- …
=> feat(ZNTA-68): Implement highlighting words in source text that match filter text in editor.

common/zanata-adapter-glossary/src/main/java/org/zanata/adapter/glossary/GlossaryCSVReader.java, common/zanata-adapter-glossary/src/test/java/org/zanata/adapter/glossary/GlossaryCSVReaderTest.java, common/zanata-adapter-glossary/src/test/resources/glossary/translate1.csv, common/zanata-adapter-glossary/src/test/resources/glossary/translate2.csv, docs/user-guide/glossary/upload-glossaries.md
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2247
Still expects column 0 to be the source locale, but checks that the
PoS and Description columns are named. This prevents garbage in
said fields.
This change also prevents repeatedly setting these fields, only
doing so once per row.
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> fix(ZNTA-2247): Remove magic numbers for glossary csv columns

server/zanata-war/src/main/webapp/resources/assets/css/style.css
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2328
remove zanata-assets css that is changing input placeholder text color
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/655)
=> fix(ZNTA-2328) update placeholder text color

server/zanata-frontend/src/frontend/app/editor/components/TransUnitTranslationPanel.js, server/zanata-frontend/src/frontend/app/editor/containers/SettingsPanel.js, server/zanata-frontend/src/frontend/app/editor/reducers/index.js, server/zanata-frontend/src/frontend/app/editor/reducers/settings-reducer.js, server/zanata-frontend/src/frontend/app/editor/reducers/settings-reducer.test.js, server/zanata-frontend/src/frontend/package.json, server/zanata-frontend/src/frontend/yarn.lock
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2325
Implemented Syntax Highlighting as an option in the React Editor
There a quite a few styles to choose from for the syntax highlighting which can been demoed here:
http://conor.rodeo/react-syntax-highlighter/demo/
altier-lakeside-light is the style being used in the editor to give some contrast, dark themes to not appear to work in the editor (possibly a css clash)
The checkbox is available in the editors settings panel and the selection should persist after refreshing.
- JIRA link
See [Zanata Development …
=> ZNTA-2325 Implement Syntax Highlighting as an option in the React Editor

server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2330
Small stylefix for the highlighting in the editor, classname was not applying
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/659)
=> style(ZNTA-2330): Fix classname for style highlighting in editor

server/zanata-frontend/src/frontend/app/editor/components/FilterToggle/index.css, server/zanata-frontend/src/frontend/app/editor/components/FilterToggle/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2339
Fix alignment of FilterToggle translation counts in editor - add a more appropriate border radius that does not shift the toggles when active.
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/667) …
=> fix(ZNTA-2339) fix FilterToggle backgrounds in editor

server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2342?streamsSourceProduct=jira
Now filtering the list of phrases to only include those matching the status of translation filter selection.
Keyboard navigation using ALT+UP or ALT+DOWN should no longer select targets that are not displayed.
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> fix(ZNTA-2342): editor filter by translated state breaking keyboard navigation

server/zanata-frontend/src/frontend/app/editor/components/PhraseStatusFilter/PhraseStatusFilter.test.js, server/zanata-frontend/src/frontend/app/editor/components/SuggestionSearchInput/index.js, server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2341
* Added spacing above alpha editor suggestions search
* Removed the duplicate 'x' that closes the suggestions search
* Updated tests
I had to start again on a clean branch from release after all those release changes were made yesterday so it will need a second review. 
- JIRA link
----
--- …
=> fix(ZNTA-2341) add top spacing to editor search

server/zanata-frontend/src/frontend/app/styles/style.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2363
Width of project version languages list items set to 100%
**Before**
**After**
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/681)
=> fix(ZNTA-2363) width of project version languages list items set to 100%

server/zanata-frontend/src/frontend/app/containers/Glossary/index.less
JIRA issue URL: NA
remove extra border from top of glossary rows
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/686)
=> Quick glossary fix

server/zanata-frontend/src/app/styles/gwt.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2369
Fix word wrapping for GWT translation history modal comments
**Result**
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/691)
=> fix(ZNTA-2369) word wrapping in GWT history modal comments

server/services/src/test/resources/META-INF/persistence.xml, server/zanata-model-test/src/main/resources/arquillian/persistence.xml, server/zanata-war/src/main/webapp-jboss/WEB-INF/classes/META-INF/persistence.xml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2367
The changes in https://github.com/zanata/zanata-platform/pull/513 were intended to work with the `native` lock strategy, but I forgot to actually request `native` locking in `persistence.xml`.
- JIRA link
----
--- …
=> fix(ZNTA-2367): use native lock strategy

server/zanata-frontend/src/app/styles/gwt.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2371
fix(ZNTA-2371) fix height of panels in Dashboard so version options dropdown is visible
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/696)
=> fix(ZNTA-2371) fix height of panels in Dashboard

server/zanata-frontend/src/app/styles/gwt.less
Reverts zanata/zanata-platform#696 which prevents scrolling on project pages and breaks tests like `org.zanata.feature.project.EditProjectAboutTest.addAboutPageDetails`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/701)
=> Revert "fix(ZNTA-2371) fix height of panels in Dashboard"

server/zanata-war/src/main/webapp/resources/assets/css/application.css
JIRA issue URL:https://zanata.atlassian.net/browse/ZNTA-2091
Widened the GWT editors vertical scrollbar using webkit-scrollbar.
QA: Style will only be viewable in webkit broswers (Chrome)
Firefox still has no support for scrollbar styling without Javascript: https://stackoverflow.com/questions/6165472/custom-css-scrollbar-for-firefox
- JIRA link
----
--- …
=> style(ZNTA-2091): Widen GWT Editor scrollbar using webkit-scrollbar

server/zanata-frontend/src/frontend/app/editor/components/Button/index.css, server/zanata-frontend/src/frontend/app/editor/components/EditorSearchInput/index.css, server/zanata-frontend/src/frontend/app/editor/containers/ControlsHeader.js, server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2382
- cursor: pointer added to editor buttons 
Please note: does not show on left-hand part of Translated/Needs Work buttons with dropdowns because they are disabled
- controlHeader height and padding fix - buttons now work on smaller screen sizes.
- text-alignment in TransUnit footer IconButtons - fixed so that it was tidier
- JIRA link
---- …
=> fix(ZNTA-2382) minor editor button UX issues

server/docker/conf/zanata-config.cli, server/zanata-frontend/src/.eslintrc, server/zanata-frontend/src/README.md, server/zanata-frontend/src/scripts/dev-server.config.js, server/zanata-frontend/src/scripts/dev-server.js, server/zanata-frontend/src/webpack.config.js
Right now they don't actually work together (the last server to be started seems to clobber the first one), but at least I've parameterised the port and URL. Also, the console messages now include full URLs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/708)
=> Run watch tasks on separate ports

server/services/src/test/java/org/zanata/adapter/AdapterUtilsTest.java
Tests for AdapterUtils
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/692)
=> test(unittest): AdapterUtils unit test

build-tools/src/main/resources/zanata-build-tools/versions-rules.xml, parent/pom.xml
This will allow us to generate a report for outdated dependencies, eg
```
./mvnw --batch-mode --threads 1 \
-DallowMajorUpdates=false \
versions:display-plugin-updates \
versions:display-dependency-updates \
versions:display-property-updates
```
or perhaps attempt automatic upgrades with something a bit like this (see also https://www.dependencies.io/ - Java support "coming soon"):
```
./mvnw --batch-mode --threads 1 \
-DallowMajorUpdates=false \
versions:update-properties \
versions:use-latest-versions
```
- JIRA link
See [Zanata Development …
=> Update versions-maven-plugin; ignore prereleases

server/pom.xml
Reverts zanata/zanata-platform#726
For some reason the Kotlin upgrade breaks rundev:
`org.hibernate.boot.MappingException: Unable to resolve explicitly named mapping-file : META-INF/orm.xml : origin(META-INF/orm.xml)`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/728)
=> Revert "Update Kotlin to 1.2.21"

server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/ForceReviewCommentWidget.java, server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, server/zanata-frontend/src/app/editor/components/RejectTranslationModal/RejectTranslationModal.story.js, server/zanata-frontend/src/app/editor/components/RejectTranslationModal/index.js, server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/CriteriaDropdown.js, server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/CriteriaDropdown.test.js, server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/PriorityDropdown.js, server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/PriorityDropdown.test.js, server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/index.css, server/zanata-frontend/src/app/editor/containers/RejectTranslationModal/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2408
- set RejectTranslationModal Critera dropdown to have empty field by default - GWT and Storybook Editor
- add truncating with ellipsis to criteria with long text
- small css fixes to modal (flex alignment, padding)
- updated snapshots and test files
- JIRA link
----
=> fix(ZNTA-2408) set RejectTranslationModal Criteria dropdown to have empty field by default

server/gwt-editor/src/main/java/org/zanata/webtrans/client/resources/UiMessages.java, server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/GlossaryDetailsView.java, server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/GlossaryDetailsView.ui.xml, server/zanata-frontend/src/app/styles/legacy.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2410
Increased width of close/cancel buttons in GWT to handle text correctly. The cancel text was overriding the button width.
- JIRA link
----
=> fix(ZNTA-2410) width of close buttons in GWT now handles text correctly

docs/index.md, docs/user-guide/api/api.md, parent/pom.xml, pom.xml
Replace API docs host in 
old: https://zanata.ci.cloudbees.com/job/zanata-api-site/site/ 
new: http://zanata.org/zanata-platform/
old: https://zanata.ci.cloudbees.com/job/zanata-api-site/site/zanata-common-api/rest-api-docs/index.html
new: http://zanata.org/zanata-platform/rest-api-docs/
`mvn clean package site -DskipTests -Dfindbugs.skip -pl :build-tools,:api,:zanata-common-api,:zanata-platform -Dgithub.global.oauth2Token={github token}
`
- JIRA link
----
*This …
=> docs: replace api doc host with github

server/zanata-frontend/src/app/editor/components/TranslatingIndicator/TranslatingIndicator.test.js, server/zanata-frontend/src/app/editor/components/TranslatingIndicator/index.js, server/zanata-frontend/src/app/editor/containers/ControlsHeader.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2401
With information about the user permissions for Translating and Reviewing available in the React Editor, use the Icon and Text in top left of the page to relate this information to the users.
The text for each mode can be localized as it has been for "Translating"
Three different modes should appear as below depending on the users permissions for a project:
- JIRA link
---- …
=> feat(ZNTA-2401): editor user mode display (Translating/Viewing/Reviewing)

server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml, server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java, server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml, server/gwt-editor/src/main/webapp/webtrans/Application.xhtml, server/services/pom.xml, server/services/src/main/java/org/zanata/util/Webjars.kt, server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap, server/zanata-frontend/src/app/editor/components/TextDiff/TextDiff.test.js, server/zanata-frontend/src/app/editor/components/TextDiff/index.js, server/zanata-frontend/src/package.json, server/zanata-frontend/src/yarn.lock
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2396
Duplicates: https://zanata.atlassian.net/browse/ZNTA-2397 
Zanata TM highlighting is confusing for low-similarity matches due to a mismatch between the backend TM matching and the frontend (GWT and React Editor) diffing algorithms.
The TM Suggestions should now correctly display matches on full words for both the GWT editor and Alpha editor (using the same diff library). 
Punctuation not effect the diff now (punctuation causing the initial issue with matching words not being displayed).
The matching words of a source/target diff should be more evident now:
The simple diff mode has also been modified to highlight the Matching parts, rather than non-matching:
The diff views in the Alpha editor should be identical.
- JIRA link
- …
=> fix(ZNTA-2396): TM suggestion highlighting shows mismatched diff 

server/zanata-frontend/src/app/containers/Languages/index.js, server/zanata-frontend/src/app/containers/Languages/index.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2429
height of languages page table now scrolls to fit content
- JIRA link
----
=> fix(ZNTA-2429): language page height scroll

server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/Breadcrumb.ui.xml, server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/AppView.ui.xml, server/gwt-editor/src/main/webapp/webtrans/Application.xhtml, server/zanata-frontend/src/app/styles/legacy.less, server/zanata-war/src/main/webapp/resources/assets/css/gwt-editor.css
Remove all frontend dependency (js and css) from gwt.
- Remove sidebar from gwt-editor
- Clean up unused css classes due to the removal
- Remove frontend.legacy.js import from gwt-editor
- remove frontend.css import from gwt
- rename application.css to gwt-editor.css
https://zanata.atlassian.net/browse/ZNTA-2454
- JIRA link
----
=> fix: remove sidebar from gwt editor

server/zanata-frontend/src/app/styles/legacy.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2446
* increase clickable area for Update Translation modal by increasing the width of parent classes to 100%. all of these changes had to be made to ensure the entire button was clickable.
* remove icon that cannot be clicked - poor UX design
- JIRA link
----
=> fix(ZNTA-2446): increase clickable area for Update Translation modal

server/zanata-frontend/src/app/editor/containers/Sidebar/index.css
JIRA issue URL:  https://zanata.atlassian.net/browse/ZNTA-2473
Improve spacing and layout of activity panel in react editor
- JIRA link
----
=> fix(ZNTA-2473) background colour of editor sidebar panels

server/zanata-frontend/src/app/components/Sidebar/index.less, server/zanata-frontend/src/app/containers/Admin/index.less, server/zanata-frontend/src/app/containers/Explore/index.less, server/zanata-frontend/src/app/containers/Glossary/index.less, server/zanata-frontend/src/app/containers/ProjectVersion/index.less, server/zanata-frontend/src/app/editor/components/Dropdown/index.css, server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.css, server/zanata-frontend/src/app/editor/components/GlossaryTermModal/index.css, server/zanata-frontend/src/app/editor/components/TransUnit/index.css, server/zanata-frontend/src/app/editor/containers/Root/index.css, server/zanata-frontend/src/app/editor/containers/Sidebar/index.css, server/zanata-frontend/src/app/editor/containers/SuggestionDetailsModal/index.css, server/zanata-frontend/src/app/styles/legacy.less, server/zanata-frontend/src/app/styles/style.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2400
Use 'rem', not 'em' in frontend css 
https://getflywheel.com/layout/rems-ems-and-pixels-whats-the-difference/
Px or pixels is still used where absolute sizing must be set
- JIRA link
----
=> refactor(ZNTA-2400): Consistency of sizes in css (use rem)

server/zanata-frontend/src/webpack.config.js
AntD build in webpack.config was interfering with storybook config files compilation.
Applied the storybook filter to the AntD build to resolve the issue.
- JIRA link
----
=> fix: storybook frontend/editor builds

server/zanata-frontend/src/app/styles/ant-theme-vars.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2491
fix(ZNTA-2491) add utility classes for text and background status colours
- JIRA link
----
=> fix(ZNTA-2491) add status utility classes to frontend

server/zanata-frontend/src/app/editor/containers/Sidebar/index.css, server/zanata-frontend/src/app/editor/containers/Sidebar/index.js
Dynamically size editor sidebar to match header expanded/contracted states
- JIRA link
----
=> style: dynamically size editor sidebar 

server/zanata-frontend/src/package.json, server/zanata-frontend/src/webpack.config.js, server/zanata-frontend/src/yarn.lock
webpack was configured to load antd through the babel-loader, which is no longer installed.
We can instead use the awesome-typescript-loader, and the ant.design [ts-import-plugin](https://github.com/Brooooooklyn/ts-import-plugin) to [import ant.design components on-demand](https://ant.design/docs/react/getting-started#Import-on-Demand).
- JIRA link
----
=> fix: use tsImportPlugin to load ant.design in webpack build

server/zanata-frontend/src/app/entrypoint/index.js, server/zanata-frontend/src/package.json, server/zanata-frontend/src/yarn.lock
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2488
So that developers can quickly make padding/spacing modifications to css components where antd is not suitable, the Tachyons css utility package has been added via yarn and loaded in frontend entrypoint.
- For an overview of the utility styles: http://tachyons.io/
- Utility styles in detail: http://tachyons.io/docs
- All css classes: https://github.com/tachyons-css/tachyons/blob/master/css/tachyons.css
To test, add one of the utility classes to a pre existing css class in the browser inspector and inspect change
_eg. add `ttu` to some text class to convert it all to uppercase_
- JIRA link
- QA needs to evaluate against the …
=> style(ZNTA-2488) add Tachyons css utility classes to frontend

server/zanata-frontend/src/app/components/DraggableVersionPanels/DraggableVersionPanels.test.js, server/zanata-frontend/src/app/components/DraggableVersionPanels/index.tsx, server/zanata-frontend/src/app/components/Notification/component.js, server/zanata-frontend/src/app/containers/Admin/Review.js, server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx, server/zanata-frontend/src/app/containers/Explore/index.js, server/zanata-frontend/src/app/containers/Glossary/index.js, server/zanata-frontend/src/app/containers/Languages/index.js, server/zanata-frontend/src/app/containers/UserProfile/CalendarMonthMatrix.jsx, server/zanata-frontend/src/app/containers/UserProfile/RecentContributions.jsx
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2508
To test the appropriate of antd buttons and align with accessibility (a11y) standards for buttons, `aria-label="button"` was added to every antd button in frontend
- JIRA link
----
=> refactor(ZNTA-2508): add aria-label to antd buttons

server/zanata-frontend/src/app/containers/Glossary/ViewHeader.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2550
Fixed the icon and project name overlap on glossary page
's1' bstrapReact class clashed with ant design icon styles
- JIRA link
----
=> fix: glossary UI icon and project name overlap

server/functional-test/src/main/java/org/zanata/page/administration/AddLanguagePage.java, server/functional-test/src/test/java/org/zanata/feature/language/AddLanguageTest.java, server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js
Ant Design form validation getFieldDecorator method overrides the input id's, update selenium test ids to match the overridden form id's in the add language modal.
- JIRA link
----
=> fix: AddLanguageTest selenium ids

server/zanata-frontend/src/app/components/TMX/TMXExportModal.js, server/zanata-frontend/src/app/styles/antd.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2553
The Ant Design badge styles appeared to cause a bug which affected the layout of the TMX Export modal, removed this component to resolve the issue.
- JIRA link
----
=> fix(ZNTA-2554): remove ant design badge component

server/zanata-frontend/src/app/styles/frontend-jsf.less, server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/delete_group_confirmation_modal.xhtml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2517
fix(ZNTA-2517) add ellipsis to handle long group names in delete group modal
- JIRA link
----
=> fix(ZNTA-2517) add ellipsis to delete group modal

server/zanata-frontend/src/app/editor/components/EditorSearchInput/EditorSearchInput.test.js, server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.css, server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2584
Found other components had the same issue with an unwanted collapse header, I could use the Ant Collapse with a controlled panel by hiding the header.
Updated the styles to match the new components elements:
- JIRA link
----
=> refactor(ZNTA-2584): EditorSearchInput to use Ant Collapse

server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java, server/services/src/main/java/org/zanata/email/ContactAdminEmailStrategy.java, server/services/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java, server/services/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java, server/services/src/main/java/org/zanata/email/DeclineLanguageRequestEmailStrategy.java, server/services/src/main/java/org/zanata/email/RequestToJoinLanguageEmailStrategy.java, server/services/src/main/java/org/zanata/email/RequestToJoinVersionGroupEmailStrategy.java, server/services/src/main/java/org/zanata/util/HtmlUtil.java, server/services/src/main/resources/org/zanata/email/templates/decline_language_team_request.vm, server/services/src/main/resources/org/zanata/email/templates/email_admin.vm, server/services/src/main/resources/org/zanata/email/templates/email_admin_anonymous.vm, server/services/src/main/resources/org/zanata/email/templates/email_coordinator.vm, server/services/src/main/resources/org/zanata/email/templates/email_language_team_members.vm, server/services/src/main/resources/org/zanata/email/templates/email_request_to_join_group.vm, server/services/src/main/resources/org/zanata/email/templates/email_request_to_join_language.vm, server/services/src/test/java/org/zanata/email/VelocityEmailStrategyTest.java, server/services/src/test/java/org/zanata/util/HtmlUtilTest.java
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-544
User messages should be plaintext, to avoid malicious links hidden in anchors
- JIRA link
----
=> fix(ZNTA-544): include user content in emails as plain text

server/zanata-frontend/src/package.json, server/zanata-frontend/src/yarn.lock
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2317
upgrade less-loader to 4.0.5 to resolve deprecation error
- JIRA link
----
=> upgrade less-loader to 4.0.5

server/zanata-frontend/src/app/editor/components/SplitDropdown/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2615
Alpha Editor translate button was not responsive.
Selecting 'needs work' from the drop down worked as expected, as does navigating to another textflow.
Nested button in SplitDropdown component caused invalid html, breaking the translate button in Firefox browsers.
- JIRA link
----
=> fix(ZNTA-2615): alpha editor translate button

server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TranslatorListWidget.ui.xml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2614
The GWT badges were applying a colour by default which I have overriden to be black (rgba(0,0,0,1)). **The opacity on this badge cannot be turned off,** have attempted everything css wise - looks like this is the best I can get it without increasing font size and messing with the whole translation panel layout
**Before**
**After**
- JIRA link
---- …
=> fix(ZNTA-2614) increase contrast of concurrent editor username in gwt editor

server/zanata-frontend/src/app/containers/Languages/index.js, server/zanata-frontend/src/app/containers/Languages/index.less, server/zanata-frontend/src/app/styles/antd.less, server/zanata-frontend/src/app/styles/style.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2591
remove extra vertical and horizontal scrolling from languages page by removing wideView container
also small styling fixes to page
- Fedora, Chrome.
- vertical scroll cannot be replicated on macOS
- JIRA link
----
=> fix(ZNTA-2591) remove extra width and height from languages page + minor styling fixes

server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2613
Hide the commentbox in the activity panel when there are no translations to comment on
- JIRA link
----
=> fix(ZNTA-2613): hide activity commentbox when no translations to comment on

server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2608
When we are adding new languages after adding 1st language, once we again click on Add new language buttons it shows previously added language details.
Fixed by resetting the form fields when closing the modal or on new language submission.
- JIRA link
----
=> fix(ZNTA-2608): reset new language form fields on close or submit

server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/EditorSearchField.ui.xml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2612
Zanata can't currently show or edit translator comments, so it's just confusing to have a feature which searches for them. It can't even show the matching comment.
- JIRA link
----
=> fix(ZNTA-2612) hide translation-comment search (can't show/edit)

server/zanata-frontend/src/app/containers/Languages/DeleteEntry.js, server/zanata-frontend/src/app/containers/Languages/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2617
fix(ZNTA-2617) add spacing to delete entry buttons on language page & fix alignment of no languages statement when page is loading
- JIRA link
----
=> fix(ZNTA-2617) add spacing to delete entry buttons on language page

Jenkinsfile, build-tools/src/test/java/TestJenkinsfile.java
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2390
Jenkins: allFuncTests
- JIRA link
----
=> chore(ZNTA-2390): run all tests if PR description contains allFuncTests

server/zanata-frontend/src/app/containers/UserProfile/index.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2620
remove padding and increase width of user profile buttons
this issue has been fixed in PR 807 (antd container refactor) targeting master also
- JIRA link
----
=> fix(ZNTA-2620) user profile button styling

server/zanata-frontend/src/app/editor/entrypoint/index.js, server/zanata-war/src/main/webapp/editor/index.xhtml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-821
In the Alpha (webapp) version, a global {{<html ... lang="en">}} attribute is present, making all the text being treated as English text in the browser. Since browsers (like Chrome) may choose fonts and sometimes OpenType features like {{locl}} by this attribute, many text end up being rendered oddly or even wrongly.
Updated the Alpha Editor index.xhtml to use the user selected language for Zanata in the html lang attribute
The selected language for Zanata also determines the localization of the alpha editor (if translations are available for the locale):
- JIRA link
- Changed …
=> fix(ZNTA-821): alpha editor to use zanata language setting as lang attribute

server/zanata-frontend/src/app/editor/components/EditorSearchInput/EditorSearchInput.test.js, server/zanata-frontend/src/app/editor/components/EditorSearchInput/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2626
Zanata can't currently show or edit translator comments, so it's just confusing to have a feature which searches for them. It can't even show the matching comment. PR #892 hid this feature in the GWT editor. This PR hides it in the React editor too.
- JIRA link
----
=> fix(ZNTA-2626): hide translation-comment search (can't show/edit)

server/zanata-frontend/src/app/containers/Explore/index.less, server/zanata-frontend/src/app/containers/Glossary/EntryModal.js, server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js, server/zanata-frontend/src/app/containers/Glossary/index.less, server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js, server/zanata-frontend/src/app/containers/Languages/index.js, server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeProjectSources.js, server/zanata-frontend/src/app/styles/antd.less, server/zanata-frontend/src/app/styles/style.less
allFuncTests
small ui fixes (input state colours) to frontend
- made hover and focus colours for react input elements use light blue, across antd and bootstrap to improve consistency
- JIRA link
----
=> fix: small ui changes

server/zanata-frontend/src/app/editor/containers/Root/index.css, server/zanata-frontend/src/app/editor/entrypoint/index.js
The antd tabs were not displaying in the editor due to a missing antd import.
This import was added to root/index.css and now the tabs are visible in production
- JIRA link
----
=> fix: add antd import to root css in editor

server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap, server/zanata-frontend/src/.storybook-frontend/storybook.less, server/zanata-frontend/src/app/components/Modal/Modal.story.js, server/zanata-frontend/src/app/containers/ProjectVersion/MTMerge.js, server/zanata-frontend/src/app/containers/UserProfile/index.jsx, server/zanata-frontend/src/app/entrypoint/index.js, server/zanata-frontend/src/app/styles/ant-theme-vars.less, server/zanata-frontend/src/app/styles/antd.less, server/zanata-frontend/src/app/styles/index.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2504
1. Run `make storybook-frontend`
2. View the Modal > MTMerge story
**Please note**: `!important` statements added to buttons in `antd.less` to ensure styling is not overridden by antd defaults (variables not available for these specific styles). this may be easier to fix once the react-bootstrap package is gone (which btw is twice the size of antd)
* list of available variables for antd components: https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
- JIRA link
See [Zanata Development …
=> ZNTA-2504: MTMerge modal story

server/services/src/main/java/org/zanata/adapter/TSAdapter.java, server/services/src/test/java/org/zanata/adapter/TSAdapterTest.java, server/services/src/test/resources/org/zanata/adapter/test-ts-untranslated.ts
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2483
Fix the corrupted TSAdapter context output
- JIRA link
----
=> fix(ZNTA-2483): Fix context in TS file write

server/zanata-frontend/src/app/containers/Glossary/ViewHeader.js, server/zanata-frontend/src/app/containers/Glossary/index.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2279
* icons in the glossary view header refactored to antd (some incl. globe and arrows for part of speech were not showing)
* languageSelect count and icon now appears next to dropdown
Screenshot 
- JIRA link
----
=> refactor(ZNTA-2279): antd icons and select styling for glossary

server/zanata-frontend/src/app/editor/components/TransUnitSourceHeader.js, server/zanata-frontend/src/app/editor/components/TransUnitTranslationHeader.js, server/zanata-frontend/src/app/editor/middlewares/new-context-fetch.js, server/zanata-frontend/src/messages/ja.json
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2078
Implement links to translations in alpha editor in the translation target panel:
Use a route param '&textflow' to select a textflow when rendering the alpha editor, eg:
/project/translate/containers/v/ver1/containersblog.txt?lang=ja&textflow=156
- JIRA link
----
=> feat(ZNTA-2078): translation permalinks in alpha editor

server/zanata-frontend/src/app/editor/containers/SuggestionsHeader.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2663
Suggestions title should be the same colour as the editor heading text
Before
After
- JIRA link
----
=> refactor(ZNTA-2529) change colour of suggestions heading in editor

server/zanata-frontend/src/app/editor/containers/MainContent.js
Rendering the conflict modal in some circumstances (using the editor Filters, pagination) causes Maincontent.js to access `selectedPhrase.conflict` when `selectedPhrase` was undefined.
Reused the `isUndefined(selectedPhrase)` check to ensure selectedPhrase is not undefined before accessing.
- JIRA link
----
=> fix: concurrent modal type error

server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
If any PO documents are changed during MT Merge, the request fails with this server-side error when trying to save the attribution:
```
06:50:29,431 ERROR [org.zanata.async.AsyncTaskManager] (pool-11-thread-2) Exception when executing an asynchronous task.: javax.persistence.PersistenceException: org.hibernate.TypeMismatchException: Provided id of the wrong type for class org.zanata.model.po.HPoTargetHeader. Expected: class java.lang.Long, got class org.hibernate.action.internal.DelayedPostInsertIdentifier
at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1608) …
```
=> fix: ensure transaction for attribution

server/zanata-frontend/src/app/styles/frontend-jsf.less, server/zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-languages.xhtml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2680
Fix height of buttons on project language page and set Disable buttons to use display: inline-flex so they always appear inline.
- JIRA link
----
=> fix(ZNTA-2680) fix height of project settings languages buttons

server/zanata-frontend/src/app/styles/frontend-jsf.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2676
Fixes:
* Colours of copytrans buttons
* Darkened background for Continue as Fuzzy buttons to improve contrast against yellow text
* Modal footer button is centered
Screenshot:
- JIRA link
----
=> fix(ZNTA-2676) colour for copytrans modal state buttons

server/zanata-frontend/src/app/editor/components/Button/index.css, server/zanata-frontend/src/app/editor/components/TransUnit/index.css
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2679
1. Error status icon picking up MT status icon styles
2. Editor buttons text when disabled should be white
- JIRA link
----
=> fix(ZNTA-2679): React Editor status icon and disabled button styles

server/zanata-frontend/src/app/containers/Languages/index.js, server/zanata-frontend/src/app/styles/antd.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2682
Fixed the page size selector and pagination components on the Languages page.
Removed the border disabled override on ant pagination, displays current selected:
- JIRA link
----
=> fix(ZNTA-2682): languages pagination

server/zanata-frontend/src/app/containers/Admin/index.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2703
Change hover text colour to white for items on admin homepage
- JIRA link
----
=> fix(ZNTA-2703) hover colour for link panels on admin homepage

server/zanata-frontend/src/app/containers/Explore/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2705
reduce spacing between explore page search and content
Fix:
- JIRA link
----
=> fix(ZNTA-2705) reduce spacing between explore page search and content

server/zanata-frontend/src/app/components/RejectionsForm/index.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2704
alignment of save and delete buttons on review criteria admin page
fix:
- JIRA link
----
=> fix(ZNTA-2704) alignment of save and delete buttons on review criteria admin page

server/zanata-frontend/src/app/styles/antd.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2707
The pop up toast notifications in frontend now use the status colours for zanata instead of the antd defaults.
- JIRA link
----
=> fix(ZNTA-2707) use zanata colours for antd notification icons

server/zanata-frontend/src/app/editor/containers/NavHeader.js, server/zanata-frontend/src/app/editor/containers/Root/index.css
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2706
alignment of editor nav arrows
text size for project name in editor nav
remove extra padding form bottom of nav dropdown
fix:
- JIRA link
----
=> fix(ZNTA-2706) alignment of react editor header nav arrows

server/zanata-frontend/src/app/styles/antd.less
JIRA issue URL: http://zanata.atlassian.net/browse/ZNTA-2701
Hover, focus, active border colour for language pagination
Use zanata colour scheme
Fix:
- JIRA link
----
=> fix(ZNTA-2701) hover, focus, active border colour for language pagination

server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap, server/zanata-frontend/src/app/components/MTMerge/MTMergeOptions.tsx
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2702
add margin between MT Merge modal alerts
update snapshot tests
fix:
- JIRA link
----
=> fix(ZNTA-2702) add margin between MT Merge modal alerts

server/zanata-frontend/src/app/containers/Glossary/ViewHeader.js, server/zanata-frontend/src/app/containers/Glossary/index.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2699
fix positioning of project glossary title and read only icon
- JIRA link
----
=> fix(ZNTA-2699) fix positioning of project glossary title

server/zanata-frontend/src/app/styles/frontend-jsf.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2698
In the old jsf modals the buttons are not center aligned. This has been fixed by removing the value set for height of the footer in the jsf.less file.
- JIRA link
----
=> fix(ZNTA-2698) vertically align modal footer content

server/zanata-frontend/src/app/reducers/version-reducer.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2708
MT Merge process status errors should not auto-dismiss themselves.
1. Go to a project version
2. Select Machine Translation from the menu
3. Select an unavailable locale (eg am)
4. Press Merge
- JIRA link
----
=> fix(ZNTA-2708): specify duration for mtmerge process status notifications

server/zanata-frontend/src/app/styles/frontend-jsf.less, server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/projects.xhtml
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2697
The dashboard project lists were not center aligned because of some frontend css.
Added a class that removes unnecessary padding from these lists.
Fix:
- JIRA link
----
=> fix(ZNTA-2697) remove extra spacing from dashboard lists

server/zanata-frontend/pom.xml
This should make it easier to install yarn without running a full build.
For example:
```
mvn -pl :zanata-frontend com.github.eirslett:frontend-maven-plugin:install-node-and-yarn
```
- JIRA link
----
=> Change node/yarn version properties

server/functional-test/src/main/java/org/zanata/page/administration/ManageUserPage.java, server/zanata-frontend/src/app/editor/components/Pager/Pager.test.tsx, server/zanata-frontend/src/app/editor/components/Pager/index.js, server/zanata-frontend/src/app/editor/containers/ControlsHeader.js, server/zanata-frontend/src/app/styles/frontend-jsf.less
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2711
alignment of admin TM list items - make sure all right aligned
fix: 
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2714
Alignment of pagination numbers in editor.
The alignment is not consistent across different operating systems (macOS and Fedora) so I have center aligned it as best I can across both systems, with Fedora taking priority.
- JIRA link
---- …
=> fix(ZNTA-2711)(ZNTA-2714)  alignment of admin TM list items and editor pagination

server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeModal.js, server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeProjectSources.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2727
Issue appears to be caused by the lack of null checking in a deprecated React lifestyle method componentWillReceiveProps.
Refactored the unsafe operation and the TMMergeModal to use the componentDidUpdate lifestyle method instead.
Issue affected the TM and MT merge modals when there exists a project without any versions.
Shouldn't experience any console errors when opening and running the TM and MT merge modals now.
- JIRA link
See [Zanata Development Guidelines](https://github.com/zanata/zanata-platform/wiki/Development-Guideli …
=> fix(ZNTA-2727): TM Merge modal version filter check, remove componentWillReceiveProps

server/zanata-frontend/src/app/components/LocaleSelect/index.tsx, server/zanata-frontend/src/app/components/MTMerge/MTMergeOptions.tsx, server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeModal.js
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2580
Extract the searchable and sorted by ID locale select implementation from MT Merge modal, use as component in both MT and TM merge modals.
- JIRA link
----
=> feat(ZNTA-2580): sorted and searchable locale select for TM Merge

server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java, server/services/src/main/java/org/zanata/service/impl/TranslationServiceImpl.java
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2730
Use EntityManager:clear after processing a batch of textflowtargets in a transaction, to prevent progressively increasing memory usage.
- JIRA link
----
=> fix(ZNTA-2730): clear hibernate cache before and after batch

README.md
*This changes the readme so that the internal link to the documentation on Docker usage works.*
=> README: Fix link to Docker docs

Jenkinsfile
Apparently the default for Node is 1.76GB on 64 bit machines: https://stackoverflow.com/questions/47381275/why-does-node-js-have-an-1-76-gb-memory-limit?rq=1
This change increases it to 4GB when built via Jenkins.
- JIRA link
----
=> Increase JS heap
