server/zanata-war/src/main/java/org/zanata/webtrans/client/ui/NotificationItem.ui.xml
server/zanata-war/src/main/java/org/zanata/webtrans/client/view/AppView.java
server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/groups.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/projects.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/settings.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/people-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/person-permissions-modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-languages.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/versions-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/settings-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/groups-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab-languages.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml
server/zanata-war/src/main/webapp/admin/rolemanager.xhtml
server/zanata-war/src/main/webapp/admin/rolerules.xhtml
server/zanata-war/src/main/webapp/admin/usermanager.xhtml
server/zanata-war/src/main/webapp/dashboard/home.xhtml
server/zanata-war/src/main/webapp/iteration/view.xhtml
server/zanata-war/src/main/webapp/language/home.xhtml
server/zanata-war/src/main/webapp/language/language.xhtml
server/zanata-war/src/main/webapp/resources/zanata/global-messages.xhtml
server/zanata-war/src/main/webapp/resources/zanata/maintainers-tab.xhtml
server/zanata-war/src/main/webapp/resources/zanata/multi-file-upload.xhtml
server/zanata-war/src/main/webapp/tm/home.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1447*
Update icon class for cancel and plus. To fix broken functional-test
- Code quality
- Testing …

fix(icons): Update icon css for 'cancel' and 'plus'

---

server/zanata-frontend/src/frontend/webpack.legacy.config.js

*Add comment for legacy build in Zanata-frontend*
- Code quality
- Testing
----
---
This …

docs(zanata-frontend): Add comments for legacy build in Zanata frontend

---

client/docs/commands/pull.md
client/docs/commands/push.md

Happened to discover some out of date info in the docs.
- Code quality
- Testing
----
--- …

update client docs

---

server/docker/Dockerfile
server/docker/common
server/docker/conf/standalone.xml
server/docker/rundb.sh
server/docker/rundev.sh

use docker network instead of linking so that we can have two way communication for containers
- Code quality
- Testing
---
_This template can be updated in …

use docker user defined network instead of linking

---

server/functional-test/src/main/java/org/zanata/util/TestEventForScreenshotListener.java
server/pom.xml
server/zanata-war/pom.xml
server/zanata-war/src/main/java/org/zanata/webtrans/client/EventProcessor.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/AppPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/AttentionKeyShortcutPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/DocumentListPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/ForceReviewCommentPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/GlossaryPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/KeyShortcutPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/SearchResultsPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/SourceContentsPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/TransMemoryMergePresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/TransUnitReplaceInfo.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/TransUnitsTablePresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/TranslationPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/UserConfigHolder.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/presenter/WorkspaceUsersPresenter.java
server/zanata-war/src/main/java/org/zanata/webtrans/client/rpc/SeamDispatchAsync.java

http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_0
- Java 8 syntax
- Faster compilation
- JS runtime performance optimisations (JDK emulation)
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technolog …

Update GWT, Guava and RichFaces

---

server/docker/conf/standalone.xml
server/functional-test/src/test/resources/conf/standalone.xml
server/functional-test/src/test/resources/conf/standalone_wildfly.xml
server/zanata-war/src/test/resources/arquillian/standalone-arquillian-wildfly.xml
server/zanata-war/src/test/resources/arquillian/standalone-arquillian.xml

JIRA issue URL: _[https://zanata.atlassian.net/browse/ZNTA-1255]_
This will enable debug logging for and CDI related errors. To reproduce a "ERROR log: WELD-000019 Error destroying an instance org.zanata.security.ZanataIdentity" error log, sign in, visit settings page, then log out. You should see detailed stacktrace logged _in the file_ (console log has threshold of INFO)
- Code quality
- Code is in …

ZNTA-1255 - enable debug logging for Weld msg with 'Catching'

---

client/zanata-client-commands/src/test/java/org/zanata/client/TestProjectGenerator.java
client/zanata-client-commands/src/test/java/org/zanata/client/TestUtils.java
client/zanata-client-commands/src/test/java/org/zanata/client/config/ConfigUtilTest.java
client/zanata-maven-plugin/src/test/java/org/zanata/maven/ZanataMojoTest.java
client/zanata-rest-client/src/test/java/org/zanata/rest/client/FileResourceClientTest.java

Another fix for #2 (should have been included in #11).
- Code quality
- Testing
---
_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_
--- …

chore: handle build directory paths containing "@"

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/PushPullCommand.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PullCommand.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PullOptions.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/PullOptionsImpl.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/AbstractPullMojo.java

JIRA issue URL: _[https://zanata.atlassian.net/browse/ZNTA-1427]_
- added a new CLI option --cache-dir to customize pull cache file location (.zanata-cache folder)
- added a new maven option -Dzanata.cacheDir to customize pull cache file location
- Code quality
- Testing …

ZNTA-1427 - add option to customize cache location

---

server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java
server/functional-test/src/test/java/org/zanata/feature/testharness/ZanataTestCase.java

- Code quality
- Testing
---
_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_
---
This change is [<img …

Allow WebDriver to be stopped and started (more isolation)

---

server/zanata-test-war/pom.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1472
maven site plugin failed on `zanata-test-war`. But we do not need to run site on zanata-test-war anyway.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new …

ZNTA-1472: maven site plugin should skip zanata-test-war

---

server/zanata-war/src/main/java/org/zanata/servlet/MDCInsertingServletFilter.java

- Code quality
- Testing
---
_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_
---
This change is [<img …

docs: add links explaining MDC

---

docs/user-guide/projects/project-types.md

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1451*
- Code quality
- Testing
----
*This …

refactor(docs): Reference raw file types to single url

---

client/pom.xml
common/pom.xml
parent/pom.xml
server/functional-test/pom.xml
server/pom.xml
server/zanata-test-war/pom.xml
server/zanata-war/pom.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1474
Variable substitution does not work well with release-plugin.
${project.version} or "real" version works, while
${zanata.api.version} does not
Also set javadoc and site skip for functional-tests and zanata-test-war, so they won't interfere the release process.
- Code quality
- Testing …

ZNTA-1474: release plugin does not play nice with variable substitution

---

api/zanata-common-api/pom.xml
parent/pom.xml
server/functional-test/pom.xml
server/pom.xml
server/zanata-model/pom.xml
server/zanata-war/pom.xml

- Code quality
- Testing
----
---
This change is [<img …

Update commons and groovy libraries

---

server/functional-test/src/test/java/org/zanata/feature/account/InactiveUserLoginTest.java
server/zanata-frontend/src/frontend/app/containers/App.js
server/zanata-war/src/main/webapp/WEB-INF/template/template_nobanner.xhtml
server/zanata-war/src/main/webapp/dashboard/home.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-47
Fix the consistency of page titles, to "Zanata: page_title"
- Code quality
- Testing
----
*This …

fix(ZNTA-47): Consistency of page titles

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/push/PushCommand.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/push/RawPushCommand.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1464
Ensure push type is one of the valid options
- Code quality
- Testing
---- …

fix(ZNTA-1464): Handle invalid push type

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/ConfigurableOptionsImpl.java
client/zanata-maven-plugin/pom.xml
client/zanata-maven-plugin/src/main/java/org/zanata/maven/AbstractPullMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/AbstractPushMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/AbstractPushPullMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/ConfigurableMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/ConfigurableProjectMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/GetStatisticsMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/GlossaryDeleteMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/GlossaryMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/GlossaryPullMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/GlossaryPushMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/InitMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/ListLocalMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/ListRemoteMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/PullModuleMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/PullSimpleMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/PushModuleMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/PushSimpleMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/PutProjectMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/PutUserMojo.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/PutVersionMojo.java

NB You can generate a file listing all options with:
mvn -pl . org.zanata:zanata-maven-plugin:4.0.0-SNAPSHOT:help -Ddetail > zanata-maven-options.txt
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and …

Switch Maven plugin to use annotations

---

api/zanata-common-api/pom.xml
parent/pom.xml
server/pom.xml

Fix the zanata-assets version, 
Also match the versions of hibernate-validator, jboss-logging
- Code quality
- Testing
---- …

fix(version): fix hibernate-validator, jboss-logging and zanata-assets version

---

server/pom.xml

Update assets to 10.1, which has META-INF/resources
- Code quality
- Testing
----
---
This …

chore(version): Update Zanata dependencies

---

server/zanata-frontend/pom.xml
server/zanata-frontend/src/editor/app/webpack.config.js
server/zanata-frontend/src/editor/app/webpack.dev.config.js
server/zanata-frontend/src/editor/app/webpack.draft.config.js
server/zanata-frontend/src/editor/app/webpack.prod.config.js
server/zanata-frontend/src/editor/package.json
server/zanata-frontend/src/frontend/package.json
server/zanata-frontend/src/frontend/webpack.config.js
server/zanata-frontend/src/frontend/webpack.dev.config.js
server/zanata-frontend/src/frontend/webpack.draft.config.js
server/zanata-frontend/src/frontend/webpack.draftlegacy.config.js
server/zanata-frontend/src/frontend/webpack.prod.config.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1394
zanata-frontend does a fast draft build by default. Use -Doptimise to do an optimised production build.
Opening for review since the changes so far are separate from the remaining changes.
- Code quality
- Testing …

Draft frontend builds (ZNTA-1394)

---

server/zanata-frontend/src/frontend/app/components/Nav/index.jsx

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1502*
- Code quality
- Testing
----
*This …

fix(nav): highlight selected page

---

server/zanata-war/src/main/java/org/zanata/action/HomePage.java

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1501*
- Code quality
- Testing
----
*This …

fix(home page content): allow empty home page content

---

server/zanata-war/src/main/webapp/resources/zanata/list-filter.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-509*
- Code quality
- Testing
----
*This …

fix(search/filter): update cancel button location for filter list

---

server/zanata-war/src/main/webapp/admin/usermanager.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1494*
- Code quality
- Testing
----
*This …

fix(user page): update design for search in the bottom of the page

---

build-tools/pom.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1509
Add scm section for maven-release-plugin
- Code quality
- Testing
---- …

fix(ZNTA-1509): add scm tag for maven-release-plugin

---

api/pom.xml

Zanata 4.0 is a good opportunity to bump the JVM requirements for code which uses zanata-common-api. We were only using Java 1.7 for Enunciate 1.x compatibility anyway.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#n …

Upgrade api to Java 1.8

---

server/docker/README.md

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1462
Adds a few instructions for getting docker working, in case the developer is unfamiliar with docker.
- Migrated from https://github.com/zanata/zanata-server/pull/1304
- This was previously reviewed except for the most recent commit, see https://reviewable.io/reviews/zanata/zanata-server/1304
- I have assigned everyone who commented in the earlier review, feel free to remove yourself.
Use the …

docs(docker): add docker setup instructions ZNTA-1462

---

build-tools/pom.xml
parent/pom.xml

Provide missing parts of pom.xml  for deploy build-tools
```
[ERROR]
[ERROR] Nexus Staging Rules Failure Report
[ERROR] ==================================
[ERROR]
[ERROR] Repository "orgzanata-1155" failures
[ERROR]   Rule "signature-staging" failures
[ERROR]     * Missing Signature: '/org/zanata/build-tools/4.0.0-alpha-2/build-tools-4.0.0-alpha-2.pom.asc' does not exist for 'build-tools-4.0.0-alpha-2.pom'.
[ERROR]     * Missing Signature: '/org/zanata/build-tools/4.0.0-alpha-2/build-tools-4.0.0-alpha-2.jar.asc' does not exist for 'build-tools-4.0.0-alpha-2.jar'.
[ERROR]   Rule "pom-staging" failures
[ERROR]     * Invalid POM: /org/zanata/build-tools/4.0.0-alpha-2/build-tools-4.0.0-alpha-2.pom: Project description missing, Project URL missing, License informat
ion missing, SCM URL …
```

Pom for deploy

---

server/zanata-frontend/src/frontend/app/containers/Root.js
server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java
server/zanata-war/src/main/webapp/project/project.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1513*
- Code quality
- Testing
----
*This …

fix(project glossary): update glossary project path

---

docs/user-guide/account/account-settings.md
docs/user-guide/client/client.md
docs/user-guide/documents/download-translated-documents.md
docs/user-guide/documents/upload-documents.md
docs/user-guide/glossary/delete-glossaries.md
docs/user-guide/glossary/upload-glossaries.md
docs/user-guide/project-maintainer-guide.md
docs/user-guide/projects/create-project.md
docs/user-guide/projects/gettext-example.md
docs/user-guide/projects/import-projects.md
docs/user-guide/projects/podir-example.md
docs/user-guide/projects/project-types.md
docs/user-guide/versions/create-version.md

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1516*
- Code quality
- Testing
----
*This …

doc(zanata-client): Update link to zanata-cli documentation

---

server/functional-test/src/test/java/org/zanata/feature/glossary/GlossaryAdminTest.java
server/zanata-war/src/main/java/org/zanata/ui/UIInputContainer.java
server/zanata-war/src/main/resources/messages.properties

* Fix various minor typos found while translating Zanata into Ukrainian
- Code quality
- Testing
---- …

Fix various minor typos

---

server/zanata-war/src/main/webapp/resources/zanata/confirm-modal.xhtml
server/zanata-war/src/main/webapp/tm/home.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1517*
- Code quality
- Testing
----
*This …

fix(modal): align cancel and ok button in modal popup

---

server/gwt-editor/src/etc/FillInTranslationGap.groovy
server/gwt-editor/zanata.xml
server/pom.xml
server/zanata-war/pom.xml
server/zanata.xml

some changes needed during investigating https://zanata.atlassian.net/browse/ZNTA-1491
[skip ci]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/44)

fix gwt i18n process

---

server/docker/Dockerfile
server/zanata-war/pom.xml
server/zanata-war/src/main/webapp-jboss/WEB-INF/jboss-deployment-structure.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1507
- include sun.jdk module in jboss deployment structure
- upgrade javamelody to 1.62.0
- add the missing class path to sun.jdk module file for dev docker image
- Code quality
- Testing …

ZNTA-1507 - enable javamelody heap dump

---

server/zanata-frontend/pom.xml
server/zanata-frontend/src/editor/.npmrc
server/zanata-frontend/src/editor/makefile
server/zanata-frontend/src/frontend/.npmrc
server/zanata-frontend/src/frontend/README.md
server/zanata-frontend/src/frontend/makefile
server/zanata-frontend/src/frontend/package.json

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1355
Script execution on third-party modules is suppressed, but allowed for all our own scripts. User `.npmrc` settings should no longer be able to interfere with our frontend build.
- Code quality
- Testing …

Limit npm script execution (ZNTA-1355)

---

server/zanata-frontend/src/editor/app/index.js
server/zanata-frontend/src/editor/app/middlewares/title-update.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-58
Show project name, version and locale name in the browser title for the React editor, using the same layout as in the GWT editor.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Dev …

Show workspace info in the browser title (ZNTA-58)

---

server/zanata-war/src/main/webapp/WEB-INF/layout/project/edit_form.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-504*
- Code quality
- Testing
----
*This …

fix(project description): validate maxlength for project description

---

server/zanata-war/src/main/java/org/zanata/util/FacesNavigationUtil.java

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1348*
Should no longer redirect to http://localhost:8080/http://localhost:8080/webtrans/translate?project=test after login from GWT editor.
- Code quality
- Testing …

fix(redirection): update editor redirection url

---

server/zanata-frontend/src/frontend/app/actions/glossary.js
server/zanata-frontend/src/frontend/app/containers/Glossary/ViewHeader.js
server/zanata-frontend/src/frontend/app/containers/Glossary/index.js
server/zanata-frontend/src/frontend/app/reducers/glossary.js
server/zanata-frontend/src/frontend/app/utils/UrlHelper.js
server/zanata-frontend/src/frontend/index.html

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1530*
- Code quality
- Testing
----
*This …

fix(project glossary): use project name for page info

---

server/gwt-editor/src/main/java/org/zanata/webtrans/Application.gwt.xml

Enable soft/runtime permutations for much faster GWT builds.
See https://github.com/gwtproject/old_google_code_wiki/blob/master/SoftPermutations.wiki.md
and http://stackoverflow.com/questions/35228019/using-collapse-all-properties-in-production
- Code quality
- Testing …

chore: use soft (runtime) permutations for GWT

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/AppView.java
server/zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml
server/zanata-war/src/main/webapp/resources/zanata/activity-entry.xhtml
server/zanata-war/src/main/webapp/resources/zanata/multi-file-upload.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-134*
- Code quality
- Testing
----
*This …

fix(doc name): handle long doc name

---

server/zanata-frontend/src/frontend/app/containers/Glossary/Entry.js
server/zanata-frontend/src/frontend/app/utils/DateHelper.js
server/zanata-frontend/src/frontend/app/utils/GlossaryHelper.js
server/zanata-frontend/src/frontend/npm-shrinkwrap.json
server/zanata-frontend/src/frontend/package.json

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1540*
- Code quality
- Testing
----
*This …

fix(glossary date): invalid date format

---

server/zanata-war/src/main/java/org/zanata/util/UrlUtil.java
server/zanata-war/src/test/java/org/zanata/util/UrlUtilTest.java

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1545*
- Code quality
- Testing
----
*This …

fix(glossary url): update glossary url from gwt

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/zip_download_progress_modal.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1536*
- Code quality
- Testing
----
*This …

fix(download zip modal): cancel and download button layout

---

server/zanata-war/src/main/webapp/iteration/view.xhtml
server/zanata-war/src/main/webapp/project/project.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1546*
- Code quality
- Testing
----
*This …

fix(projects link): projects link in project and version page

---

server/zanata-war/src/main/webapp/version-group/version_group.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1551*
- Code quality
- Testing
----
*This …

fix(groups link): link to dashboard groups from group page

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TransUnitDetailsPanel.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/SourceContentsView.java

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1556*
- Code quality
- Testing
----
*This …

fix(tu details): display/hide tu details on user settings in editor

---

server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/settings.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1561*
- Code quality
- Testing
----
*This …

fix(join language link): url to join language from dashboard

---

server/zanata-war/src/main/webapp/WEB-INF/layout/admin/contact_admin_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/admin/contact_admin_modal_anonymous.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/copy_trans_inline_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/delete_confirmation_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/contact_coordinator_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/contact_members_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/decline_request_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/request_join_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/search_user_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/request_join_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/merge_trans_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/upload_translation_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/zip_download_progress_modal.xhtml
server/zanata-war/src/main/webapp/resources/zanata/confirm-modal.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1558*
- Code quality
- Testing
----
*This …

fix(modal): align footer button in modal

---

server/zanata-frontend/src/frontend/app/actions/glossary.js

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1544*
- Code quality
- Testing
----
*This …

fix(glossary): update language count after update term

---

server/zanata-frontend/src/frontend/app/components/Nav/index.jsx
server/zanata-frontend/src/frontend/app/legacy.js

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1559*
- Code quality
- Testing
----
*This …

fix(nav): highlight dashboard and settings for sidebar nav

---

server/pom.xml
server/zanata-war/src/main/webapp/project/project.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1560*
- Code quality
- Testing
----
*This …

fix(project page): url align for repo info

---

server/functional-test/src/main/java/org/zanata/page/account/RegisterPage.java
server/functional-test/src/main/java/org/zanata/workflow/RegisterWorkFlow.java
server/functional-test/src/test/java/org/zanata/feature/account/RegisterTest.java
server/zanata-war/src/main/java/org/zanata/action/RegisterAction.java
server/zanata-war/src/main/webapp/account/google_password_reset_request.xhtml
server/zanata-war/src/main/webapp/account/login.xhtml
server/zanata-war/src/main/webapp/account/password_reset.xhtml
server/zanata-war/src/main/webapp/account/password_reset_request.xhtml
server/zanata-war/src/main/webapp/account/register.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1537*
- Code quality
- Testing
----
*This …

fix(redirect after sign-up): redirect to login after sign up

---

server/functional-test/src/test/java/org/zanata/feature/versionGroup/VersionGroupTest.java
server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/settings-tab.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1550*
- Code quality
- Testing
----
*This …

fix(version group): update project search to use name

---

server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/TransMemoryQuery.java
server/pom.xml
server/zanata-war/pom.xml
server/zanata-war/src/main/java/org/zanata/dao/TextFlowTargetDAO.java
server/zanata-war/src/main/java/org/zanata/email/ActivationEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/ContactAdminEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/DeclineLanguageRequestEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/EmailBuilder.java
server/zanata-war/src/main/java/org/zanata/email/EmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/EmailValidationEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/LanguageTeamPermissionChangeEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/PasswordResetEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/RequestToJoinLanguageEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/RequestToJoinVersionGroupEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/email/UsernameChangedEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/rest/ZanataRestSecurityInterceptor.java
server/zanata-war/src/main/java/org/zanata/rest/editor/service/SuggestionsService.java
server/zanata-war/src/main/java/org/zanata/service/TranslationFinder.java
server/zanata-war/src/main/java/org/zanata/service/TranslationMemoryService.java
server/zanata-war/src/main/java/org/zanata/service/impl/CopyTransWorkFactory.java
server/zanata-war/src/main/java/org/zanata/service/impl/TransMemoryMergeServiceImpl.java
server/zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java
server/zanata-war/src/test/java/org/zanata/service/impl/TransMemoryMergeServiceImplTest.java
server/zanata-war/src/test/java/org/zanata/service/impl/TranslationFinderTest.java
server/zanata-war/src/test/java/org/zanata/service/impl/TranslationMemoryServiceImplTest.java

https://zanata.atlassian.net/browse/ZNTA-1572
Replace TotallyLazy with Javaslang and remove the non-Central Maven repository repo.bodar.com.
Among other things, Javaslang is better documented and doesn't require using the bodar Maven repo.
http://www.javaslang.io/
- Code quality
- Testing …

chore(ZNTA-1572) use javaslang, not totallylazy

---

server/zanata-war/src/main/java/org/zanata/action/ServerConfigurationBean.java

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1563*
- Code quality
- Testing
----
*This …

fix(log email): email list validation for admin log

---

server/zanata-frontend/src/frontend/app/containers/Glossary/DeleteAllEntriesModal.jsx
server/zanata-frontend/src/frontend/app/containers/Glossary/DeleteEntryModal.jsx

fix(glossary): align button for delete entry

---

server/zanata-war/src/main/webapp/iteration/view.xhtml
server/zanata-war/src/main/webapp/resources/zanata/multi-file-upload.xhtml

- Code quality
- Testing
----
--- …

Fix link to custom parameters help

---

server/zanata-war/src/main/java/org/zanata/action/ServerConfigurationBean.java

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1564*
- Code quality
- Testing
----
*This …

fix(int validation): int validation for max concurrent client config

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-3
Hides the "Download all as zip" option when there is nothing to download
- Code quality
- Testing …

fix(ZNTA-3): Hide download zip option when version is empty

---

server/zanata-war/src/main/java/org/zanata/action/VersionGroupHome.java
server/zanata-war/src/main/resources/messages.properties

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-100
Show notification on group settings updated
- Code quality
- Testing
---- …

fix(ZNTA-100): Show notification on group settings update

---

server/functional-test/pom.xml
server/zanata-test-war/pom.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1571
Definitions of `allow.deploy.skip` is missing in zanata-test-war and functional-test.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-d …

ZNTA-1571: allow.deploy.skip for zanata-test-war and functional-test

---

server/zanata-frontend/src/frontend/app/containers/Languages/NewLanguageModal.js

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1593*
- Code quality
- Testing
----
*This …

fix(language): reset fields after add new language

---

server/zanata-war/src/main/java/org/zanata/rest/service/GlossaryService.java

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1594*
- Code quality
- Testing
----
*This …

fix(glossary): return deleted glossary entry count

---

docs/release-notes.md

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1584
Add the Migration Guide to release note.
- Code quality
- Testing
---- …

Znta 1584 migration guide

---

server/zanata-model/src/main/java/org/zanata/model/HApplicationConfiguration.java
server/zanata-model/src/main/java/org/zanata/model/HPersonEmailValidationKey.java
server/zanata-model/src/main/java/org/zanata/model/validator/AcceptedEmailDomainsForNewAccount.java
server/zanata-model/src/main/java/org/zanata/model/validator/EmailDomain.java
server/zanata-model/src/main/java/org/zanata/model/validator/EmailDomainValidator.java
server/zanata-model/src/test/java/org/zanata/model/validator/EmailDomainValidatorTest.java
server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
server/zanata-war/src/main/java/org/zanata/action/AbstractProfileAction.java
server/zanata-war/src/main/java/org/zanata/action/HasUserDetail.java
server/zanata-war/src/main/java/org/zanata/action/InactiveAccountAction.java
server/zanata-war/src/main/java/org/zanata/action/NewProfileAction.java
server/zanata-war/src/main/java/org/zanata/action/RegisterAction.java
server/zanata-war/src/main/java/org/zanata/action/ServerConfigurationBean.java
server/zanata-war/src/main/java/org/zanata/action/UserSettingsAction.java
server/zanata-war/src/main/java/org/zanata/action/validator/DomainList.java
server/zanata-war/src/main/java/org/zanata/action/validator/DomainListValidator.java
server/zanata-war/src/main/java/org/zanata/config/DatabaseBackedConfig.java
server/zanata-war/src/main/resources/ValidationMessages.properties
server/zanata-war/src/main/resources/messages.properties
server/zanata-war/src/main/webapp/admin/server_configuration.xhtml
server/zanata-war/src/test/java/org/zanata/action/validator/DomainListValidatorTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1567
- Code quality
- Testing
---- …

ZNTA-1567 limit email for registration

---

server/zanata-war/src/main/webapp/resources/zanata/multi-file-upload.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1614*
- Code quality
- Testing
----
*This …

fix :  cancel and upload doc button align in modal

---

server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
server/zanata-war/src/main/java/org/zanata/log4j/ZanataSMTPAppender.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1615
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/117)

ZNTA-1615 - fix email logging start up error

---

server/zanata-frontend/src/frontend/app/containers/Glossary/Entry.js

https://zanata.atlassian.net/browse/ZNTA-1578
- Code quality
- Testing
----
*This template can be updated …

fix(glossary): button alignment for each entry

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/OptionsUtil.java
client/zanata-client-commands/src/test/java/org/zanata/client/commands/OptionsUtilTest.java
client/zanata-rest-client/src/main/java/org/zanata/rest/client/RestClientFactory.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1619
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/119)

refactor to make zanata-client-command more customizable

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/resources/EnumMessages.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/resources/UiMessages.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TMMergeForm.ui.xml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-468*
*Added details to CopyTrans for Approved*
Related to *[https://github.com/zanata/zanata-assets/pull/12]* - ie. approved label styling
- Code quality
- Testing …

WIP: add approved label to copytrans

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/zip_download_progress_modal.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1624*
- Code quality
- Testing
----
*This …

fixed : ZNTA-1624 download all modal buttons alignment

---

server/zanata-war/pom.xml

https://zanata.atlassian.net/browse/ZNTA-1628
- Code quality
- Testing …

chore(explode profile): update profile to use root.war

---

api/pom.xml
api/zanata-common-api/pom.xml
build-tools/pom.xml
client/pom.xml
client/stub-server/pom.xml
client/zanata-cli/pom.xml
client/zanata-client-commands/pom.xml
client/zanata-maven-plugin/pom.xml
client/zanata-rest-client/pom.xml
common/pom.xml
common/zanata-adapter-glossary/pom.xml
common/zanata-adapter-po/pom.xml
common/zanata-adapter-properties/pom.xml
common/zanata-adapter-xliff/pom.xml
common/zanata-common-util/pom.xml
parent/pom.xml
pom.xml
server/functional-test/pom.xml
server/gwt-editor/pom.xml
server/pom.xml
server/security-common/pom.xml
server/zanata-frontend/pom.xml
server/zanata-liquibase/pom.xml
server/zanata-model/pom.xml
server/zanata-test-war/pom.xml
server/zanata-war/pom.xml

chore(revert version): revert development version to 4.1.0-SNAPSHOT

---

server/pom.xml

*Changed assets to 10.2-SNAPSHOT*
- Code quality
- Testing
---- …

chore: changed assets version to 10.2-SNAPSHOT

---

server/zanata-frontend/src/frontend/app/containers/Glossary/Entry.js

https://zanata.atlassian.net/browse/ZNTA-1541
- Code quality
- Testing …

fix(glossary): update and cancel button display in glossary page

---

server/zanata-war/src/main/java/org/zanata/dao/AccountDAO.java
server/zanata-war/src/main/java/org/zanata/dao/ProjectDAO.java

https://zanata.atlassian.net/browse/ZNTA-1629
- Code quality
- Testing …

fix(search): ignore case search for user and project

---

README.md

*Notes added to README for build process on OSX/macOS since there is an issue pointing to the correct JAVA_HOME directory*
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technolo …

chore: update README to include notes on Mac build process

---

server/zanata-frontend/src/frontend/app/components/Nav/index.jsx
server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
server/zanata-war/src/main/java/org/zanata/action/ActivateAction.java
server/zanata-war/src/main/java/org/zanata/action/AdminCreateUserAction.java
server/zanata-war/src/main/java/org/zanata/action/RegisterAction.java
server/zanata-war/src/main/java/org/zanata/action/UserAction.java
server/zanata-war/src/main/java/org/zanata/config/AllowPublicRegistration.java
server/zanata-war/src/main/java/org/zanata/dao/AccountDAO.java
server/zanata-war/src/main/java/org/zanata/email/ActivationEmailStrategy.java
server/zanata-war/src/main/java/org/zanata/seam/security/IdentityManager.java
server/zanata-war/src/main/java/org/zanata/service/EmailService.java
server/zanata-war/src/main/java/org/zanata/service/UserAccountService.java
server/zanata-war/src/main/java/org/zanata/service/impl/EmailServiceImpl.java
server/zanata-war/src/main/java/org/zanata/service/impl/UserAccountServiceImpl.java
server/zanata-war/src/main/java/org/zanata/util/UrlUtil.java
server/zanata-war/src/main/resources/messages.properties
server/zanata-war/src/main/resources/org/zanata/email/templates/activation.vm
server/zanata-war/src/main/webapp/WEB-INF/faces-config.xml
server/zanata-war/src/main/webapp/WEB-INF/template/template.xhtml
server/zanata-war/src/main/webapp/account/activate.xhtml
server/zanata-war/src/main/webapp/account/login.xhtml
server/zanata-war/src/main/webapp/account/register.xhtml
server/zanata-war/src/main/webapp/admin/create_user.xhtml
server/zanata-war/src/main/webapp/admin/usermanager.xhtml
server/zanata-war/src/test/java/org/zanata/action/AdminCreateUserActionTest.java
server/zanata-war/src/test/java/org/zanata/email/EmailStrategyTest.java
server/zanata-war/src/test/java/org/zanata/service/impl/UserAccountServiceImplTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1626
- Code quality
- Testing
---- …

ZNTA-1626 only admin can create users

---

server/zanata-frontend/src/frontend/index.html
server/zanata-frontend/src/frontend/webpack.draft.config.js

https://zanata.atlassian.net/browse/ZNTA-1646
- Code quality
- Testing …

chore(eslint): enable eslint check in draft mode

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/upload_translation_modal.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1644*
- Code quality
- Testing
----
*This …

fixed : ZNTA-1644 : upload translation modal button alignment

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/ReviewCommentInputWidget.ui.xml
server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1645*
*Fixed wrapping of button and text on reject translation modal in gwt editor*
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-depende …

fix: remove overrides from style.less which affect reject translation modal in gwt editor (ZNTA-1645)

---

server/zanata-frontend/src/frontend/app/containers/Explore/index.js
server/zanata-frontend/src/frontend/app/containers/Languages/index.js
server/zanata-frontend/src/frontend/app/styles/style.less
server/zanata-frontend/src/frontend/app/styles/variables.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1648
Tidy up minor bootstrap issues
1. Positioning of search box icon on Explore page
2. Add a larger border radius to buttons so they don't look so square
3. Change the styling of the + Add a new language button so it isn't so bold
Explore page changes (icon positioning)
Language page changes (button size, radius and colour) - button radius and colour applies to other primary buttons throughout Zanata frontend that use bootstrap now for better contrast on the pages
The reviewer can use this list for …

chore: fixed positioning of search button icons on explore and languages pages, changed colour and border radius of buttons (ZNTA-1646)

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1650
The weekly contribution table is not generating when you go to the calendar and change the date range.
Have made it visible by changing position to relative and also have made the hover/active/focus on the table colours more visible.
- Code quality
- Testing
- If there …

fix: fix display of contribution table on display page and improve contrast of its buttons (ZNTA-1650)

---

client/zanata-cli/src/main/java/org/zanata/client/ZanataClient.java
client/zanata-cli/src/test/java/org/zanata/client/ZanataClientTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1630
Ensure the command is known to client before attempting to display its help/usage
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-depen …

fix(ZNTA-1630): Prevent NPE when help target is incorrect

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/glossary/delete/GlossaryDeleteCommand.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/glossary/pull/GlossaryPullCommand.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/glossary/pull/GlossaryPullOptionsImpl.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/glossary/push/GlossaryPushCommand.java

Handle null project, filename or glossary id
- Code quality
- Testing
---- …

refactor(glossary): Add robustness to the glossary commands

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/FilterViewEvent.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/events/TransUnitSaveEvent.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/service/GetTransUnitActionContext.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/service/ModalNavigationStateHolder.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/service/SaveEventQueue.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/Editor.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TargetContentsView.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/TransHistoryItem.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/TransMemoryDetails.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/TransUnit.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/TransUnitUpdateInfo.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/TransUnitUpdateRequest.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/model/WorkspaceRestrictions.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/EditorFilter.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/GetTransUnitList.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/GetTransUnitListResult.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/GetTransUnitsNavigation.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/GetTransUnitsNavigationResult.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/RemoteLoggingAction.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/TransMemoryMerge.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/TransUnitUpdated.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/UpdateTransUnit.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/rpc/UpdateTransUnitResult.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/search/FilterConstraints.java
server/pom.xml
server/zanata-war/src/main/java/org/zanata/limits/RestCallLimiter.java
server/zanata-war/src/main/java/org/zanata/notification/MessageUnwrapper.java

https://github.com/google/guava/wiki/Release21
- Code quality
- Testing
----
---
This …

chore: update to Guava 21.0

---

server/zanata-frontend/src/editor/app/webpack.draft.config.js

style(eslint): enable eslint check in PR build for zanata-frontend

---

server/zanata-frontend/src/frontend/app/containers/Languages/DeleteEntry.js
server/zanata-frontend/src/frontend/app/containers/Languages/NewLanguageModal.js
server/zanata-frontend/src/frontend/app/containers/Languages/index.js
server/zanata-frontend/src/frontend/app/styles/style.less
server/zanata-frontend/src/frontend/app/styles/variables.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1653
Remove all zanata UI components from the containers/Languages/... in frontend
Also fixed vertical alignment of nav sidebar
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Developm …

ZNTA-1653-languages-containers

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutVersionCommand.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutVersionOptions.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutVersionOptionsImpl.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/PutVersionMojo.java
server/zanata-war/src/main/java/org/zanata/rest/service/ProjectVersionService.java

Enable --version-status active/readonly
- Code quality
- Testing
---- …

feat(project-version): Allow user to update version write state

---

server/gwt-editor/src/main/webapp/webtrans/Application.xhtml
server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/ImportedTMDetailPanel.js
server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/LocalProjectDetailPanel.js
server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/PlainSuggestionContents.js
server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.css
server/zanata-frontend/src/editor/app/containers/SuggestionDetailsModal/index.js
server/zanata-frontend/src/frontend/app/containers/App.js
server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1657
- Fixed layout of TM Suggestions modal so that it can handle long file names for project, version and document. 
- Added titles for icons in modal
- Made sure the modal appears in front of the zanata logo (without changes to zanata-ui).
- Added Source and Target headings
- Code quality …

ZNTA-1657-TM-suggestion-modal

---

api/zanata-common-api/src/main/java/org/zanata/rest/dto/User.java
api/zanata-common-api/src/test/java/org/zanata/rest/dto/UserTest.java
server/zanata-frontend/src/frontend/app/containers/Languages/Entry.js
server/zanata-frontend/src/frontend/app/containers/UserProfile/index.jsx
server/zanata-frontend/src/frontend/app/utils/UrlHelper.js
server/zanata-frontend/src/frontend/index.html
server/zanata-war/src/main/java/org/zanata/action/DashboardAction.java
server/zanata-war/src/main/java/org/zanata/rest/editor/service/UserService.java
server/zanata-war/src/main/webapp/admin/usermanager.xhtml
server/zanata-war/src/main/webapp/dashboard/home.xhtml
server/zanata-war/src/test/java/org/zanata/rest/editor/service/UserServiceTest.java
server/zanata-war/src/test/java/org/zanata/rest/service/ProjectVersionTest.java

https://zanata.atlassian.net/browse/ZNTA-1664
- Code quality
- Testing …

fix(dashboard,profile): add user roles in dashboard and profile page

---

api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java
client/stub-server/src/main/java/org/zanata/rest/service/MockGlossaryResource.java
server/zanata-frontend/src/frontend/app/actions/glossary.js
server/zanata-war/src/main/java/org/zanata/rest/service/GlossaryService.java

https://zanata.atlassian.net/browse/ZNTA-1667
- Code quality
- Testing …

fix(glossary): permission check for project glossary insert/delete

---

server/zanata-war/src/main/java/org/zanata/action/RoleAction.java
server/zanata-war/src/main/webapp/admin/roledetail.xhtml

https://zanata.atlassian.net/browse/ZNTA-1500
- Code quality
- Testing …

fix(manage role): returns to main page when cancel if click

---

server/functional-test/src/main/java/org/zanata/page/webtrans/EditorPage.java
server/functional-test/src/test/java/org/zanata/feature/editor/TranslationHistoryTest.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/Application.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/DocumentListTable.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TransHistoryItemLine.java
server/zanata-war/src/main/java/org/zanata/webtrans/server/rpc/GetTranslationHistoryHandler.java
server/zanata-war/src/main/java/org/zanata/webtrans/server/rpc/TransUnitTransformer.java
server/zanata-war/src/test/java/org/zanata/webtrans/server/rpc/GetTranslationHistoryHandlerTest.java

https://zanata.atlassian.net/browse/ZNTA-1418
- Code quality
- Testing …

feat(username link): link username to profile page from editor

---

server/zanata-war/src/main/java/org/zanata/action/LanguageJoinAction.java
server/zanata-war/src/main/webapp/WEB-INF/layout/language/decline_request_modal.xhtml

https://zanata.atlassian.net/browse/ZNTA-1479
- Code quality
- Testing …

fix(decline request): check field size for request-reject in lang

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutProjectCommand.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutProjectOptions.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutProjectOptionsImpl.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/PutProjectMojo.java
client/zanata-rest-client/src/main/java/org/zanata/rest/client/ProjectClient.java
server/zanata-war/src/main/java/org/zanata/rest/service/ProjectService.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1632
Client put-project now requires id only, or id, name and type for
new projects.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-depende …

fix(ZNTA-1632): Make non-essential put-project fields optional

---

server/zanata-war/src/main/java/org/zanata/servlet/KLoginServlet.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1665
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/166)

ZNTA-1665 - New user redirect to 404 when login with kinit

---

server/functional-test/src/test/java/org/zanata/feature/language/ContactLanguageTeamTest.java
server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java
server/zanata-war/src/main/java/org/zanata/action/LanguageContactCoordinatorAction.java
server/zanata-war/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java
server/zanata-war/src/main/resources/messages.properties
server/zanata-war/src/main/resources/org/zanata/email/templates/email_coordinator.vm
server/zanata-war/src/main/webapp/WEB-INF/layout/language/contact_coordinator_modal.xhtml
server/zanata-war/src/main/webapp/language/language.xhtml
server/zanata-war/src/test/java/org/zanata/email/EmailStrategyTest.java

https://zanata.atlassian.net/browse/ZNTA-1210
- Code quality
- Testing …

fix(contact admin): contact admin when there is no lang coordinator

---

api/zanata-common-api/src/main/java/org/zanata/rest/dto/Account.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutUserCommand.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutUserOptions.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutUserOptionsImpl.java
client/zanata-client-commands/src/main/resources/prompts.properties
client/zanata-client-commands/src/test/java/org/zanata/client/commands/PutUserCommandTest.java
client/zanata-client-commands/src/test/java/org/zanata/client/commands/PutUserOptionsImplTest.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/PutUserMojo.java
client/zanata-rest-client/pom.xml
client/zanata-rest-client/src/main/java/org/zanata/rest/client/AccountClient.java
client/zanata-rest-client/src/main/java/org/zanata/rest/client/ResponseStatusFilter.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1596
User only needs to specify a target username, others are optional.
Email and name are required for a new user.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelin …

fix(ZNTA-1596): Update user without having to specify all details

---

.editorconfig

http://editorconfig.org/
- Code quality
- Testing
----
--- …

style: add .editorconfig for consistent whitespace

---

.editorconfig

https://youtrack.jetbrains.com/issue/IDEA-145069#comment=27-1359692
- Code quality
- Testing
---- …

Tell IntelliJ to use 8 space continuation indents

---

server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
server/zanata-war/src/main/java/org/zanata/ZanataInit.java
server/zanata-war/src/main/java/org/zanata/log4j/ZanataHTMLLayout.java
server/zanata-war/src/test/java/org/zanata/log4j/ZanataHTMLLayoutTest.java

https://zanata.atlassian.net/browse/ZNTA-1376
- Code quality
- Testing …

fix(log): add build info in error log

---

server/docker/rundev.sh
server/zanata-frontend/src/frontend/app/styles/style.less
server/zanata-frontend/src/frontend/app/styles/variables.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1681
Added popover css for delete button on languages page.
- Code quality
- Testing
----
*This …

fix: added css for languages popover lost in merge

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/init/InitCommand.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/init/UserConfigHandler.java
client/zanata-client-commands/src/test/java/org/zanata/client/commands/init/InitCommandTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1671
The client init command no longer requires a zanata.ini file
- Code quality
- Testing
----
*This …

fix(ZNTA-1671): Ignore missing user-config

---

server/zanata-frontend/src/frontend/app/actions/languages.js
server/zanata-frontend/src/frontend/app/containers/Languages/DeleteEntry.js
server/zanata-frontend/src/frontend/app/containers/Languages/index.js
server/zanata-frontend/src/frontend/index.html

https://zanata.atlassian.net/browse/ZNTA-1686
- Code quality
- Testing …

fix(language search): reset search after delete

---

server/zanata-war/src/main/webapp/WEB-INF/layout/language/members-tab.xhtml

https://zanata.atlassian.net/browse/ZNTA-1707
- Code quality
- Testing …

fix(language): fix checkbox not appear after search

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/zip_download_progress_modal.xhtml

https://zanata.atlassian.net/browse/ZNTA-1381
- Code quality
- Testing …

fix(download): fix download zip files dialog in version page

---

server/zanata-frontend/src/frontend/app/actions/glossary.js

https://zanata.atlassian.net/browse/ZNTA-1717
- Code quality
- Testing …

fix(glossary): reset page when do glossary search

---

server/zanata-war/src/main/webapp/a/index.xhtml

https://zanata.atlassian.net/browse/ZNTA-1712
- Code quality
- Testing …

fix(sign up link): fix sign up link show/hidden in explore page

---

server/zanata-frontend/src/frontend/app/containers/UserProfile/index.jsx
server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1704
Fixed: On profile page both languages shows wihout separation. it looks like its an single language.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-tec …

fix:positioning of languages on profile page (ZNTA-1704)

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1710
Fixed loader on delete button in rows on Glossary page so that when clicked the button doesn't change size.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guideli …

ZNTA-1710 - Fix: loader on delete button

---

server/zanata-frontend/src/frontend/app/actions/languages.js

https://zanata.atlassian.net/browse/ZNTA-1706
- Code quality
- Testing …

fix(language): fix filter error in language page

---

server/zanata-war/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java
server/zanata-war/src/main/java/org/zanata/security/oauth/SecurityTokens.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1703
- Code quality
- Testing
---- …

ZNTA-1703 - eliminate error log on ZanataIdentity.preDestroy

---

docs/user-guide/projects/project-settings.md

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1726
* add missing documentation for manual webhook
[skipci]
- Code quality
- Testing
----
*This …

ZNTA-1726 add manual webhook documentation

---

server/docker/rundb.sh
server/docker/rundev.sh

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1660
Use :z in -v instead of chcon
Use realpath instead of readlink for MacOS/BSD compatibility.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technolo …

fix(ZNTA-1660): Use :z instead of chcon

---

server/docker/conf/zanata-config.cli
server/functional-test/src/test/conf/standalone_wildfly.xml
server/zanata-overlay/distros/wildfly/standalone/configuration/standalone-zanata.xml
server/zanata-war/src/test/resources/arquillian/standalone-arquillian-wildfly.xml

This should make it easier to diagnose problems which occur with Docker/rundev.sh. eg https://zanata.atlassian.net/browse/ZNTA-1255
Also disabled the org.hibernate.engine.jdbc.internal debug logging because it doesn't tell us anything useful.
- Code quality
- Testing …

Log debug to console

---

server/zanata-war/src/test/java/org/zanata/adapter/TSAdapterTest.java

Use extensions given search function for finding context/comment
- Code quality
- Testing
---- …

refactor(test): Use extensions findByType instead of searching

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1738
Fix height of link boxes for translations in GWT editor so they are not larger than the link field
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-t …

ZNTA-1738 fix: fixed height of link boxes in GWT editor 

---

common/zanata-adapter-po/src/main/java/org/zanata/adapter/po/PoWriter2.java
server/zanata-war/src/test/java/org/zanata/adapter/GettextAdapterTest.java
server/zanata-war/src/test/resources/org/zanata/adapter/test-gettext-comments.po
server/zanata-war/src/test/resources/org/zanata/adapter/test-gettext-flags.pot
server/zanata-war/src/test/resources/org/zanata/adapter/test-gettext-plurals.po
server/zanata-war/src/test/resources/org/zanata/adapter/test-gettext-reference.pot
server/zanata-war/src/test/resources/org/zanata/adapter/test-gettext-translated.po
server/zanata-war/src/test/resources/org/zanata/adapter/test-gettext-untranslated.pot

Add Gettext adapter unit test

---

docs/release-notes.md

Ref: https://zanata.atlassian.net/browse/ZNTA-1724?focusedCommentId=28206&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-28206
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-te …

Update release notes for 4.0

---

server/zanata-war/src/main/java/org/zanata/adapter/JsonAdapter.java
server/zanata-war/src/test/java/org/zanata/adapter/JsonAdapterTest.java
server/zanata-war/src/test/resources/org/zanata/adapter/test-json-duplicatecontent.json
server/zanata-war/src/test/resources/org/zanata/adapter/test-json-duplicateentries.json
server/zanata-war/src/test/resources/org/zanata/adapter/test-json-duplicateids.json
server/zanata-war/src/test/resources/org/zanata/adapter/test-json-untranslated.json

~~Fixed: The contentHash method allowed the content of two different key value pairs to be considered equal.~~
Update unit tests, add TODO for fixing id generation
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#ne …

test(adapter): Add JSONAdapter unit tests

---

server/docker/conf/zanata-config.cli
server/functional-test/src/test/conf/standalone.xml
server/zanata-war/src/main/java/org/zanata/rest/service/VirusScanner.java
server/zanata-war/src/test/java/org/zanata/file/SourceDocumentUploadTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1745
Remove clamdscan warnings in dev and functional test
- Code quality
- Testing
----
*This …

fix(ZNTA-1745): Fix VirusScan warnings

---

server/zanata-war/src/main/java/org/zanata/adapter/AdapterUtils.java
server/zanata-war/src/main/java/org/zanata/adapter/FileFormatAdapter.java
server/zanata-war/src/main/java/org/zanata/adapter/GenericPropertiesAdapter.java
server/zanata-war/src/main/java/org/zanata/adapter/GettextAdapter.java
server/zanata-war/src/main/java/org/zanata/adapter/PropertiesAdapter.java
server/zanata-war/src/test/java/org/zanata/adapter/PropertiesAbstractTest.java
server/zanata-war/src/test/java/org/zanata/adapter/PropertiesLatinOneAdapterTest.java
server/zanata-war/src/test/java/org/zanata/adapter/PropertiesUTF8AdapterTest.java
server/zanata-war/src/test/resources/org/zanata/adapter/test-properties-latin1.properties
server/zanata-war/src/test/resources/org/zanata/adapter/test-properties-utf8.properties

- test(adapter): Add properties tests
Test UTF-8 and Latin1 properties documents, the latter using generated files
- refactor(adapter): Relocate duplicated code
Move duplicated stream-in code to a util class
Use NonNull for parseDocument function rather than check and throw.
- Code quality
- Testing
- If …

Properties adapter tests

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml

https://zanata.atlassian.net/browse/ZNTA-1748
- Code quality
- Testing …

fix(ZNTA-1748): display dialog when export tmx per language

---

docs/user-guide/system-admin/configuration/installation.md
server/zanata-war/src/main/java/org/zanata/servlet/UrlRewriteConfig.java

When the system property `zanata.redirectHttpToHttps` is `true`, any HTTP requests forwarded by a proxy or load balancer with the header `X-Forwarded-Proto: http` will be redirected to ~the equivalent HTTPS URL~ the top-level HTTPS page, ie https://hostname.example.com/.
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1746
- Code quality
- If code is …

feat(ZNTA-1746) add zanata.redirectHttpToHttps

---

docs/release-notes.md
server/zanata-model/src/main/java/org/zanata/model/tm/TransMemoryUnitVariant.java
server/zanata-model/src/main/java/org/zanata/tmx/TMXUtil.java
server/zanata-model/src/main/java/org/zanata/util/OkapiUtil.java
server/zanata-model/src/test/java/org/zanata/tmx/TMXUtilTest.java
server/zanata-model/src/test/java/org/zanata/util/OkapiUtilTest.java
server/zanata-war/src/main/java/org/zanata/action/ConfigurationAction.java
server/zanata-war/src/main/java/org/zanata/liquibase/custom/RebuildTMXPlainText.java
server/zanata-war/src/main/java/org/zanata/tmx/TMXParser.java
server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.1.xml
server/zanata-war/src/main/resources/db/db.changelog.xml
server/zanata-war/src/test/java/org/zanata/tmx/TMXParserTest.java
server/zanata-war/src/test/resources/tmx/default-valid-tm.tmx

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1740
TMX import was previously broken for non-Unicode locales. This change ensures
TMX will be imported as Unicode, and fixes existing translation memories. TMX
importing should also be a bit faster.
- Code quality
- Testing
[Considerations …

fix(ZNTA-1740): ensure UTF-8 when parsing TMX segments

---

server/functional-test/pom.xml

Error in mvn test execution for allFuncTests
- Code quality
- Testing
---- …

fix(test): Revert allFuncTests to DetailedTestSuite

---

server/zanata-war/src/test/java/org/zanata/config/DatabaseBackedConfigTest.java
server/zanata-war/src/test/resources/org/zanata/test/model/ApplicationConfigurationData.dbunit.xml

Test coverage for DatabaseBackedConfig
- Code quality
- Testing
---- …

test(coverage): Add tests for ApplicationConfig

---

api/pom.xml
api/zanata-common-api/pom.xml
build-tools/pom.xml
client/pom.xml
client/stub-server/pom.xml
client/zanata-cli/pom.xml
client/zanata-client-commands/pom.xml
client/zanata-maven-plugin/pom.xml
client/zanata-rest-client/pom.xml
common/pom.xml
common/zanata-adapter-glossary/pom.xml
common/zanata-adapter-po/pom.xml
common/zanata-adapter-properties/pom.xml
common/zanata-adapter-xliff/pom.xml
common/zanata-common-util/pom.xml
parent/pom.xml
pom.xml
server/functional-test/pom.xml
server/gwt-editor/pom.xml
server/pom.xml
server/security-common/pom.xml
server/zanata-frontend/pom.xml
server/zanata-liquibase/pom.xml
server/zanata-model/pom.xml
server/zanata-test-war/pom.xml
server/zanata-war/pom.xml

fix(version): the master version should be 4.2.0-SNAPSHOT

---

server/zanata-war/src/main/java/org/zanata/action/AccountMergeAction.java
server/zanata-war/src/test/java/org/zanata/action/AccountMergeActionTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1780
Injected objects in the wrong space. Created through constructor instead.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependenc …

fix(ZNTA-1780): Null pointer exception in OpenID merge

---

server/functional-test/src/main/java/org/zanata/page/WebDriverFactory.java
server/functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectGeneralTab.java
server/functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectWebHooksTab.java
server/functional-test/src/main/java/org/zanata/util/TestEventForScreenshotListener.java
server/functional-test/src/main/java/org/zanata/util/TestFileGenerator.java
server/functional-test/src/main/java/org/zanata/workflow/ClientWorkFlow.java
server/zanata-model/src/main/java/org/zanata/model/Activity.java
server/zanata-model/src/main/java/org/zanata/model/po/HPoTargetHeader.java
server/zanata-model/src/main/java/org/zanata/tmx/TMXUtil.java
server/zanata-model/src/test/java/org/zanata/model/ActivityTest.java
server/zanata-model/src/test/java/org/zanata/model/po/HPoTargetHeaderTest.java
server/zanata-test-war/src/main/java/org/zanata/rest/SampleDataResourceImpl.java

Handle some warnings reported by findbugs and friends.
- Code quality
- Testing
---- …

refactor(warnings): Remove/suppress some findbugs warnings

---

server/zanata-model/src/main/java/org/zanata/model/HApplicationConfiguration.java
server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
server/zanata-war/src/main/java/org/zanata/action/LanguageJoinAction.java
server/zanata-war/src/main/java/org/zanata/action/ServerConfigurationBean.java
server/zanata-war/src/main/java/org/zanata/config/DatabaseBackedConfig.java
server/zanata-war/src/main/resources/messages.properties
server/zanata-war/src/main/webapp/admin/server_configuration.xhtml
server/zanata-war/src/test/java/org/zanata/action/LanguageJoinActionTest.java
server/zanata-war/src/test/java/org/zanata/config/DatabaseBackedConfigTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1763
Remove unnecessary work for admins and co-ordinators when there is no
need to lock down translation privileges. Projects can do this directly.
- Code quality
- Testing …

feature(ZNTA-1763): Add an option to automatically accept language team requests

---

server/zanata-war/src/main/java/org/zanata/action/NewProfileAction.java
server/zanata-war/src/main/resources/messages.properties
server/zanata-war/src/test/java/org/zanata/action/NewProfileActionTest.java

Also replace hard coded strings with Messages
- Code quality
- Testing
----
---
This …

test(action): NewProfileAction test

---

server/zanata-war/src/main/java/org/zanata/action/AccountMergeAction.java
server/zanata-war/src/test/java/org/zanata/action/AccountMergeActionTest.java

AccountMergeAction unit tests. Also
- changes the private static inner class to be a package private class
- injects ZanataIdentity rather than using .Instance()
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Develop …

test(action): AccountMergeAction unit tests

---

server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1794
- Code quality
- Testing
---- …

fix(ZNTA-1794): avoid bad file URL handling

---

build

Updated the order of commands in build script
- Code quality
- Testing
---- …

fix: updated build help script

---

server/zanata-frontend/src/editor/app/utils/RoutingHelpers.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1774
Paging code was using the old history (`hashHistory`) instead of the one we switched to a while ago (`browserHistory`).
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Develop …

Fix paging in React editor (ZNTA-1774)

---

server/zanata-war/src/test/java/org/zanata/webhook/events/DocumentMilestoneEventTest.java

- Code quality
- Testing
----
--- …

test(coverage): DocumentMilestoneEvent test

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/SearchResultsView.ui.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1778
ISSUE: The search and replace header (click on the search icon in the editor) has scrollbars is odd places and is not sized to fit its contents.
RESOLUTION: Increased height of tables, added padding where necessary
- Code quality
- Testing
- If there are new …

fix: removed scrollbar from search and replace header (ZNTA-1778)

---

client/zanata-cli/pom.xml
client/zanata-cli/src/main/assembly/bin.xml
docs/client/installation/windows-installation.md

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1141
* include generated bat script for windows into the dist tar.gz and zip
* upgrade the plugin version
This also brings in the changes in https://github.com/zanata/zanata-client/pull/90 (I had to manually apply the changes because the file and repo has all moved.
- Code quality
- Testing …

ZNTA-1141 - enable windows bat script to be included

---

server/pom.xml

- Code quality
- Testing
----
--- …

refactor: update to Kotlin 1.0.7

---

server/pom.xml
server/zanata-test-war/pom.xml

fix(ZNTA-1783): Upgrade entityunit

---

server/zanata-model/src/main/java/org/zanata/model/HPerson.java
server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml
server/zanata-war/src/main/resources/db/db.changelog.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1760
* delete user will cascade delete project locale members
- Code quality
- Testing
----
*This …

ZNTA-1760 - add missing database constraints

---

api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectIterationLocalesResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectLocalesResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectsResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/SourceDocResource.java
server/zanata-war/src/main/java/org/zanata/exception/DocumentUploadException.java
server/zanata-war/src/main/java/org/zanata/file/DocumentUploadUtil.java
server/zanata-war/src/main/java/org/zanata/file/SourceDocumentUpload.java
server/zanata-war/src/main/java/org/zanata/file/TranslationDocumentUpload.java
server/zanata-war/src/test/java/org/zanata/file/DocumentUploadUtilTest.java
server/zanata-war/src/test/java/org/zanata/file/SourceDocumentUploadTest.java

- Code quality
- Testing
----
--- …

refactor: rename ChunkUploadException to DocumentUploadException

---

server/zanata-war/src/main/java/org/zanata/action/ProjectHome.java
server/zanata-war/src/main/java/org/zanata/action/RoleAssignmentRuleAction.java
server/zanata-war/src/main/java/org/zanata/action/VersionGroupHome.java
server/zanata-war/src/main/java/org/zanata/dao/DocumentDAO.java

Replace new Long with Long.valueOf (performance).
Suggest NO_QA and coverage concerns for this minor change.
- Code quality
- Testing …

fix(warning): Replace new Long with Long.valueOf

---

server/zanata-model/src/main/java/org/zanata/model/HApplicationConfiguration.java
server/zanata-model/src/test/java/org/zanata/model/HApplicationConfigurationTest.java

HApplicationConfiguration overrides equals and hashcode functions
- Code quality
- Testing
---- …

fix(warning): HApplicationConfiguration overrides equals function

---

server/zanata-war/src/main/webapp-jboss/WEB-INF/web.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1826
Use pretty URL for 404 redirects.
- Code quality
- Testing
---- …

fix(ZNTA-1826) use pretty 404 link

---

server/zanata-frontend/src/frontend/app/containers/Explore/ProjectTeaser.jsx

State the project ID instead instead of the redundant "No description available"
- Code quality
- Testing
---- …

fix(explore): Use project id instead of no description available

---

server/zanata-frontend/src/frontend/app/containers/Explore/GroupTeaser.jsx

fix(explore) : Group id if no description

---

server/zanata-war/src/main/webapp/dashboard/home.xhtml

Don't leave empty space after locale icon on dashboard, provide a link instead.
- Code quality
- Testing
---- …

fix(usability): Add link to join a language team

---

server/functional-test/src/main/java/org/zanata/page/projectversion/versionsettings/VersionDocumentsTab.java
server/zanata-model/src/main/java/org/zanata/util/ZanataEntities.java
server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/255)

ZNTA-1760 - modify constraint and fix functional test

---

server/zanata-model/src/main/java/org/zanata/model/HDocumentHistory.java
server/zanata-model/src/main/java/org/zanata/model/HPersonEmailValidationKey.java
server/zanata-model/src/main/java/org/zanata/model/HSimpleComment.java
server/zanata-model/src/test/java/org/zanata/model/HDocumentHistoryTest.java
server/zanata-model/src/test/java/org/zanata/model/HPersonEmailValidationKeyTest.java
server/zanata-model/src/test/java/org/zanata/model/HSimpleCommentTest.java

Deep-copy dates to prevent vulnerability (ei-expose-rep)
- Code quality
- Testing
---- …

fix(warnings): Remove potential EI_EXPOSE_REP vulnerability in Date

---

server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java
server/zanata-war/src/main/java/org/zanata/action/LanguageJoinAction.java
server/zanata-war/src/main/resources/messages.properties
server/zanata-war/src/main/webapp/language/language.xhtml
server/zanata-war/src/test/java/org/zanata/action/LanguageActionTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1840
Remove the "introduce yourself" step for auto accepted translator join.
Also remove requests for the same, which may occur if admin set auto
accept to true with requests pending.
- Code quality
- Testing …

fix(ZNTA-1840): Remove the introduction dialog for auto-accepted locale joins

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TransMemoryMergePresenter.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/resources/UiMessages.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TMMergeForm.ui.xml
server/zanata-war/src/test/java/org/zanata/webtrans/client/presenter/TransMemoryMergePresenterTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1834
- Code quality
- Testing
---- …

ZNTA-1834 TM merge reword

---

server/zanata-model/src/main/java/org/zanata/model/HApplicationConfiguration.java
server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
server/zanata-war/src/main/java/org/zanata/action/ServerConfigurationBean.java
server/zanata-war/src/main/java/org/zanata/config/DatabaseBackedConfig.java
server/zanata-war/src/main/java/org/zanata/service/impl/GravatarServiceImpl.java
server/zanata-war/src/main/resources/messages.properties
server/zanata-war/src/main/webapp/admin/server_configuration.xhtml
server/zanata-war/src/test/java/org/zanata/ApplicationConfigurationTest.java
server/zanata-war/src/test/java/org/zanata/config/DatabaseBackedConfigTest.java
server/zanata-war/src/test/java/org/zanata/service/impl/GravatarServiceImplTest.java
server/zanata-war/src/test/resources/org/zanata/test/model/ApplicationConfigurationData.dbunit.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1846
Allow admin to set a minimum gravatar image rating. G seemed a bit too constrictive, and it may as well be up to the admin.
Default to 'G' if not set.
- Code quality
- Testing …

fix(ZNTA-1846): Admin setting for Gravatar image rating

---

server/gwt-editor/src/main/java/org/zanata/webtrans/Application.gwt.xml
server/gwt-editor/src/main/java/org/zanata/webtrans/ApplicationI18n.gwt.xml
server/zanata-war/src/main/webapp/WEB-INF/faces-config.xml

https://zanata.atlassian.net/browse/ZNTA-1851
- Code quality
- Testing …

feat: enabled Simplify chinese locale for Zanata server and editor

---

server/zanata-war/src/test/java/org/zanata/action/ContactAdminActionTest.java

Added test for contact admin action

---

.editorconfig
.mvn/extensions.xml
Jenkinsfile
api/zanata-common-api/pom.xml
build-tools/pom.xml
build-tools/src/test/java/TestJenkinsfile.java
client/zanata-cli/pom.xml
mvnw
parent/pom.xml
run-clean.sh
server/etc/scripts/extractAppserver.groovy
server/pom.xml
server/zanata-frontend/pom.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1414
Script our build pipelines with Jenkinsfile
- Code quality
- Testing
----
*This template can …

ZNTA-1414: Script our build pipelines with Jenkinsfile

---

server/zanata-war/src/main/webapp/dashboard/home.xhtml
server/zanata-war/src/main/webapp/language/language.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1853*
- Code quality
- Testing
----
*This …

fixed : ZNTA-1853 language and dashboard links

---

server/zanata-war/src/main/webapp/project/create_project.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1860*
- Code quality
- Testing
----
*This …

fix : ZNTA-1860 projects link on create project

---

server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.css

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1863
TM details modal source text incorrectly aligned on small screens
Need to fix the padding that has been set for the text heading 'Source'
Pretty sure I have fixed this previously but something must have overridden my changes.
_Please Note:_ As part of this issue I have also improved the design of the suggestions modal so that it is easier to read. I inverted the heading colours and fiddled with the font weights.
It now  looks like this:
Before these changes it looked like this:
The reviewer can …

fix: alignment of source header in TM details modal on small screens (ZNTA-1863)

---

Jenkinsfile
build-tools/src/test/java/TestJenkinsfile.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1870
Configure Pipeline jobs to remove generated files from the workspace after each build (including jars, wars, logs, screenshots, node_modules). This may save 2.2GB per workspace in some cases.
- Code quality
- Testing
[Considerations for …

Run git clean after build

---

server/docker/rundev.sh

JAVA_OPTS was being overridden, thus removing the default option `-Djava.net.preferIPv4Stack=true` and heap size options.
- Code quality
- Testing
---- …

fix "Protocol family unavailable" error in undertow.HttpListenerService

---

server/zanata-frontend/src/frontend/package.json

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1896
Stops the Jenkins logs being flooded with progress updates during draft build.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-depe …

chore(ZNTA-1896): prevent editor draft build flooding the jenkins logs

---

Jenkinsfile
build-tools/src/test/java/TestJenkinsfile.java
build-tools/src/test/java/hudson/AbortException.java

- Code quality
- Testing
----
--- …

chore: call codecov from Jenkinsfile

---

server/zanata-frontend/src/frontend/app/editor/components/ProgressBar/story.js
server/zanata-frontend/src/frontend/app/editor/components/stories.js

*Add a storybook section for Progress bars*
- Code quality
- Testing
----
---
This …

chore: add storybook stories for ProgressBar component

---

server/zanata-war/src/main/resources/db/changelogs/db.changelog-4.2.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1859
* Add missing foreign key constraints in liquibase
* Drop duplicate index, add missing index, missing unique key constraint
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Dev …

ZNTA-1859 - fix liquibase to match hibernate

---

server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java
server/zanata-war/src/test/java/org/zanata/ApplicationConfigurationTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1822
- Code quality
- Testing
---- …

ZNTA-1822 email log settings will take effect immediately

---

server/zanata-war/src/test/java/org/zanata/service/impl/TransMemoryMergeServiceImplTest.java
server/zanata-war/src/test/java/org/zanata/transaction/TransactionUtilForUnitTest.java

- Code quality
- Testing
----
--- …

Fix NullPointerException in test

---

Jenkinsfile

- Code quality
- Testing
----
--- …

chore(Jenkinsfile): publish checkstyle/findbugs

---

server/zanata-frontend/src/frontend/makefile
server/zanata-frontend/src/frontend/package.json

JIRA issue URL: *There is no JIRA for this*
All stories.js and story.js files are just for the storybook overview,
and similar to test files it is not appropriate to unit test them.
This change excludes all files with either of those names from the
coverage statistics.
- Code quality
- Testing …

chore(storybook): skip coverage stats on storybook files

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1897
Fixed positioning of clear selection button on Profile page - now in line with heading it sits next to
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#n …

ZNTA-1897: fix positioning of Profile clear selection button

---

Jenkinsfile
build-tools/src/test/java/TestJenkinsfile.java

Integration tests stopped running (with Jenkinsfile) after https://github.com/zanata/zanata-platform/pull/278. 
One of the new publishers must be setting build status to 'SUCCESS' (instead of null), so we should check for either.
- Code quality
- Testing …

chore: ensure int. tests run on SUCCESS

---

server/zanata-model/src/main/java/org/zanata/util/ZanataEntities.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/285)

fix functional test after merging ZNTA-1859

---

server/zanata-frontend/src/frontend/app/components/Notification/component.js

fix: remove unused import

---

Jenkinsfile
build-tools/src/main/resources/zanata-build-tools/findbugs-filter.xml

- Code quality
- Testing
----
--- …

chore: enable WarningsPublisher/AnalysisPublisher

---

server/zanata-frontend/src/frontend/app/editor/components/GlossaryTermModal/component.js
server/zanata-frontend/src/frontend/app/editor/components/GlossaryTermModal/story.js
server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css
server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.css
server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1838
Remove zanata-ui modal from editor (Glossary Details and Suggestions modals), and replaced with frontend modal component.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Devel …

removed zanata-ui modals from editor

---

server/pom.xml
server/zanata-war/pom.xml
server/zanata-war/src/test/resources/META-INF/persistence.xml
server/zanata-war/src/test/resources/arquillian.xml
server/zanata-war/src/test/resources/arquillian/persistence.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1914
Avoids IncompatibleClassChangeError on EAP 7.0.5
- Code quality
- Testing
----
*This …

Avoid hibernate-testing.jar in Arquillian tests

---

server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1910
The 100% match text in the Editor Suggestions panel doesn't flow over two lines anymore.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologie …

ZNTA-1910 editor percentage wrapping

---

server/zanata-model/src/main/java/org/zanata/model/Activity.java
server/zanata-model/src/test/java/org/zanata/model/ActivityTest.java

Add equals method for Activity, using business rules.
- Code quality
- Testing
---- …

fix(warnings): Add equals and hashcode methods to activity

---

Jenkinsfile

Fix logs archiving
- Code quality
- Testing
----
--- …

fix(JenkinsFile): archive logs

---

server/zanata-war/src/main/java/org/zanata/ApplicationConfiguration.java

ZNTA-1822 - only activate email logging option when enabled

---

Jenkinsfile

Use ~/.m2/settings.xml instead of .travis-settings.xml 
- Code quality
- Testing
---- …

refactor: use default settings.xml instead

---

server/functional-test/src/main/java/org/zanata/page/administration/TranslationMemoryPage.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1937
Fix webdriver trying to click a button that's not ready
- Code quality
- Testing
----
*This …

fix(ZNTA-1937): Ensure button is ready before click

---

api/zanata-common-api/README.md
api/zanata-common-api/etc/enunciate/enunciate.xml
api/zanata-common-api/pom.xml
api/zanata-common-api/src/main/java/org/zanata/rest/dto/Account.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/ProcessStatus.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/resource/AbstractResourceMeta.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/resource/Resource.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/resource/TextContainer.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/resource/TextFlow.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/AccountResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/AsynchronousProcessResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/CopyTransResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectIterationLocalesResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectLocalesResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectVersionResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectsResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/SourceDocResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslatedDocResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslationMemoryResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/VersionResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/package-info.java

*Constant additions to improve the REST API documentation*
- Code quality
- Testing
---- …

Rest api docs

---

Jenkinsfile
server/pom.xml
server/zanata-model/src/main/java/org/zanata/model/Glossary.java
server/zanata-model/src/main/java/org/zanata/model/HAccountActivationKey.java
server/zanata-model/src/test/java/org/zanata/model/SlugEntityBaseTest.java
server/zanata-war/src/test/java/org/zanata/security/permission/PermissionEvaluatorTest.java
server/zanata-war/src/test/java/org/zanata/service/impl/CopyTransServiceUnitTest.java

Hopefully this will fix master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/306)

Fix javac warnings failing master build

---

server/zanata-war/src/test/java/org/zanata/arquillian/Deployments.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1944
- Code quality
- Testing
---- …

chore(ZNTA-1944): alow Arquillian to use remote repos

---

server/zanata-war/src/main/webapp/version-group/create_version_group.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1947*
*[There is no option to cancel or go back on create group page hence create link for groups.]*
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-tec …

fix :  ZNTA-1947 groups link

---

server/zanata-war/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1966
- Code quality
- Testing
---- …

ZNTA-1966 - include TransMemoryUnit id into the result id list

---

server/zanata-war/src/main/java/org/zanata/action/LoginAction.java
server/zanata-war/src/main/webapp/account/login.xhtml
server/zanata-war/src/test/java/org/zanata/action/LoginActionTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-481
Log in with username or email address
- Code quality
- Testing
---- …

fix(ZNTA-481): Log in with username or email address

---

server/pom.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1728
This pull request target will probably be changed to `release` after the branch for Zanata 4.2 happens, unless we merge it before that.
- Code quality
- Testing …

Update to ocpsoft rewrite-servlet 3.4.1.Final

---

server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js
server/zanata-frontend/src/frontend/app/styles/style.less
server/zanata-frontend/src/frontend/package.json
server/zanata-frontend/src/frontend/yarn.lock

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1865
Frontend modal work for Version Merge Modal - made in storybook.
Run `make storybook-frontend`, then in storybook go to Modal -> version-merge.
* The **drag and drop** functionality was implemented using 'react-draggable' and could do with some tidying up (so it works in a nicer fashion if possible). I think this is best handled by someone with more backend experience.  https://github.com/mzabriskie/react-draggable
* The **+ and - arrows** (see mockups in JIRA) were difficult to add for me in this task. Unsure how to do it in es6 or if there is an easy way to show them - react-bootstrap doesn't seem to have functionality to do so. However the fact that one of these boxes is expanded from the outset provides an indicator that …

feat(ZNTA-1865):version merge modal

---

server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js
server/zanata-frontend/src/frontend/app/styles/style.less
server/zanata-frontend/src/frontend/yarn.lock

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1969
Add Project Name to Version Sort in Version Merge Modal Story
- Code quality
- Testing
---- …

feat(ZNTA-1969): added project names to draggable sort

---

server/zanata-model/src/main/java/org/zanata/model/HTextFlowTarget.java
server/zanata-war/src/main/java/org/zanata/service/impl/TranslationServiceImpl.java

https://zanata.atlassian.net/browse/ZNTA-1973
- Code quality
- Testing …

fix: clear HTextFlowTarget contents when set

---

server/zanata-frontend/src/frontend/app/containers/UserProfile/index.jsx
server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1971
User profile can now handle long file names using ellipsis
- Code quality
- Testing
---- …

fix(ZNTA-1971): handling of long usernames on profile page

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1972
Centered 'No content' text and icon on glossary page.
- Code quality
- Testing
----
*This …

fix(ZNTA-1973) centered no content glossary icon

---

build-tools/src/main/resources/zanata-build-tools/detekt.yml
server/pom.xml

- Code quality
- Testing
----
--- …

chore: update detekt

---

server/zanata-frontend/src/frontend/app/index.js
server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1980
Styling of comment box in glossary modal
Targeting release
- Code quality
- Testing
---- …

fix(ZNTA-1980): styling of glossary comment box

---

api/zanata-common-api/src/main/java/org/zanata/rest/dto/Account.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/PutUserCommand.java
client/zanata-client-commands/src/test/java/org/zanata/client/commands/PutUserCommandTest.java
server/zanata-war/src/main/java/org/zanata/rest/service/AccountService.java
server/zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java

https://zanata.atlassian.net/browse/ZNTA-1684:
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies …

refactor: rename tribes to languages

---

server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js
server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1865
This is version based TM merge, which uses lucene search. 
The existing version merge will remain the same. 
The existing TM merge in editor will remain the same.
**This is a storybook component**  which can be accessed by running `make storybook-frontend` and navigating to Modal > Version TM
- Code quality
- Code is in an appropriate …

Design: ZNTA-1969-vTM-story

---

server/pom.xml

~Partly to avoid https://youtrack.jetbrains.com/issue/KT-15778~ No longer the case, since https://github.com/zanata/zanata-platform/pull/303 upgraded to Kotlin 1.1.1
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines# …

chore: update to Kotlin 1.1.2

---

api/zanata-common-api/pom.xml
client/pom.xml
client/stub-server/pom.xml
client/zanata-cli/pom.xml
client/zanata-client-commands/pom.xml
client/zanata-maven-plugin/pom.xml
client/zanata-rest-client/pom.xml
common/zanata-adapter-glossary/pom.xml
common/zanata-adapter-xliff/pom.xml
common/zanata-common-util/pom.xml
parent/pom.xml
server/functional-test/pom.xml
server/gwt-editor/pom.xml
server/pom.xml
server/zanata-model/pom.xml
server/zanata-test-war/pom.xml
server/zanata-war/pom.xml

- Blacklist findbugs:annotations
- Replace with fine-grained dependencies:
findbugs-annotations, jcip-annotations, jsr305
This is a pre-requisite for https://github.com/zanata/zanata-platform/pull/308
- Code quality
- Testing …

Split findbugs:annotations dependency

---

server/functional-test/pom.xml

Fixed [WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
- Code quality
- Testing
---- …

fix(pom): The expression ${version} is deprecated

---

api/pom.xml
build-tools/src/main/resources/zanata-build-tools/findbugs-filter.xml
client/pom.xml
common/pom.xml
parent/pom.xml
server/pom.xml

- Code quality
- Testing
----
--- …

chore: enable findbugs for server module

---

parent/pom.xml
server/zanata-war/src/test/java/org/zanata/ZanataDbunitJpaTest.java
server/zanata-war/src/test/java/org/zanata/rest/ResourceRequestEnvironment.java
server/zanata-war/src/test/java/org/zanata/ui/faces/FacesMessagesTest.java

This allows us to prevent access to (eg) `*.internal.*` packages, the use of which can lead to maintenance problems.
- Code quality
- Testing
----
*This …

chore: add restrict-maven-plugin

---

server/functional-test/pom.xml

Should fix this warning:
```
Some problems were encountered while building the effective model for org.zanata:functional-test:takari-jar:4.3.0-SNAPSHOT
'profiles.profile[run-functional-test].plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.codehaus.gmavenplus:gmavenplus-plugin @ org.zanata:functional-test:[unknown-version], /home/fedora/jenkins/workspace/-org_zanata-platform_PR-308-AWKSO5Q5BTEUCCLGP7T4COKES6424E72BHFVMWYNUCSGB46KRGQA/server/functional-test/pom.xml, line 698, column 19
It is highly recommended to fix these problems because they threaten the stability of your build.
For this reason, future Maven versions might no longer support building such malformed projects.
```
[Zanata Development …

chore: fix Maven warning for gmavenplus

---

Jenkinsfile

Cherry-picked from https://github.com/zanata/zanata-platform/pull/336 for `release` branch, so that we can run full functional tests against a pull request when desired.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guideli …

chore(Jenkinsfile): add allFuncTests option

---

server/zanata-model/src/main/java/org/zanata/hibernate/search/ContainingWorkspaceBridge.java
server/zanata-model/src/main/java/org/zanata/hibernate/search/IndexFieldLabels.java
server/zanata-war/src/main/java/org/zanata/service/IndexingService.java
server/zanata-war/src/main/java/org/zanata/service/impl/IndexingServiceImpl.java
server/zanata-war/src/main/java/org/zanata/service/impl/SlugEntityUpdatedListener.java
server/zanata-war/src/test/java/org/zanata/service/impl/SlugEntityUpdatedListenerTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1865
This will include project version slug into lucene index.
How/what to QA:
This PR is to include project version slug into the lucene index. So I think changing version slug and then verify TM is not affected will be part of QA. Anything else might be affected by version indexing can also be tested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/331)

ZNTA-1865 - prep for version merge by TM (index version)

---

Jenkinsfile
server/zanata-war/src/main/java/org/zanata/action/validator/EmailListValidator.java
server/zanata-war/src/test/java/org/zanata/action/validator/EmailListValidatorTest.java

- Code quality
- Testing
----
--- …

Avoid ref to internal EmailValidator class

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2005
Text area box in Project Settings / About should not flow outside of container
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-depe …

fix(ZNTA-2005) set textarea max width to 100% to avoid overflow

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/init/InitCommand.java
client/zanata-rest-client/src/test/java/org/zanata/rest/client/MockServerTestUtil.java
server/zanata-model/src/main/java/org/zanata/model/HDocument.java
server/zanata-war/src/test/java/org/zanata/RestTest.java
server/zanata-war/src/test/java/org/zanata/action/AccountMergeActionTest.java
server/zanata-war/src/test/java/org/zanata/action/LoginActionTest.java
server/zanata-war/src/test/java/org/zanata/rest/editor/service/TransMemoryMergeManagerTest.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/AnonymousUserRawRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/SourceAndTranslationResourceRestBase.java
server/zanata-war/src/test/java/org/zanata/ui/autocomplete/AutocompleteTest.java

serializable class has no definition of serialVersionUID
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/ …

fix: remove missing serialVersionUID warning

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1998
Fixed text wrapping on projects with long document names in Search and Replace.
To replicate:
- Go to vendor instance in Chrome 58
- Find RHV VM Management Guide
- Download document Explanation of Settings in the New Template and Edit Template Windows
- Download translated PO for Chinese (Simplified) for this document
- Upload document and translations in new project
- Go to search and replace and search 'virtual machine'
- View table layout
It now should not look broken like it does in this image:
to refresh your …

fix(ZNTA-1998): handling of target and source table cells in search&replace

---

client/zanata-cli/pom.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2012
- Code quality
- Testing
---- …

ZNTA-2012 - assemble generated zanata-cli script

---

server/zanata-war/src/test/java/org/zanata/ZanataRestTest.java
server/zanata-war/src/test/java/org/zanata/model/HDocumentHistoryJPATest.java
server/zanata-war/src/test/java/org/zanata/model/HTextFlowHistoryJPATest.java
server/zanata-war/src/test/java/org/zanata/model/HTextFlowTargetHistoryJPATest.java

redundant cast warnings
- Code quality
- Testing
---- …

fix: remove compiler warning - redundant cast

---

server/zanata-war/src/test/java/org/zanata/ZanataRestTest.java
server/zanata-war/src/test/java/org/zanata/async/AsyncTaskHandleTest.java
server/zanata-war/src/test/java/org/zanata/model/HDocumentHistoryJPATest.java
server/zanata-war/src/test/java/org/zanata/model/HTextFlowHistoryJPATest.java
server/zanata-war/src/test/java/org/zanata/model/HTextFlowTargetHistoryJPATest.java

found raw type: org.zanata.async.AsyncTaskHandle
- Code quality
- Testing
----
*This template can be updated …

fix: remove compiler warning - found raw type: org.zanata.async.AsyncTaskHandle

---

server/functional-test/src/main/java/org/zanata/page/administration/ManageUserAccountPage.java
server/functional-test/src/test/java/org/zanata/feature/administration/ManageUsersTest.java
server/zanata-war/src/main/java/org/zanata/action/RegisterAction.java
server/zanata-war/src/main/java/org/zanata/action/UserAction.java
server/zanata-war/src/main/resources/messages.properties
server/zanata-war/src/main/webapp/admin/userdetail.xhtml
server/zanata-war/src/test/java/org/zanata/action/UserActionTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2015
Add Full Name field, editable.
Checks for >0 visible characters
Provides a placeholder of the original name.
Limits to 80 characters.
Also checks the register page for whitespace.
- Code quality
- Testing …

fix(ZNTA-2015): Allow admin to change a user's name

---

server/zanata-frontend/src/frontend/app/styles/index.less
server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2019
Removed the -webkit-box css from nav-link which was added in error to handle really really old browsers.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines …

fix(ZNTA-1019): nav layout bug

---

server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js
server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1865
Updated the design of the Version TM Merge story to include the options from TM Merge as directed. 
`make storybook-frontend`
then go to `localhost:9001`
then go to Modals
- Code quality
- Testing …

feat(ZNTA-1865): version TM merge modal revision

---

server/zanata-frontend/src/frontend/app/containers/UserProfile/index.jsx

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2020
Fixed wrapping of email address on profile page so it is not inline with username 
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and- …

fix(ZNTA-2020): wrapping of email on profile page

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1996
Make container for dropdown for add a maintainer tall enough to handle scrollable list of usernames - had to be resolved using margin on the parent element
Also fixed up the height of the title on the group page as it was overlapping with the bottom border
**Dropdown not active**
**Active dropdown**
- Code quality
- Code is in an …

fix(ZNTA-1996): add maintainer dropdown container now handles username display

---

api/zanata-common-api/src/main/java/org/zanata/common/ProjectType.java
api/zanata-common-api/src/test/java/org/zanata/common/ProjectTypeTest.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/TransFileResolver.java

https://zanata.atlassian.net/browse/ZNTA-2011
- Code quality
- Testing …

fix(ZNTA-2011): offlinepo download exception

---

server/zanata-war/src/test/java/org/zanata/file/SourceDocumentUploadTest.java

- Code quality
- Testing
----
---
This …

Znta 1924 org.mockito.matchers

---

server/zanata-war/src/test/java/org/zanata/ApplicationConfigurationTest.java
server/zanata-war/src/test/java/org/zanata/dao/TextFlowTargetHistoryDAOTest.java
server/zanata-war/src/test/java/org/zanata/email/EmailStrategyTest.java
server/zanata-war/src/test/java/org/zanata/ui/InMemoryListFilterTest.java

fix: insert missing serialVersionUID

---

server/zanata-war/src/test/java/org/zanata/webtrans/client/presenter/DocumentListPresenterTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/client/presenter/EditorOptionsPresenterTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/client/presenter/ForceReviewCommentPresenterTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/client/presenter/WorkspaceUsersPresenterTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/server/SeamDispatchTest.java

fix: remove uncheck method invocation

---

server/zanata-frontend/pom.xml
server/zanata-frontend/src/frontend/app/editor/api/index.js
server/zanata-frontend/src/frontend/app/editor/config.json
server/zanata-frontend/src/frontend/app/editor/config/index.js
server/zanata-frontend/src/frontend/app/editor/index.js
server/zanata-frontend/src/frontend/package.json
server/zanata-frontend/src/frontend/webpack.config.js
server/zanata-frontend/src/frontend/webpack.prod.config.js
server/zanata-frontend/src/frontend/yarn.lock

JIRA issue URL:
* https://zanata.atlassian.net/browse/ZNTA-1988
* https://zanata.atlassian.net/browse/ZNTA-1989
* ~~https://zanata.atlassian.net/browse/ZNTA-1790~~
Polyfill `Symbol` and `Intl` for mobile browsers. The `Intl` polyfill is large so it is loaded as a separate chunk only loaded if needed. ~~Sets the history basename so that the editor should work for any path the server is deployed to (e.g. /zanata)~~
*Reviewers* note that index.js has most of its contents wrapped in a function, so it looks like a lot of changes but really it is just indented. The new part is the `if (window.Intl)` block at the bottom, the `history.basename` line and the assignment to `__webpack_public_path__`
- Test it for Symbol and Intl with BrowserStack.
- The layout is broken on Safari 8, but that is a …

Polyfills for tablets (ZNTA-1988, ZNTA-1989)

---

server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-29
Storybook design for TMX export modal when handling lots of files - has file preparation count and a button to download when finished. This should be used when the download is going to create a state of inactivity when the files are preparing.
- Code quality
- Testing
- …

feat(ZNTA-29): storybook for TMX export modal when reindexing

---

server/zanata-war/src/test/java/org/zanata/rest/compat/ProjectIterationRawCompatibilityITCase.java
server/zanata-war/src/test/java/org/zanata/rest/compat/ProjectRawCompatibilityITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/AccountRawRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/AnonymousUserRawRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/AsyncResourceRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/CopyTransRestITCase.java

- Code quality
- Testing
----
---
This …

fix: remove warning for found raw type: javax.ws.rs.client.Entity

---

server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js

JIRA issue URL: 
Small update to Version Merge modal to add Merge Translations button to top of modal so that when there are long lists of projects, the user can access the button without scrolling all the way to the footer.
- Code quality
- Testing …

update version merge modals

---

api/zanata-common-api/src/test/java/org/zanata/common/ProjectTypeTest.java
client/stub-server/src/main/java/org/zanata/rest/service/MockFileResource.java
server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java

fix: deprecate test for org.zanata.common.ProjectType has been deprecated

---

server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/NoSuggestionsPanel.test.js
server/zanata-frontend/src/frontend/app/editor/components/NoSuggestionsPanel/index.js
server/zanata-frontend/src/frontend/app/editor/containers/GlossaryTab.js
server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css
server/zanata-frontend/src/frontend/app/editor/containers/SuggestionsBody.js
server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1940
- added suggestions loader in editor (using LoaderText component in frontend)
- and made minor css fixes to translation panel loaders (left padding)
- also made changes to height of h1 in frontend to handle bottom-border on all pages
- Code quality
- Testing
- If …

fix(ZNTA-1940) added suggestions loader 

---

server/zanata-war/src/test/java/org/zanata/model/TestFixture.java
server/zanata-war/src/test/java/org/zanata/webtrans/client/presenter/DocumentListPresenterTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/client/presenter/TargetContentsPresenterTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/client/service/HistoryEventHandlerServiceTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/client/service/NavigationServiceIntegrationTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/client/service/NavigationServiceUnitTest.java

fix: remove raw type in GwtEvent

---

Jenkinsfile

- Code quality
- Testing
----
--- …

chore: enable StabilityTestDataPublisher

---

Jenkinsfile
server/functional-test/pom.xml
server/functional-test/src/main/java/org/zanata/page/AbstractPage.java
server/functional-test/src/main/java/org/zanata/page/editor/ReactEditorPage.java
server/functional-test/src/main/java/org/zanata/page/webtrans/EditorPage.java
server/functional-test/src/test/java/org/zanata/feature/editor/EditorAlphaTest.java
server/functional-test/src/test/java/org/zanata/feature/editor/EditorTestSuite.java
server/functional-test/src/test/java/org/zanata/feature/testharness/ZanataTestCase.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2003
Required setting context path to root. Adds a function to
close windows other than the first on test completion.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Gu …

fix(ZNTA(2003): WebDriver test for alpha editor

---

server/zanata-war/src/test/java/org/zanata/ui/autocomplete/AutocompleteTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/client/presenter/SearchResultsPresenterTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/server/rpc/LoadOptionsHandlerTest.java
server/zanata-war/src/test/java/org/zanata/webtrans/server/rpc/SaveOptionsHandlerTest.java

fix: remove unchecked conversion warnings

---

server/zanata-war/src/test/java/org/zanata/webtrans/client/presenter/TargetContentsPresenterTest.java

fix: remove unchecked generic array creation

---

api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectIterationLocalesResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/SourceDocResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslatedDocResource.java
client/stub-server/src/main/java/org/zanata/rest/service/MockProjectIterationResource.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/push/RawPushCommand.java
client/zanata-rest-client/src/test/java/org/zanata/rest/client/FileResourceClientTest.java
server/gwt-editor/src/main/java/org/zanata/webtrans/shared/validation/action/TabValidation.java
server/zanata-model/src/main/java/org/zanata/model/HDocument.java
server/zanata-war/src/main/java/org/zanata/action/CopyTransAction.java
server/zanata-war/src/main/java/org/zanata/action/LocaleSelectorAction.java
server/zanata-war/src/main/java/org/zanata/action/ProjectHomeAction.java
server/zanata-war/src/main/java/org/zanata/action/VersionGroupHome.java
server/zanata-war/src/main/java/org/zanata/action/VersionHome.java
server/zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java
server/zanata-war/src/main/java/org/zanata/i18n/Messages.java
server/zanata-war/src/main/java/org/zanata/security/SmartEntitySecurityListener.java
server/zanata-war/src/main/java/org/zanata/security/ZanataIdentity.java
server/zanata-war/src/main/java/org/zanata/security/ZanataOpenId.java
server/zanata-war/src/main/java/org/zanata/ui/AbstractAutocomplete.java
server/zanata-war/src/test/java/org/zanata/cache/InfinispanTestCacheContainer.java
server/zanata-war/src/test/java/org/zanata/security/ZanataIdentityTest.java
server/zanata-war/src/test/java/org/zanata/ui/autocomplete/AutocompleteTest.java
server/zanata-war/src/test/java/org/zanata/util/PasswordUtilTest.java

fix: remove warning for internal deprecated method

---

client/zanata-cli/src/main/java/org/zanata/client/ZanataClient.java
common/zanata-common-util/src/main/java/org/zanata/common/util/ElementBuilder.java
server/zanata-model/src/main/java/org/zanata/util/RequestContextValueStore.java
server/zanata-war/src/test/java/org/zanata/rest/service/LocalesServiceTest.java
server/zanata-war/src/test/java/org/zanata/rest/service/ProjectVersionServiceUnitTest.java
server/zanata-war/src/test/java/org/zanata/rest/service/ProjectVersionTest.java
server/zanata-war/src/test/java/org/zanata/rest/service/ProjectsServiceTest.java
server/zanata-war/src/test/java/org/zanata/service/impl/TranslationMemoryServiceImplTest.java
server/zanata-war/src/test/java/org/zanata/test/EventListener.java
server/zanata-war/src/test/java/org/zanata/util/RawRestTestUtils.java

fix: remove unchecked cast warnings

---

client/zanata-cli/src/main/java/org/zanata/client/ZanataClient.java
common/zanata-common-util/src/main/java/org/zanata/common/util/ElementBuilder.java
server/zanata-model/src/main/java/org/zanata/hibernate/search/LocaleFilterFactory.java
server/zanata-model/src/main/java/org/zanata/model/HTextFlowHistory.java
server/zanata-model/src/main/java/org/zanata/util/RequestContextValueStore.java
server/zanata-war/src/main/java/org/zanata/rest/HibernateValidationInterceptor.java
server/zanata-war/src/test/java/org/zanata/rest/service/LocalesServiceTest.java
server/zanata-war/src/test/java/org/zanata/rest/service/ProjectVersionServiceUnitTest.java
server/zanata-war/src/test/java/org/zanata/rest/service/ProjectVersionTest.java
server/zanata-war/src/test/java/org/zanata/rest/service/ProjectsServiceTest.java
server/zanata-war/src/test/java/org/zanata/service/impl/TranslationMemoryServiceImplTest.java
server/zanata-war/src/test/java/org/zanata/test/EventListener.java
server/zanata-war/src/test/java/org/zanata/util/RawRestTestUtils.java

- Code quality
- Testing
----
---
This …

fix: remove uncheck cast warnings, deprecated hibernate lib

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/UnorderedListWidget.java

fix: remove warning for gwt deprecation

---

server/zanata-frontend/src/frontend/README.md
server/zanata-frontend/src/frontend/app/editor/components/IconButton/IconButton.test.js
server/zanata-frontend/src/frontend/makefile
server/zanata-frontend/src/frontend/scripts/codemods/create-component.js
server/zanata-frontend/src/frontend/scripts/codemods/stateful.template.js
server/zanata-frontend/src/frontend/scripts/codemods/stateless.template.js
server/zanata-frontend/src/frontend/scripts/codemods/story.template.js
server/zanata-frontend/src/frontend/scripts/codemods/test.template.js

JIRA issue URL: there is no JIRA for this, just a weekend project
Adds a script to frontend, so `make component` will ask a few questions then set up a new component in storybook ready for development.
- Code quality
- Testing …

Add component creation script

---

client/stub-server/src/main/java/org/zanata/rest/service/MockResourcesApplication.java
client/zanata-cli/src/test/java/org/zanata/client/ParameterRule.java
client/zanata-cli/src/test/java/org/zanata/client/ZanataClientTest.java
server/functional-test/src/main/java/org/zanata/workflow/ClientWorkFlow.java
server/zanata-war/src/test/java/org/zanata/adapter/JsonAdapterTest.java
server/zanata-war/src/test/java/org/zanata/service/impl/TranslationUpdatedManagerTest.java

fix: remove compiler warnings

---

server/zanata-war/src/main/java/org/zanata/rest/ZanataRestResponseInterceptor.java
server/zanata-war/src/main/java/org/zanata/rest/ZanataRestVersionInterceptor.java
server/zanata-war/src/test/java/org/zanata/ZanataRestTest.java

fix: replace resteasy deprecated class

---

Jenkinsfile

- Code quality
- Testing
----
---
This …

chore: update compiler warnings threshold

---

server/zanata-war/src/main/webapp/iteration/view.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2044
Added translate icon to merge translation dropdown link. Used this because I could not get the import icon working (there's no css :before rule with the icon code and I couldn't generate one) - the copy translations link uses the same icon instead of a copy icon so that's why I chose this one. 
- Code quality
- Code is in an appropriate …

fix(ZNTA-2944) merge translations icon added to proj version drop down

---

server/zanata-frontend/src/frontend/app/components/Modal/Modal.story.js
server/zanata-frontend/src/frontend/app/styles/style.less

See title
*note*: this design uses the new version icon (from the react components) which I am slowly implementing across Zanata as a replacement to the [v] icon that does not represent versions in other languages.
- Code quality
- Testing …

(fix) added project and version icons to TMX export modal

---

server/functional-test/src/main/java/org/zanata/page/explore/ExplorePage.java
server/functional-test/src/test/java/org/zanata/feature/search/SearchTestSuite.java
server/functional-test/src/test/java/org/zanata/feature/search/comp/ExploreCTest.java
server/functional-test/src/test/java/org/zanata/feature/search/comp/GroupSearchCTest.java
server/functional-test/src/test/java/org/zanata/feature/search/comp/LanguageSearchCTest.java

Explore comprehensive test

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2063
changed white text to dark blue for improved visibility
- Code quality
- Testing
----
*This …

fix(ZNTA-2063) improved contrast of needs work buttons on profile

---

parent/pom.xml
server/functional-test/src/main/java/org/zanata/page/webtrans/EditorPage.java

- Code quality
- Testing
----
--- …

Type inferencing

---

server/functional-test/src/main/java/org/zanata/page/administration/ManageUserPage.java
server/functional-test/src/test/java/org/zanata/feature/endtoend/AdminEndToEndTest.java

Fix intermittent failure where the page may not have updated the list.
Add some missed logging in this area.
- Code quality
- Testing …

fix(test): Fix intermittent admin e2e test failure

---

Jenkinsfile
server/functional-test/etc/trace-tests.groovy
server/functional-test/src/test/java/org/zanata/util/TestTracing.java

- Collate Polarion and Autotest results into a JSON collection
- (Build) Delete traceability doc if exists, archive it after test run
- Does not affect Zanata (No_QA)
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/De …

feat(test): Traceability parsing script

---

server/functional-test/src/main/java/org/zanata/page/languages/LanguagePage.java
server/functional-test/src/main/java/org/zanata/page/languages/RequestToJoinPopup.java
server/functional-test/src/test/java/org/zanata/feature/language/LanguageTestSuite.java
server/functional-test/src/test/java/org/zanata/feature/language/comp/LanguageCTest.java

Added comprehensive test for language page

---

server/docker/README.md
server/docker/rundb.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/410)

add new option to use an ephemeral database container

---

server/functional-test/etc/trace-tests.groovy
server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt
server/functional-test/src/main/java/org/zanata/page/account/EnterNewPasswordPage.java
server/functional-test/src/main/java/org/zanata/page/account/InactiveAccountPage.java
server/functional-test/src/main/java/org/zanata/page/account/RegisterPage.java
server/functional-test/src/test/java/org/zanata/feature/account/EmailValidationTest.java
server/functional-test/src/test/java/org/zanata/feature/account/InactiveUserLoginTest.java
server/functional-test/src/test/java/org/zanata/feature/account/comp/InactiveUserLoginCTest.java
server/functional-test/src/test/java/org/zanata/feature/account/comp/RegisterCTest.java
server/functional-test/src/test/java/org/zanata/feature/endtoend/UserEndToEndTest.java
server/functional-test/src/test/java/org/zanata/feature/security/SecurityTest.java
server/functional-test/src/test/java/org/zanata/util/EmailQuery.java
server/zanata-war/src/main/webapp/account/password_reset.xhtml

Add comprehensive tests for inactive account. Complete the reset password test and improve the email parsing. Add ids to tests. Improve the trace-tests script.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Developme …

fix(test): Add Polarion ids to and improve account tests

---

server/zanata-frontend/src/frontend/makefile
server/zanata-frontend/src/frontend/package.json

JIRA issue URL: there is not a JIRA for this
This allows command `make test-watch` and `make test-watch coverage=[glob pattern]`
to be run. This command was broken because I forgot to check in the necessary addition to package.json
- Code quality
- Testing …

Fix `make test-watch` so that it works

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/resources/UiMessages.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml
server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml

https://zanata.atlassian.net/browse/ZNTA-2092
- Code quality
- Testing …

fix: switch yellow and white for tm diff

---

server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css
server/zanata-frontend/src/frontend/app/editor/containers/SuggestionDetailsModal/index.css

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2062
Fixed line wrapping and made sure ellipsis work for long document names in suggestions panel
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technol …

fix(ZNTA-2062) fixed wrapping of long document names in editor suggestions panel

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2107
Fixed GWT bug where words broke over multiple lines and were hyphenated. Because this is a high priority fix for translators I have made the changes to the release branch.
- Code quality
- Testing …

fix(ZNTA-2107) word breaking and removal of hyphens for editor

---

api/zanata-common-api/src/main/java/org/zanata/common/EntityStatus.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/CopyTransStatus.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/GlossaryEntry.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/GlossaryInfo.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/GlossaryLocaleInfo.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/GlossaryResults.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/GlossaryTerm.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/Link.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/Links.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/LocaleDetails.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/Project.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/ProjectIteration.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/QualifiedName.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/ResultList.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/VersionInfo.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/resource/Resource.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/resource/TranslationsResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/stats/ContainerTranslationStatistics.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/stats/TranslationStatistics.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/stats/contribution/BaseContributionStatistic.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/stats/contribution/ContributionStatistics.java
api/zanata-common-api/src/main/java/org/zanata/rest/dto/stats/contribution/LocaleStatistics.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/CopyTransResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectsResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslatedDocResource.java
api/zanata-common-api/src/main/java/org/zanata/rest/service/VersionResource.java
server/zanata-war/src/main/java/org/zanata/rest/service/package-info.java

Updates to our enunciate declarations so that API docs have an improved presentation. Changes include:
- Color coded response codes
- Response examples
- Additional documentation for parameters and headers
- other minor improvements...
To generate the api docs locally, type the following command at the root of `zanata-platform`:
```sh
mvn com.webcohesion.enunciate:enunciate-slim-maven-plugin:docs -pl :zanata-common-api
```
Then open the following file in a browser:
`zanata-platform/api/zanata-common-api/target/site/rest-api-docs/index.html`
The reviewer …

Improve REST API docs

---

Jenkinsfile

Related to https://zanata.atlassian.net/browse/ZNTA-1949
Since we have migrate victims to new build server, we can reenable victims.
Notes: http://www.victi.ms/ seems down at the moment (503  Service Unavailable)
Yet we can use the data before Sun Jun 18 23:52:12 UTC 2017
- Code quality
- Testing …

enable(build): enable victims

---

server/zanata-frontend/src/frontend/app/components/Nav/index.jsx

https://zanata.atlassian.net/browse/ZNTA-2064
- Code quality
- Testing …

fix: include dswid for glossary and language page

---

server/zanata-war/src/test/java/org/zanata/provider/DBUnitProvider.java
server/zanata-war/src/test/java/org/zanata/rest/compat/AccountRawCompatibilityITCase.java
server/zanata-war/src/test/java/org/zanata/rest/compat/ProjectIterationRawCompatibilityITCase.java
server/zanata-war/src/test/java/org/zanata/rest/compat/ProjectRawCompatibilityITCase.java
server/zanata-war/src/test/java/org/zanata/rest/compat/StatisticsCompatibilityITCase.java
server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsCompatibilityITCase.java
server/zanata-war/src/test/java/org/zanata/rest/compat/TranslationsRawCompatibilityITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/AccountRawRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/FileRawRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/GlossaryRawRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/ProjectIterationRawRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/ProjectRawRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/ProjectVersionRawRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/ProjectsRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/StatisticsRawRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/TranslationResourceRestITCase.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/VersionRawRestITCase.java

Split out from https://github.com/zanata/zanata-platform/pull/425 (these tests aren't moving to services.jar).
- Code quality
- Testing
----
*This …

Remove some trailing comments

---

server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/settings.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/settings-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/edit_form.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-translation.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-webhook.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/edit_form.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml
server/zanata-war/src/main/webapp/resources/zanata/multi-file-upload.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2114
Fix broken help icons and links. Also add _blank target to open in new tab/page.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-de …

fix(ZNTA-2114): Broken help icons and links

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/push/RawPushCommand.java

https://zanata.atlassian.net/browse/ZNTA-128
- Code quality
- Testing …

fix: null pointer check when pushing raw file

---

server/zanata-war/src/main/java/org/zanata/action/ProjectHome.java
server/zanata-war/src/main/resources/messages.properties
server/zanata-war/src/main/webapp/WEB-INF/layout/project/edit_form.xhtml

https://zanata.atlassian.net/browse/ZNTA-197
- Code quality
- Testing …

fix: validate project name to be alphanumeric

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/pull/RawPullCommand.java

https://zanata.atlassian.net/browse/ZNTA-2098
- Code quality
- Testing …

fix: handle exception when pull with project without content

---

common/zanata-common-util/src/main/java/org/zanata/CommonUtil.gwt.xml
server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.java

https://zanata.atlassian.net/browse/ZNTA-510
- Code quality
- Testing …

refactor: replace method with common-util

---

server/zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab.xhtml
server/zanata-war/src/main/webapp/project/project.xhtml

https://zanata.atlassian.net/browse/ZNTA-666
- Code quality
- Testing …

fix: update member page when add/remove mainainers

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2105
The '+' icon is not visible for the New Version setting in the dropdown. Corrected this in css.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-tech …

fix(ZNTA-2105) changed colour of new version icon

---

api/zanata-common-api/src/main/java/org/zanata/rest/dto/Project.java

https://zanata.atlassian.net/browse/ZNTA-330
- Code quality
- Testing …

fix: update project#description dto size

---

server/zanata-war/src/main/java/org/zanata/action/ProjectHome.java
server/zanata-war/src/main/java/org/zanata/action/VersionHome.java

https://zanata.atlassian.net/browse/ZNTA-658
- Code quality
- Testing …

fix: sort language by display name in project/version page

---

server/zanata-war/src/main/java/org/zanata/action/LanguageAction.java
server/zanata-war/src/main/webapp/WEB-INF/layout/language/search_user_modal.xhtml

https://zanata.atlassian.net/browse/ZNTA-274
- Code quality
- Testing …

fix: disable button when no roles is selected

---

server/zanata-war/src/main/java/org/zanata/action/VersionGroupHome.java
server/zanata-war/src/main/java/org/zanata/security/SecurityFunctions.java
server/zanata-war/src/main/java/org/zanata/util/UrlUtil.java
server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/settings-tab.xhtml

https://zanata.atlassian.net/browse/ZNTA-182
- Code quality
- Testing …

fix: update page when remove group maintainer

---

server/zanata-war/src/main/resources/messages.properties
server/zanata-war/src/main/webapp/iteration/view.xhtml
server/zanata-war/src/main/webapp/project/project.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2132
Fix tooltip for version tmx export select-option.
- Code quality
- Testing
----
*This …

fix(ZNTA-2132): Incorrect tooltip for export project/version tmx

---

server/zanata-frontend/src/frontend/app/containers/UserProfile/CalendarMonthMatrix.jsx
server/zanata-frontend/src/frontend/app/containers/UserProfile/CalendarPeriodHeading.jsx
server/zanata-frontend/src/frontend/app/containers/UserProfile/RecentContributions.jsx

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-1899*
- Code quality
- Testing
----
*This …

fix: ZNTA-1899 changed '...' in profile to 'to'

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2144
Removed padding from table cell buttons in calendar matrix on user profile
Before:
After:
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologi …

fix(ZNTA-2144) removed padding from profile calendar matrix buttons

---

server/zanata-frontend/src/frontend/app/containers/ProjectVersion/index.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2146
The TM Merge Modal (ZNTA-1865) was overriding the html tab title when opened.
This has been removed by excluding the Helmet from the ProjectVersion component.
- Code quality
- Testing …

fix(ZNTA-2146): Remove Helmet from ProjectVersion page

---

server/zanata-frontend/src/frontend/app/components/Modal/index.jsx

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2133
onBlur was triggering the TM Merge modal close when making dropdown selections or on clicking certain areas, changed to check for clicks on modal backdrop class elements and outside of the modal component.
note: Modal component covers the screen with a backdrop element with the class 'modal' and 'container'
- Code quality
- Code is in an …

fix(ZNTA-2133): stop modal closing on dropdown open

---

server/zanata-frontend/src/frontend/app/styles/style.less

https://zanata.atlassian.net/browse/ZNTA-2152
- Code quality
- Testing
----
---
This …

fix(ZNTA-2152): removed css overrides that affected 'add' icon in dropdowns throughout frontend

---

api/zanata-common-api/src/main/java/org/zanata/rest/dto/LanguageTeamSearchResult.java
server/zanata-frontend/src/frontend/app/containers/Languages/Entry.js
server/zanata-war/src/main/java/org/zanata/rest/service/LocalesService.java
server/zanata-war/src/main/java/org/zanata/service/LocaleService.java
server/zanata-war/src/main/java/org/zanata/service/RequestService.java
server/zanata-war/src/test/java/org/zanata/rest/service/LocalesServiceTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1762
Add the request count to the languages list to indicate outstanding requests.
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-depen …

fix(ZNTA-1762): Add request count to languages list

---

server/zanata-frontend/src/frontend/app/components/Notification/component.js
server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2148
Fixed vertical alignment of icon next to notification modal heading so they are aligned
I also noticed a bug where the correct styling was not being applied to the warning notification modal. It was using the danger styling so I updated the component. You can see the result in storybook: 
- Code quality …

fix(ZNTA-2148): css fixes to frontend notification modal

---

server/gwt-editor/src/test/java/org/zanata/webtrans/client/history/HistoryTokenTest.java
server/gwt-shared/src/test/java/org/zanata/webtrans/shared/validation/HtmlXmlTagValidationTest.java
server/gwt-shared/src/test/java/org/zanata/webtrans/shared/validation/NewlineLeadTrailValidationTest.java
server/gwt-shared/src/test/java/org/zanata/webtrans/shared/validation/XMLEntityValidationTest.java

This helps to avoid problems with detection of test classes.
Related to https://github.com/zanata/zanata-platform/pull/425
- Code quality
- Testing
---- …

test: rename *Tests -> *Test

---

Jenkinsfile
api/zanata-common-api/src/main/java/org/zanata/rest/ElemSet.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/FileMappingRuleHandler.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/OptionMismatchChecker.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/TransFileResolver.java
client/zanata-client-commands/src/test/java/org/zanata/client/commands/FileMappingRuleHandlerTest.java
client/zanata-rest-client/src/main/java/org/zanata/rest/client/FileResourceClient.java
client/zanata-rest-client/src/test/java/org/zanata/rest/client/FileResourceClientTest.java

fix: remove java warnings in client and api

---

Jenkinsfile
build-tools/src/test/java/TestJenkinsfile.java

JIRA issue URL:  https://zanata.atlassian.net/browse/ZNTA-2035
Use GitHubCommitStatusSetter to report the status.
- Code quality
- Testing
----
*This …

Use GitHubCommitStatusSetter

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2158
stop words breaking over multiple lines in GWT
This has been requested by translators and is a fix to previous code added to master, otherwise I would be basing off release branch. I need to make another fix to release, so I shall update the code there also in a different branch.
- Code quality
- If code …

fix(ZNTA-2158) stop words breaking over multiple lines in GWT

---

server/services/src/main/java/org/zanata/dao/GlossaryDAO.java
server/services/src/test/java/org/zanata/dao/GlossaryDAOTest.java
server/zanata-frontend/src/frontend/app/actions/glossary-actions.js
server/zanata-frontend/src/frontend/app/components/EditableText/index.js

fix: light color for placeholder
https://zanata.atlassian.net/browse/ZNTA-2131
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#n …

fix: glossary search handle special char

---

Jenkinsfile

fix: reduce threshold for java warnings

---

server/zanata-war/src/main/webapp/resources/assets/css/application.css

https://zanata.atlassian.net/browse/ZNTA-2091
- Code quality
- Testing …

fix: use default scrollbar in gwt editor

---

server/services/src/main/java/org/zanata/dao/AbstractDAOImpl.java
server/services/src/main/java/org/zanata/dao/GlossaryDAO.java
server/services/src/main/java/org/zanata/dao/LocaleDAO.kt
server/services/src/main/java/org/zanata/dao/PersonDAO.java
server/services/src/main/java/org/zanata/dao/ProjectDAO.java
server/services/src/main/java/org/zanata/dao/VersionGroupDAO.java
server/zanata-frontend/src/frontend/app/actions/explore-actions.js

https://zanata.atlassian.net/browse/ZNTA-2129
- Code quality
- Testing …

fix: handles special char for explore search

---

server/functional-test/src/test/java/org/zanata/feature/TransMemoryTest.java
server/functional-test/src/test/java/org/zanata/feature/document/DownloadDocumentTest.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/GlossaryDetailsPresenter.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/KeyShortcutPresenter.java
server/gwt-shared/src/main/java/org/zanata/webtrans/shared/rpc/GetDocumentStats.java
server/services/src/main/java/org/zanata/action/DashboardAction.java
server/services/src/main/java/org/zanata/action/ProjectHome.java
server/services/src/main/java/org/zanata/action/UserSettingsAction.java
server/services/src/main/java/org/zanata/adapter/GettextAdapter.java
server/services/src/main/java/org/zanata/dao/TextFlowTargetHistoryDAO.java
server/services/src/main/java/org/zanata/seam/text/SeamTextParser.java
server/services/src/main/java/org/zanata/service/impl/RequestServiceImpl.java
server/services/src/main/java/org/zanata/service/impl/SecurityServiceImpl.java
server/services/src/main/java/org/zanata/util/QueryBuilder.java
server/services/src/test/java/org/zanata/model/CacheReliabilityTest.java
server/services/src/test/java/org/zanata/service/impl/CopyTransServiceImplParameterizedTest.java
server/services/src/test/java/org/zanata/service/impl/CopyTransServiceImplPerformanceTest.java
server/services/src/test/java/org/zanata/service/impl/CopyTransServiceImplTest.java
server/services/src/test/java/org/zanata/service/impl/TranslationFinderTest.java
server/zanata-model/src/main/java/org/zanata/model/HTextFlow.java
server/zanata-model/src/main/java/org/zanata/model/HTextFlowTarget.java
server/zanata-model/src/main/java/org/zanata/model/Request.java
server/zanata-model/src/main/java/org/zanata/model/WebHook.java
server/zanata-war/src/test/java/org/zanata/rest/service/raw/GlossaryRawRestITCase.java

fix: remove unused method and imports

---

Jenkinsfile
server/services/src/main/java/org/zanata/action/CopyTransAction.java
server/services/src/main/java/org/zanata/action/ProjectHomeAction.java
server/services/src/main/java/org/zanata/action/VersionGroupHome.java
server/services/src/main/java/org/zanata/action/VersionHome.java
server/services/src/main/java/org/zanata/action/VersionHomeAction.java
server/services/src/main/java/org/zanata/dao/GlossaryDAO.java
server/services/src/main/java/org/zanata/liquibase/custom/ChangePositionalResIdToContentHash.java
server/services/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java
server/services/src/main/java/org/zanata/liquibase/custom/MigrateSeamTextToCommonMark.java
server/services/src/main/java/org/zanata/liquibase/custom/ValidateAccountPasswords.java
server/services/src/main/java/org/zanata/rest/service/ProjectIterationService.java
server/services/src/main/java/org/zanata/rest/service/ResourceUtils.java
server/services/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java
server/services/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java
server/zanata-model/src/main/java/org/zanata/hibernate/search/AbstractFieldBridge.java

fix: remove deprecation warnings:

---

server/services/src/main/java/org/zanata/action/LanguageAction.java
server/services/src/main/java/org/zanata/action/ProjectPermissionDialog.java
server/services/src/main/java/org/zanata/dao/AccountDAO.java
server/services/src/main/java/org/zanata/dao/PersonDAO.java
server/services/src/main/java/org/zanata/rest/editor/service/UserService.java
server/services/src/main/java/org/zanata/rest/search/service/SearchService.java
server/services/src/main/java/org/zanata/ui/autocomplete/MaintainerAutocomplete.java
server/services/src/test/java/org/zanata/dao/PersonDAOTest.java
server/services/src/test/java/org/zanata/rest/editor/service/UserServiceTest.java
server/zanata-frontend/src/frontend/app/containers/UserProfile/index.jsx
server/zanata-frontend/src/frontend/app/reducers/profile-reducer.js
server/zanata-model-test/src/main/resources/org/zanata/test/model/AccountData.dbunit.xml

https://zanata.atlassian.net/browse/ZNTA-2172
- Code quality
- Testing
---- …

fix: do not display profile of inactive account

---

api/zanata-common-api/src/main/java/org/zanata/rest/service/StatisticsResource.java
client/stub-server/src/main/java/org/zanata/rest/service/MockStatisticsResource.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/stats/GetStatisticsCommand.java
client/zanata-rest-client/src/main/java/org/zanata/rest/client/StatisticsResourceClient.java
server/services/src/main/java/org/zanata/rest/service/StatisticsServiceImpl.java

https://zanata.atlassian.net/browse/ZNTA-234
- Code quality
- Testing …

fix: update stats endpoint for docId

---

server/services/src/main/java/org/zanata/security/UsernameLoggingFilter.java

This seems to have been broken ever since Zanata 3.9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/488)

Use SLF4J MDC, not Log4j

---

server/zanata-war/src/main/webapp/resources/assets/css/application.css

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2168
increase contrast between active and inactive translation panels in GWT
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencie …

fix(ZNTA-2168): GWT panel contrast

---

server/pom.xml
server/services/pom.xml
server/services/src/test/java/ServicesITCases.kt
server/services/src/test/java/ServicesUTCases.kt
server/zanata-war/pom.xml
server/zanata-war/src/test/java/ZanataWarITCases.kt
server/zanata-war/src/test/java/ZanataWarUTCases.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/497)

Add wildcard suites for IDEs

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
server/zanata-war/src/main/webapp/iteration/view.xhtml

https://zanata.atlassian.net/browse/ZNTA-2187
- Code quality
- Testing …

fix: put prefix for document id element

---

Jenkinsfile

chore: update threshold for java warnings

---

api/zanata-common-api/src/main/java/org/zanata/rest/service/LocalesResource.java

fix: Locales resource annotation

---

server/zanata-frontend/src/frontend/.yarnrc
server/zanata-frontend/src/frontend/makefile
server/zanata-frontend/src/frontend/package.json
server/zanata-frontend/src/frontend/yarn.lock

JIRA issue URL: no JIRA
`yarn` or `yarn install` will now fail after adding a dependency with `npm install --save`. Dependencies should only be added with `yarn add`.
The failure looks like this:
```
[damason@sprout frontend]$ npm install --save foo
...
[damason@sprout frontend]$ yarn
yarn install v0.27.5
[1/4] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
The fix is to run:
```
$ yarn add foo
```
this will correctly update both `yarn.lock` and `package.json`
As a reviewer, you should check the guidelines …

Enforce keeping yarn.lock and package.json in sync

---

server/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/512)

Update Kotlin to 1.1.4-3

---

Jenkinsfile
build-tools/src/test/java/TestJenkinsfile.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2182
This requires https://github.com/zanata/zanata-pipeline-library/pull/3
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies …

test: update for pipeline-library ZNTA-2182

---

server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java

fix: functional test

---

server/pom.xml
server/services/src/test/java/org/zanata/security/permission/PermissionEvaluatorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/520)

Upgrade to cdi-unit 4.0.0

---

Jenkinsfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/521)

Show agent names in build name

---

server/services/src/main/java/org/zanata/action/ServerConfigurationBean.java
server/services/src/test/java/org/zanata/config/DatabaseBackedConfigTest.java
server/zanata-model-test/src/main/resources/org/zanata/test/model/ApplicationConfigurationData.dbunit.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2206
Help link on More page of Zanata frontend pointed to old help page on zanata.org which does not exist anymore with the new website. The link has been updated to point to readthedocs
- Code quality
- Testing …

fix(ZNTA-2206) Help link now points to docs.zanata.org

---

server/zanata-frontend/src/frontend/app/actions/glossary-actions.js

https://zanata.atlassian.net/browse/ZNTA-2208
- Code quality
- Testing …

fix: glossary upload

---

server/zanata-frontend/src/frontend/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2220
Change overflow rule on modal-content class
- Code quality
- Testing
----
*This template can …

fix(ZNTA-2220) remove scrollbars from modals that don't need scrolling

---

server/gwt-shared/src/main/java/org/zanata/webtrans/shared/rest/dto/InternalTMSource.java

https://zanata.atlassian.net/browse/ZNTA-2218:
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-dependencies …

fix: TM serializable issue

---

server/gwt-editor/pom.xml
server/pom.xml
server/zanata-test-war/pom.xml
server/zanata-test-war/src/main/java/org/zanata/rest/RemoteTestSignalerImpl.java
server/zanata-test-war/src/main/java/org/zanata/test/SessionChecker.kt
server/zanata-test-war/src/main/java/org/zanata/test/SessionTracker.kt
server/zanata-war/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/514)

test: check session size/serializability

---

server/gwt-editor/pom.xml
server/zanata-war/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/535)

Fix test dependency

---

Jenkinsfile
server/services/src/main/java/org/zanata/database/ConnectionWrapper.java
server/services/src/main/java/org/zanata/database/ProxyUtil.java
server/services/src/main/java/org/zanata/database/ResultSetWrapper.java
server/services/src/main/java/org/zanata/database/StatementWrapper.java
server/services/src/main/java/org/zanata/seam/framework/EntityHome.java
server/services/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java
server/services/src/main/java/org/zanata/seam/text/SeamTextParser.java
server/services/src/main/java/org/zanata/service/impl/ActivityServiceImpl.java
server/services/src/main/java/org/zanata/service/impl/GlossarySearchServiceImpl.java
server/services/src/main/java/org/zanata/service/impl/TranslationMemoryServiceImpl.java
server/services/src/main/java/org/zanata/transaction/TransactionUtil.java
server/services/src/test/java/org/zanata/ZanataDbunitJpaTest.java
server/services/src/test/java/org/zanata/adapter/JsonAdapterTest.java
server/services/src/test/java/org/zanata/adapter/TSAdapterTest.java
server/services/src/test/java/org/zanata/dao/TextFlowTargetDAOTest.java
server/services/src/test/java/org/zanata/model/CacheReliabilityTest.java
server/services/src/test/java/org/zanata/rest/service/StatisticsServiceImplTest.java
server/services/src/test/java/org/zanata/rest/service/raw/AnonAccessAlt.java
server/services/src/test/java/org/zanata/rest/service/raw/OAuthAlt.java
server/services/src/test/java/org/zanata/service/impl/GlossaryUrlTest.java
server/services/src/test/java/org/zanata/service/impl/TransMemoryMergeServiceImplTest.java
server/services/src/test/java/org/zanata/transaction/TransactionUtilForUnitTest.java
server/services/src/test/java/org/zanata/webtrans/server/rpc/GetGlossaryHandlerJpaTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/537)

Reduce compiler warnings

---

server/functional-test/pom.xml
server/pom.xml
server/services/pom.xml
server/services/src/test/java/org/zanata/rest/service/raw/ArquillianRest.kt
server/zanata-model-test/pom.xml
server/zanata-model/pom.xml
server/zanata-war/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/546)

Update Kotlin to 1.1.51

---

Jenkinsfile
build-tools/src/test/java/TestJenkinsfile.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2201
See also zanata/zanata-pipeline-library#4
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-techn …

ZNTA-2201-correctSHA

---

server/functional-test/src/main/java/org/zanata/page/account/ProfilePage.java
server/zanata-frontend/src/frontend/app/containers/Languages/index.js
server/zanata-frontend/src/frontend/app/containers/Languages/index.less
server/zanata-frontend/src/frontend/app/containers/UserProfile/index.jsx
server/zanata-frontend/src/frontend/app/containers/UserProfile/index.less

self-explanatory, fixes master
- Code quality
- Testing
----
--- …

fix: add IDs to fix functional tests

---

server/zanata-frontend/src/frontend/makefile
server/zanata-frontend/src/frontend/package.json
server/zanata-frontend/src/frontend/yarn.lock

https://zanata.atlassian.net/browse/ZNTA-1485
- Code quality
- Testing …

chore: remove fake-server dependency

---

server/docker/Dockerfile

*The Wildfly docker container throws error WFLYCTL0056 when starting up. Add a line to prevent this from happening.*
- Code quality
- Testing
----
*This …

fix: WFLYCTL0056 error when starting docker wildfly container

---

server/zanata-frontend/src/frontend/app/styles/style.less

add css class for italic text to style.less - **u-textItalic** 
- Code quality
- Testing
---- …

fix: ZNTA - add italic-class

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

https://zanata.atlassian.net/browse/ZNTA-1952
- Code quality
- Testing …

doc: Update PR template

---

docs/release-notes.md
docs/user-guide/system-admin/configuration/installation.md
server/docker/conf/zanata-config.cli
server/etc/scripts/zanata-config-test-common.cli
server/services/src/main/java/org/zanata/config/SystemPropertyConfigStore.java
server/services/src/main/java/org/zanata/file/FileSystemPersistService.java
server/services/src/main/java/org/zanata/log4j/ZanataSMTPAppender.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2225
- add system property zanata.home as a root for all storage related properties
- Code quality
- Testing
[Considerations for new dependencies](https://github.com/zanata/zanata-platform/wiki/Development-Guidelines#new-technologies-and-depe …

ZNTA-2225 - define java.home sys prop

---

Jenkinsfile
parent/pom.xml
server/pom.xml

Designed to go with https://github.com/zanata/zanata-platform/pull/562
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/564)

Add staticAnalysisCI profile

---

server/pom.xml
server/services/src/main/java/org/zanata/util/CommonMarkRenderer.java
server/services/src/test/java/org/zanata/util/CommonMarkRendererTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/553)

Avoid direct dependency on Nashorn classes

---

server/zanata-frontend/src/frontend/app/containers/Languages/index.js

https://zanata.atlassian.net/browse/ZNTA-2130
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/567)

fix: display no results message

---

server/zanata-frontend/src/frontend/app/containers/Glossary/index.less
server/zanata-frontend/src/frontend/app/containers/Languages/index.js
server/zanata-frontend/src/frontend/app/containers/UserProfile/index.jsx
server/zanata-frontend/src/frontend/app/containers/UserProfile/index.less
server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css
server/zanata-frontend/src/frontend/app/editor/containers/Sidebar/index.css
server/zanata-frontend/src/frontend/app/styles/gwt.less
server/zanata-frontend/src/frontend/app/styles/style.less
server/zanata-frontend/src/frontend/app/styles/variables.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2212
*Improvements*
* minor fixes to editor layout (sidebar border)
* removed zanata icon from minimised alpha editor header
* gwt fixes - button links, administration pages, other minor css fixes to frontend
* made popovers and tooltips consistent throughout reactJS pages in frontend
* minor fixes to glossary layout and TM Merge Modal (css)
* fix alignment of 'Clear selection' button on User Profile
* button heights now consistent, have box borders, minor css tweaks
* increased width of Languages page to 100% like other pages (excluding Explore)
As a reviewer, you should check the guidelines …

ZNTA-2212: improve css consistency in frontend

---

server/zanata-frontend/src/frontend/app/styles/gwt.less
server/zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-2232*
- Code quality
- Testing
----
*This …

ZNATA-2232 Upload source document '+' icon.

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/OptionsUtil.java
client/zanata-client-commands/src/test/java/org/zanata/client/commands/HTTPMockContainer.java
client/zanata-client-commands/src/test/java/org/zanata/client/commands/push/PushCommandTest.java

https://zanata.atlassian.net/browse/ZNTA-1327
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/570)

fix:allow pull without zanata.xml

---

server/services/src/main/resources/messages.properties

https://zanata.atlassian.net/browse/ZNTA-1975
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/574)

fix: new window for commonmark ref

---

server/services/src/main/java/org/zanata/rest/service/StatisticsServiceImpl.java
server/services/src/test/java/org/zanata/rest/service/StatisticsServiceImplTest.java
server/zanata-frontend/src/frontend/app/reducers/glossary-reducer.js

https://zanata.atlassian.net/browse/ZNTA-2174
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/572)

fix: security check for private project in zanata-cli

---

server/services/src/main/java/org/zanata/service/SearchIndexManager.java
server/zanata-model/src/main/java/org/zanata/model/HGlossaryEntry.java
server/zanata-model/src/main/java/org/zanata/model/HProjectIteration.java
server/zanata-test-war/src/main/java/org/zanata/util/SampleDataProfile.java

https://zanata.atlassian.net/browse/ZNTA-2197
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/576)

fix(ZNTA-2197): remove unused indexed annotation

---

server/services/src/main/java/org/zanata/file/DocumentUploadUtil.java
server/services/src/main/java/org/zanata/rest/service/FileService.java
server/services/src/test/java/org/zanata/file/DocumentUploadTest.java
server/services/src/test/java/org/zanata/file/DocumentUploadUtilTest.java
server/services/src/test/java/org/zanata/rest/service/FileServiceTest.java

https://zanata.atlassian.net/browse/ZNTA-2174
Add restriction in file service end point
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/579)

fix: permission check for file project type download

---

server/zanata-frontend/src/frontend/app/editor/index.js

https://zanata.atlassian.net/browse/ZNTA-1790
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/581)

fix: support context path for alpha editor

---

server/gwt-shared/src/main/java/org/zanata/webtrans/shared/validation/action/PrintfXSIExtensionValidation.java
server/gwt-shared/src/test/java/org/zanata/webtrans/shared/validation/PrintfXSIExtensionValidationTest.java

https://zanata.atlassian.net/browse/ZNTA-2238
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/586)

fix: printf validation

---

server/zanata-war/src/main/webapp/account/register.xhtml
server/zanata-war/src/main/webapp/admin/create_user.xhtml

https://zanata.atlassian.net/browse/ZNTA-1991
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/591)

fix: username validation

---

server/services/src/main/java/org/zanata/action/ProjectHome.java

https://zanata.atlassian.net/browse/ZNTA-1976
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/590)

fix: avoid validation warning when project id has not changed

---

api/zanata-common-api/src/main/java/org/zanata/rest/service/TranslationMemoryResource.java

https://zanata.atlassian.net/browse/ZNTA-897
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/593)

doc: improve api doc for tm resource

---

server/services/src/main/java/org/zanata/action/LoginAction.java
server/services/src/main/java/org/zanata/util/UrlUtil.java
server/services/src/test/java/org/zanata/action/LoginActionTest.java
server/services/src/test/java/org/zanata/util/UrlUtilTest.java
server/zanata-war/src/main/webapp/WEB-INF/faces-config.xml
server/zanata-war/src/main/webapp/account/login.xhtml
server/zanata-war/src/main/webapp/account/singleopenidlogin.xhtml

- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/595)

fix: prevent logged in user in sign_in page

---

api/zanata-common-api/pom.xml
build
build-tools/pom.xml
client/stub-server/pom.xml
client/zanata-cli/pom.xml
client/zanata-client-commands/pom.xml
client/zanata-maven-plugin/pom.xml
client/zanata-rest-client/pom.xml
common/zanata-adapter-glossary/pom.xml
common/zanata-adapter-po/pom.xml
common/zanata-adapter-properties/pom.xml
common/zanata-adapter-xliff/pom.xml
common/zanata-common-util/pom.xml
parent/pom.xml
server/functional-test/pom.xml
server/gwt-shared/pom.xml
server/gwt-test/pom.xml
server/pom.xml
server/security-common/pom.xml
server/services/pom.xml
server/zanata-frontend/pom.xml
server/zanata-liquibase/pom.xml
server/zanata-model-test/pom.xml
server/zanata-model/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/601)

Remove takari-lifecycle-plugin

---

Jenkinsfile
build-tools/pom.xml
build-tools/src/test/java/TestJenkinsfile.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2234
Pipeline library: zanata/zanata-pipeline-library#4
openprops:  zanata/openprops#6
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/571)

fix(ZNTA-2234): Correct the codecov URL

---

server/zanata-frontend/src/frontend/scripts/build.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/602)

Fix colour contrast for console

---

server/services/src/main/java/org/zanata/action/LoginAction.java
server/services/src/main/java/org/zanata/util/FacesNavigationUtil.java
server/services/src/main/java/org/zanata/util/UrlUtil.java
server/services/src/test/java/org/zanata/action/LoginActionTest.java

https://zanata.atlassian.net/browse/ZNTA-2055
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/603)

fix: login redirect with url issue (exposing port)

---

server/zanata-frontend/src/frontend/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
server/zanata-frontend/src/frontend/package.json
server/zanata-frontend/src/frontend/webpack.config.js
server/zanata-frontend/src/frontend/yarn.lock

https://zanata.atlassian.net/browse/ZNTA-2261
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/606)

fix: failed story-book watch

---

server/zanata-frontend/pom.xml
server/zanata-frontend/src/frontend/scripts/build.js

JIRA issues: https://zanata.atlassian.net/browse/ZNTA-2256 and https://zanata.atlassian.net/browse/ZNTA-2266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/608)

fix(ZNTA-2256, ZNTA-2266) fail build for JS errors

---

.mvn/wrapper/maven-wrapper.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/605)

Update Maven to 3.5.2

---

api/zanata-common-api/src/main/java/org/zanata/common/IssuePriority.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/gin/WebTransClientModule.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/ForceReviewCommentPresenter.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenter.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/ReviewCommentInputWidget.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/ForceReviewCommentDisplay.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/ForceReviewCommentWidget.java
server/gwt-editor/src/test/java/org/zanata/webtrans/client/presenter/ForceReviewCommentPresenterTest.java
server/gwt-editor/src/test/java/org/zanata/webtrans/client/presenter/TransMemoryMergePresenterTest.java
server/gwt-editor/src/test/java/org/zanata/webtrans/client/presenter/TranslationHistoryPresenterTest.java
server/gwt-shared/src/main/java/org/zanata/webtrans/shared/model/ReviewComment.java
server/gwt-shared/src/main/java/org/zanata/webtrans/shared/model/ReviewCriterionId.java
server/gwt-shared/src/main/java/org/zanata/webtrans/shared/model/UserWorkspaceContext.java
server/gwt-shared/src/main/java/org/zanata/webtrans/shared/rest/dto/TransReviewCriteria.java
server/gwt-shared/src/main/java/org/zanata/webtrans/shared/rpc/AddReviewCommentAction.java
server/gwt-test/src/main/java/org/zanata/webtrans/test/GWTTestData.java
server/services/src/main/java/org/zanata/dao/ReviewCriteriaDAO.kt
server/services/src/main/java/org/zanata/rest/review/ReviewService.java
server/services/src/main/java/org/zanata/webtrans/server/rpc/ActivateWorkspaceHandler.java
server/services/src/main/java/org/zanata/webtrans/server/rpc/AddReviewCommentHandler.java
server/services/src/main/java/org/zanata/webtrans/server/rpc/GetTranslationHistoryHandler.java
server/services/src/main/resources/db/changelogs/db.changelog-4.4.xml
server/services/src/test/java/org/zanata/rest/review/ReviewServiceTest.java
server/services/src/test/java/org/zanata/webtrans/server/rpc/ActivateWorkspaceHandlerTest.java
server/services/src/test/java/org/zanata/webtrans/server/rpc/AddReviewCommentHandlerTest.java
server/services/src/test/java/org/zanata/webtrans/server/rpc/GetTranslationHistoryHandlerTest.java
server/zanata-model/src/main/java/org/zanata/model/HTextFlowTarget.java
server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetHistory.java
server/zanata-model/src/main/java/org/zanata/model/HTextFlowTargetReviewComment.java
server/zanata-model/src/main/java/org/zanata/model/ReviewCriteria.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2215
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/604)

ZNTA-2215 - review criteria in gwt editor

---

client/stub-server/src/main/java/org/zanata/rest/service/MockAccountResource.java
client/stub-server/src/main/java/org/zanata/rest/service/MockAsynchronousProcessResource.java
client/stub-server/src/main/java/org/zanata/rest/service/MockCopyTransResource.java
client/stub-server/src/main/java/org/zanata/rest/service/MockFileResource.java
client/stub-server/src/main/java/org/zanata/rest/service/MockGlossaryResource.java
client/stub-server/src/main/java/org/zanata/rest/service/MockProjectIterationResource.java

https://zanata.atlassian.net/browse/ZNTA-2272
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/610)

fix: remove unused serialVersionUID

---

server/services/src/main/java/org/zanata/rest/service/AsyncProcessService.java
server/services/src/main/java/org/zanata/rest/service/ProjectVersionService.java
server/services/src/main/java/org/zanata/util/HttpUtil.java
server/services/src/test/java/org/zanata/util/HttpUtilTest.java
server/zanata-frontend/src/frontend/app/containers/ProjectVersion/TMMergeModal.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2271
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/609)

ZNTA-2271 - make sure protocol is consistent

---

server/gwt-shared/src/main/java/org/zanata/webtrans/shared/validation/action/PrintfXSIExtensionValidation.java
server/gwt-shared/src/test/java/org/zanata/webtrans/shared/validation/PrintfXSIExtensionValidationTest.java

https://zanata.atlassian.net/browse/ZNTA-2238
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/611)

fix: printf positional variables

---

Jenkinsfile
build-tools/src/test/java/TestJenkinsfile.java

Jenkins2 Upgrade
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/613)

feat(ZNTA-2270): custom context

---

server/functional-test/src/main/java/org/zanata/page/account/ProfilePage.java
server/functional-test/src/main/java/org/zanata/page/administration/AddLanguagePage.java
server/functional-test/src/main/java/org/zanata/page/administration/ManageSearchPage.java
server/functional-test/src/main/java/org/zanata/page/dashboard/DashboardActivityTab.java
server/functional-test/src/main/java/org/zanata/page/editor/ReactEditorPage.java
server/functional-test/src/main/java/org/zanata/page/groups/CreateVersionGroupPage.java
server/functional-test/src/main/java/org/zanata/page/groups/VersionGroupPage.java
server/functional-test/src/main/java/org/zanata/page/languages/LanguagePage.java
server/functional-test/src/main/java/org/zanata/page/projects/ProjectPeoplePage.java
server/functional-test/src/main/java/org/zanata/page/projects/ProjectVersionsPage.java
server/functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectLanguagesTab.java
server/functional-test/src/main/java/org/zanata/page/projects/projectsettings/ProjectPermissionsTab.java
server/functional-test/src/main/java/org/zanata/page/projectversion/CreateVersionPage.java
server/functional-test/src/main/java/org/zanata/page/projectversion/VersionDocumentsPage.java
server/functional-test/src/main/java/org/zanata/page/projectversion/VersionLanguagesPage.java
server/functional-test/src/main/java/org/zanata/page/projectversion/versionsettings/VersionDocumentsTab.java
server/functional-test/src/main/java/org/zanata/page/projectversion/versionsettings/VersionLanguagesTab.java
server/functional-test/src/main/java/org/zanata/page/webtrans/EditorPage.java
server/functional-test/src/main/java/org/zanata/workflow/AbstractWebWorkFlow.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2280
Add withMessage to the waitForAMoment action in functional tests.
Also cleans up several of those functions.
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/616)

fix(ZNTA-2280): Add messages to waitFor actions in functional test

---

server/zanata-frontend/src/frontend/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
server/zanata-frontend/src/frontend/app/styles/gwt.less

Fix the following issue
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/619)

fix: project heading length

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransUnitNavigationView.java
server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/TransUnitNavigationView.ui.xml

https://zanata.atlassian.net/browse/ZNTA-15
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/618)

fix: nav button styling in editor

---

Jenkinsfile
server/pom.xml
server/zanata-model/src/main/java/org/zanata/model/HLocale.kt

https://blog.jetbrains.com/kotlin/2017/11/kotlin-1-2-released/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/620)

Update to Kotlin 1.2.0

---

server/zanata-frontend/src/frontend/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
server/zanata-frontend/src/frontend/app/components/Sidebar/Sidebar.story.js
server/zanata-frontend/src/frontend/app/components/Sidebar/index.jsx
server/zanata-frontend/src/frontend/app/containers/ProjectVersion/AboutPage.js
server/zanata-frontend/src/frontend/app/containers/ProjectVersion/index.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1695
Create AboutPage component for new Project Version section.
Created props for the project description, a URL and the URL name.
I put the AboutPage.js and it's small bit of css under /containers/ProjectVersion. I didn't think keeping it with the Sidebar Component was the best place for it.
- JIRA link
----
--- …

feat(ZNTA-1695) add container for ProjectVersion AboutPage

---

common/pom.xml
server/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/627)

Update to jgettext 0.15

---

server/zanata-frontend/src/frontend/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
server/zanata-frontend/src/frontend/app/components/Sidebar/Sidebar.story.js
server/zanata-frontend/src/frontend/app/components/Sidebar/index.jsx
server/zanata-frontend/src/frontend/app/containers/ProjectVersion/PeoplePage.js
server/zanata-frontend/src/frontend/app/containers/ProjectVersion/index.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1694
Storybook - ProjectVersion People page (see Sidebar story in storybook-frontend)
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/628)

ZNTA-1694: storybook: ProjVersion People page

---

server/zanata-war/src/main/webapp/resources/zanata/multi-file-upload.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2305
Fix alignment of Upload Documents button in Upload new documents Modal
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/631)

fix(ZNTA-2305): alignment of footer in Upload new document modal

---

parent/pom.xml
server/functional-test/pom.xml
server/functional-test/src/main/java/org/zanata/workflow/ClientWorkFlow.java
server/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/600)

Update Guava and browsermob-proxy

---

server/docker/Dockerfile
server/docker/conf/zanata-config.cli
server/etc/scripts/zanata-config-arq-test.cli
server/etc/scripts/zanata-config-test-common.cli
server/functional-test/pom.xml
server/functional-test/src/test/resources/readme.txt
server/pom.xml
server/services/src/main/java/org/zanata/ApplicationConfiguration.java
server/services/src/main/java/org/zanata/action/HomePage.java
server/services/src/main/java/org/zanata/cache/CacheManagerProducer.java
server/services/src/main/java/org/zanata/config/JaasConfig.java
server/services/src/main/java/org/zanata/rest/ZanataRestResponseInterceptor.java
server/services/src/main/resources/ehcache.xml
server/services/src/test/resources/arquillian.xml
server/zanata-war/src/main/webapp-jboss/WEB-INF/web.xml
server/zanata-war/src/test/resources/arquillian.xml
server/zanata-war/src/test/resources/arquillian/test-web.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/612)

Mark app distributable; use Infinispan for HomePage

---

build
server/functional-test/pom.xml
server/pom.xml
server/services/pom.xml
server/zanata-war/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/632)

Update to JBoss EAP 7.1

---

Jenkinsfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/634)

Disable StabilityTestDataPublisher

---

server/zanata-frontend/src/frontend/package.json
server/zanata-frontend/src/frontend/yarn.lock

https://zanata.atlassian.net/browse/ZNTA-2317
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/641)

chore: update css-loader version

---

README.md

- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/642)

doc: add commit message format in readme

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/push/AbstractCommonPushStrategy.java
client/zanata-client-commands/src/test/java/org/zanata/client/commands/push/XmlStrategyTest.java

https://zanata.atlassian.net/browse/ZNTA-166
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/644)

fix: exclude file without basename

---

server/services/src/main/java/org/zanata/dao/AccountDAO.java
server/services/src/test/java/org/zanata/dao/AccountDAOTest.java

https://zanata.atlassian.net/browse/ZNTA-1325
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/645)

fix: update API key generation

---

server/services/src/main/java/org/zanata/ApplicationConfiguration.java
server/services/src/main/java/org/zanata/rest/JaxRSApplication.java
server/services/src/main/java/org/zanata/rest/review/ReviewService.java
server/services/src/main/java/org/zanata/rest/service/AccountService.java
server/services/src/main/java/org/zanata/rest/service/AsyncProcessService.java
server/services/src/main/java/org/zanata/rest/service/ProjectService.java
server/services/src/main/java/org/zanata/rest/service/ProjectVersionService.java
server/services/src/main/java/org/zanata/rest/service/SourceDocResourceService.java
server/services/src/main/java/org/zanata/rest/service/TranslatedDocResourceService.java
server/services/src/main/java/org/zanata/util/UrlUtil.java
server/services/src/test/java/org/zanata/rest/review/ReviewServiceTest.java
server/services/src/test/java/org/zanata/rest/service/ProjectVersionServiceUnitTest.java
server/services/src/test/java/org/zanata/util/UrlUtilTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2273
REST resources returning absolute path needs to use configured server url because Zanata might be running behind a proxy.
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/643)

ZNTA-2273 - REST resources returning absolute path 

---

server/pom.xml
server/services/src/main/java/org/zanata/action/HasUserDetail.java
server/services/src/main/java/org/zanata/action/InactiveAccountAction.java
server/services/src/main/java/org/zanata/action/ServerConfigurationBean.java
server/services/src/main/java/org/zanata/action/UserSettingsAction.java
server/services/src/main/java/org/zanata/action/validator/EmailListValidator.java
server/zanata-model/pom.xml
server/zanata-model/src/main/java/org/zanata/model/validator/ZanataEmail.java
server/zanata-model/src/main/java/org/zanata/model/validator/ZanataEmailValidator.java
server/zanata-model/src/test/java/org/zanata/model/validator/ZanataEmailValidatorTest.java

https://zanata.atlassian.net/browse/ZNTA-1375
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/650)

fix: use apache email validator

---

client/zanata-cli/src/main/java/org/zanata/client/ZanataClient.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/BasicOptions.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/BasicOptionsImpl.java
client/zanata-client-commands/src/main/java/org/zanata/client/commands/OptionsUtil.java
client/zanata-client-commands/src/test/java/org/zanata/client/commands/OptionsUtilTest.java
client/zanata-maven-plugin/src/main/java/org/zanata/maven/ConfigurableMojo.java

https://zanata.atlassian.net/browse/ZNTA-1117
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/649)

fix: zanata-cli basic options positioning

---

server/pom.xml

https://zanata.atlassian.net/browse/ZNTA-1570
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/651)

chore: remove jboss maven repo

---

server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt
server/functional-test/src/main/java/org/zanata/page/CorePage.java
server/functional-test/src/main/java/org/zanata/page/administration/AddLanguagePage.java
server/functional-test/src/main/java/org/zanata/page/administration/AdministrationPage.java
server/functional-test/src/main/java/org/zanata/page/administration/CreateUserAccountPage.java
server/functional-test/src/main/java/org/zanata/page/administration/EditHomeContentPage.java
server/functional-test/src/main/java/org/zanata/page/administration/EditRoleAssignmentPage.java
server/functional-test/src/main/java/org/zanata/page/administration/ManageSearchPage.java
server/functional-test/src/main/java/org/zanata/page/administration/ManageUserAccountPage.java
server/functional-test/src/main/java/org/zanata/page/administration/ManageUserPage.java
server/functional-test/src/main/java/org/zanata/page/administration/RoleAssignmentsPage.java
server/functional-test/src/main/java/org/zanata/page/administration/ServerConfigurationPage.java
server/functional-test/src/main/java/org/zanata/page/administration/TranslationMemoryEditPage.java
server/functional-test/src/main/java/org/zanata/page/administration/TranslationMemoryPage.java
server/functional-test/src/main/java/org/zanata/workflow/TranslationMemoryWorkFlow.java
server/functional-test/src/test/java/org/zanata/feature/administration/AutoRoleAssignmentTest.java
server/functional-test/src/test/java/org/zanata/feature/administration/EditHomePageTest.java
server/functional-test/src/test/java/org/zanata/feature/administration/EditTranslationMemoryTest.java
server/functional-test/src/test/java/org/zanata/feature/administration/ManageSearchTest.java
server/functional-test/src/test/java/org/zanata/feature/administration/ManageUsersTest.java
server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java
server/functional-test/src/test/java/org/zanata/feature/endtoend/AdminEndToEndTest.java
server/zanata-war/src/main/webapp/admin/search.xhtml
server/zanata-war/src/main/webapp/tm/home.xhtml

Improve and document functional tests and pages
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/629)

fix(test): Audit administration functional tests

---

server/zanata-frontend/src/frontend/app/editor/app.css
server/zanata-frontend/src/frontend/app/editor/containers/Root/index.css

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2327
Isolate editor highlight styling so it does not affect frontend
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/654)

fix(ZNTA-2327) isolated highlight styling to Editor

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/request_join_modal.xhtml

https://zanata.atlassian.net/browse/ZNTA-2345
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/668)

fix: request version group button

---

server/zanata-war/src/main/webapp/resources/assets/css/application.css

https://zanata.atlassian.net/browse/ZNTA-2344
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/671)

fix: GWT editor font size

---

server/services/src/main/java/org/zanata/security/AnonymousAccessControlPhaseListener.java
server/services/src/main/java/org/zanata/security/UserRedirectBean.java
server/services/src/main/java/org/zanata/servlet/UrlRewriteConfig.java
server/services/src/test/java/org/zanata/security/AnonymousAccessControlPhaseListenerTest.java
server/zanata-war/src/main/webapp/error/404.xhtml
server/zanata-war/src/main/webapp/error/home.xhtml
server/zanata-war/src/main/webapp/error/missing_entity.xhtml
server/zanata-war/src/main/webapp/error/viewexpiredexception.xhtml

https://zanata.atlassian.net/browse/ZNTA-2332
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/661)

fix: handle redirect of error pages

---

server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/settings.xhtml

Increase rows in Settings (client_settings_config) so that scrollbar isn't visible
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2348
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/669)

fix(ZNTA-2348) increase rows in Settings (client_settings_config)

---

server/zanata-frontend/src/app/editor/components/FilterToggle/index.css
server/zanata-frontend/src/app/editor/components/FilterToggle/index.js
server/zanata-frontend/src/app/editor/components/PhraseStatusFilter/PhraseStatusFilter.test.js
server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/settings.xhtml

fix merge conflicts in FilterToggle due to move of frontend dir
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/673)

merge release into master

---

server/functional-test/src/test/java/org/zanata/feature/endtoend/AdminEndToEndTest.java

JIRA issue URL: na
Workaround a flaky Admin E2E test. Further investigation required.
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/676)

Workaround for flaky E2E test

---

server/zanata-frontend/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/675)

Ensure JS tests can fail the build

---

server/services/src/main/java/org/zanata/action/UserSettingsAction.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2353
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/674)

fix(ZNTA-2353): remove broken injection

---

server/zanata-war/src/main/webapp/resources/assets/css/style.css

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2362
Right align dates on TM page under Admin
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/677)

fix(ZNTA-2362) right align dates on Admin - Translation Memory

---

server/zanata-model/src/main/java/org/zanata/model/ReviewCriteria.java

- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/684)

Fix merge conflicts

---

server/zanata-frontend/src/app/editor/components/FilterToggle/index.css

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2339
remove padding added in error
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/689)

fix(ZNTA-2339) fix filter toggles in editor

---

server/services/src/main/java/org/zanata/security/AuthenticationManager.java
server/services/src/main/java/org/zanata/security/SamlAccountService.kt
server/services/src/main/java/org/zanata/servlet/SAMLFilter.kt
server/services/src/test/java/org/zanata/security/AuthenticationManagerTest.kt
server/services/src/test/java/org/zanata/servlet/SAMLFilterTest.kt

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2374
To test:
- having an account in your system that uses your redhat email (registered as internal authentication)
- sign in using SSO
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/697)

ZNTA-2374 sso with existing account can sign in on first time

---

server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
server/zanata-frontend/src/app/components/Sidebar/Sidebar.story.js
server/zanata-frontend/src/app/containers/ProjectVersion/GroupsPage.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1700
Add Groups ProjectVersion page story to frontend
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/699)

feat(ZNTA-1700): Groups ProjectVersion page story

---

server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
server/zanata-frontend/src/app/components/Sidebar/Sidebar.story.js
server/zanata-frontend/src/app/components/Sidebar/index.less
server/zanata-frontend/src/app/containers/ProjectVersion/LanguagesPage.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1698
Run `make storybook-frontend` and view the sidebar stories to see example.
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/700)

feat(ZNTA-1698): ProjectVersion Languages page story

---

server/zanata-frontend/src/.storybook-frontend/__snapshots__/storyshots-frontend.test.js.snap
server/zanata-frontend/src/app/components/Sidebar/Sidebar.story.js
server/zanata-frontend/src/app/containers/ProjectVersion/DocumentsPage.js
server/zanata-frontend/src/app/containers/ProjectVersion/GroupsPage.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1699
feat(ZNTA-1699) add story for Project Version Documents page and update snapshots
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/703)

feat(ZNTA-1699) add story for Project Version Documents page

---

server/services/src/main/java/org/zanata/dao/ProjectDAO.java
server/services/src/test/java/org/zanata/dao/ProjectDAOTest.java

https://zanata.atlassian.net/browse/ZNTA-2375
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/704)

fix: duplicate project result in explore page

---

server/zanata-frontend/src/frontend/app/reducers/version-reducer.js

https://zanata.atlassian.net/browse/ZNTA-2372
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/705)

fix: include server error message in tm merge notification

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml

https://zanata.atlassian.net/browse/ZNTA-2383
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/710)

fix: doc list percentage position

---

server/services/src/main/java/org/zanata/service/impl/TransMemoryMergeServiceImpl.java

- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/711)

fix: merge trans stops before completing

---

server/zanata-war/src/main/webapp/WEB-INF/layout/admin/contact_admin_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/admin/contact_admin_modal_anonymous.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/copy_trans_inline_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/groups.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/projects.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/delete_confirmation_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/contact_coordinator_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/contact_members_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/decline_request_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/request_join_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/language/search_user_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/person-permissions-modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/languages-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/request_join_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/merge_trans_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/upload_translation_modal.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/zip_download_progress_modal.xhtml
server/zanata-war/src/main/webapp/dashboard/home.xhtml
server/zanata-war/src/main/webapp/resources/assets/css/style.css
server/zanata-war/src/main/webapp/resources/zanata/activity-entry.xhtml
server/zanata-war/src/main/webapp/resources/zanata/confirm-modal.xhtml
server/zanata-war/src/main/webapp/resources/zanata/multi-file-upload.xhtml
server/zanata-war/src/main/webapp/tm/home.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2378
fix(ZNTA-2378) remove references to aria-hidden from zanata-war dialogs so modals work correctly (specifically API generation modal)
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/706)

fix(ZNTA-2378) remove references to aria-hidden from zanata-war dialogs

---

docs/client/installation/linux-installation.md

Update client installation instruction
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/698)

doc(client): Update installation instruction

---

server/zanata-frontend/src/app/editor/api/index.js

- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/718)

fix: invalid js import syntax

---

server/services/src/main/java/org/zanata/action/ActivateAction.java
server/services/src/test/java/org/zanata/action/ActivateActionTest.java

Unit test for ActivateAction, except for the activate function.
Changes ActivateAction from a field inject to a constructor inject
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/685)

test(unittest): ActivateAction test

---

server/pom.xml

https://blog.jetbrains.com/kotlin/2018/01/kotlin-1-2-20-is-out/
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/726)

Update Kotlin to 1.2.21

---

parent/pom.xml

- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/722)

Add nexus-staging-maven-plugin in release profile

---

server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
server/zanata-frontend/src/app/editor/components/ActivityFeedItem/ActivityFeedItem.story.js
server/zanata-frontend/src/app/editor/components/DashboardLink/DashboardLink.test.js
server/zanata-frontend/src/app/editor/components/DashboardLink/index.js
server/zanata-frontend/src/app/editor/index.html
server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js
server/zanata-frontend/src/app/editor/reducers/header-data-reducer.test.js
server/zanata-frontend/src/index.html

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2395
Fix errors such as the following in react editor
```
Mixed Content: The page at 'https://translate.stage.engineering.redhat.com/project/translate/odys/v/1/odyssey.txt?dswid=9827&lang=de'c was loaded over HTTPS, but requested an insecure image 'http://www.gravatar.com/avatar/undefined?d=mm&ampr=g&amps=72'. This content should also be served over HTTPS.
```
- JIRA link
----
*This template can be updated …

fix(ZNTA-2395): references to http

---

server/services/src/main/java/org/zanata/servlet/UrlRewriteConfig.java
server/zanata-frontend/src/app/containers/Admin/index.js
server/zanata-frontend/src/app/containers/Admin/index.less
server/zanata-frontend/src/app/containers/Root.js
server/zanata-frontend/src/app/styles/style.less
server/zanata-frontend/src/app/styles/variables.less
server/zanata-war/src/main/webapp/WEB-INF/faces-config.xml
server/zanata-war/src/main/webapp/admin/create_user.xhtml
server/zanata-war/src/main/webapp/admin/processmanager.xhtml
server/zanata-war/src/main/webapp/admin/roledetail.xhtml
server/zanata-war/src/main/webapp/admin/rolemanager.xhtml
server/zanata-war/src/main/webapp/admin/roleruledetails.xhtml
server/zanata-war/src/main/webapp/admin/rolerules.xhtml
server/zanata-war/src/main/webapp/admin/search.xhtml
server/zanata-war/src/main/webapp/admin/server_configuration.xhtml
server/zanata-war/src/main/webapp/admin/stats.xhtml
server/zanata-war/src/main/webapp/admin/userdetail.xhtml
server/zanata-war/src/main/webapp/admin/usermanager.xhtml
server/zanata-war/src/main/webapp/tm/create.xhtml
server/zanata-war/src/main/webapp/tm/home.xhtml

JIRA issue URL:  https://zanata.atlassian.net/browse/ZNTA-2391
- JIRA link
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-platform/723)

ZNTA-2391: admin react page

---

server/zanata-frontend/src/app/editor/components/SplitDropdown/index.css
server/zanata-frontend/src/app/editor/components/SplitDropdown/index.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2393
Convert to bootstrap buttons so they handle scaling and dropdowns better.
- JIRA link
----

refactor(ZNTA-2393) translation split dropdown buttons in editor

---

server/zanata-frontend/src/app/editor/css/resizer/index.css
server/zanata-war/src/main/webapp/resources/assets/css/application.css

https://zanata.atlassian.net/browse/ZNTA-2399
increase visibility of panel resizers in gwt and react editors
- JIRA link
----

fix(ZNTA-2399) increase visibility of panel resizers in editors

---

server/services/src/main/java/org/zanata/rest/service/TranslationsTMXExportStrategy.java
server/services/src/test/java/org/zanata/rest/service/ExportTranslationsTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-30
Remove illegal characters from String before TM export to xml.
- JIRA link
----

fix(ZNTA-30) remove invalid char from TM Export

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/documents-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml
server/zanata-war/src/main/webapp/iteration/view.xhtml

https://zanata.atlassian.net/browse/ZNTA-2421
- JIRA link
----

fix(version page): show selected doc and locale

---

server/pom.xml

https://github.com/ocpsoft/rewrite/compare/3.4.1.Final...3.4.2.Final

Update to rewrite 3.4.2.Final

---

server/zanata-frontend/src/app/utils/DateHelper.ts

1. Fix date formatting problem introduced by bad refactoring in https://github.com/zanata/zanata-platform/pull/737
2. Change DD/MM/YYYY date formats to international format (YYYY-MM-DD, ~ISO 8601)

fix(ZNTA-2423) fix & improve date formatting

---

docs/client/installation/linux-installation.md

doc: update zanata-cli installation command

---

server/zanata-war/src/main/webapp/WEB-INF/layout/project/people-tab.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/person-permissions-modal.xhtml
server/zanata-war/src/main/webapp/resources/zanata/person-permission-entry.xhtml

These were the only files using z: as a prefix for http://java.sun.com/jsf/composite/zanata so I think it's better to make them consistent with the other .xhtml files.

Use xmlns:zanata in JSF, not xmlns:z

---

server/pom.xml
server/zanata-test-war/pom.xml
server/zanata-war/pom.xml

chore: fix deltaspike dependency

---

docs/client/installation/windows-installation.md

Related to https://zanata.atlassian.net/browse/ZNTA-2432

Update Windows manual instructions

---

server/zanata-frontend/src/package.json
server/zanata-frontend/src/yarn.lock

https://github.com/Microsoft/TypeScript/releases/tag/v2.8.1

Update TypeScript to 2.8.1

---

parent/pom.xml

See https://github.com/victims/maven-security-versions/issues/4

Disable maven-security-versions

---

docs/client/installation/linux-installation.md

Same changes as https://github.com/zanata/zanata-platform/pull/768, minus the Windows bits.

Reformat 0install docs

---

server/zanata-frontend/src/app/containers/UserProfile/index.jsx

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2490
Fix missing profile page 'email' icon
- JIRA link
----

fix(ZNTA-2490): Fix missing profile email icon

---

server/services/src/main/java/org/zanata/ApplicationConfiguration.java
server/services/src/main/java/org/zanata/ZanataInit.java
server/services/src/main/java/org/zanata/action/LoginAction.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2497
- JIRA link
----

fix(ZNTA-2497) support OpenID-only option

---

server/pom.xml

https://zanata.atlassian.net/browse/ZNTA-2471
- JIRA link
----

update: jackson-databind library

---

parent/pom.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2505
- JIRA link
----

Add aether-api

---

server/services/src/main/java/org/zanata/dao/AccountDAO.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2387
Admin can search for users via display name, email or username.
- JIRA link
----

fix(ZNTA-2387): Add email and name to user search query

---

client/zanata-client-commands/src/main/resources/prompts.properties

Update zanata.org/help to docs.zanata.org
- JIRA link
----

docs: update help url in cli

---

server/functional-test/src/main/java/org/zanata/page/account/RegisterPage.java
server/services/src/main/java/org/zanata/action/HasUserDetail.java
server/services/src/main/resources/ValidationMessages.properties

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-860
Add letter/number at start requirement to error message. Make min and max characters a reused constant.
- JIRA link
----

fix(ZNTA-860): Indicate username must start with a letter or number

---

server/services/src/main/java/org/zanata/liquibase/custom/CountWordsInHTextFlow.java
server/services/src/main/java/org/zanata/liquibase/custom/GenerateHashForGlossaryEntry.java
server/services/src/main/java/org/zanata/liquibase/custom/MigrateDataToHCredentials.java
server/services/src/main/java/org/zanata/liquibase/custom/MigrateHTermCommentToString.java
server/services/src/main/java/org/zanata/liquibase/custom/MigrateRawDocumentsToFileSystem.java
server/services/src/main/java/org/zanata/liquibase/custom/RebuildTMXPlainText.java
server/services/src/main/java/org/zanata/liquibase/custom/ValidateAccountPasswords.java

https://zanata.atlassian.net/browse/ZNTA-2531
- JIRA link
----

Fix old Liquibase migrations

---

server/zanata-frontend/src/frontend/app/editor/components/DocsDropdown/index.js
server/zanata-frontend/src/frontend/app/editor/components/LanguagesDropdown/index.js

https://zanata.atlassian.net/browse/ZNTA-2525
- JIRA link
----

fix: include context path for doc and language link

---

server/services/src/main/java/org/zanata/action/RoleAction.java
server/services/src/main/java/org/zanata/seam/security/ZanataJpaIdentityStore.java
server/services/src/main/resources/messages.properties
server/services/src/test/java/org/zanata/action/RoleActionTest.java
server/zanata-war/src/main/webapp/admin/roledetail.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1993
Prevent empty role name or greater than 255 characters
Prevent role name changes
Prevent overwriting an existing role
Remove users from role before deleting it
Add test
- JIRA link
----

fix(ZNTA-1993): Fix the role manager validation

---

server/services/src/test/java/org/zanata/test/DBUnitDataSetRunner.java
server/services/src/test/java/org/zanata/test/rule/DataSetOperation.java
server/zanata-model-test/src/main/java/org/zanata/RestTest.java
server/zanata-model-test/src/main/java/org/zanata/provider/DBUnitProvider.java
server/zanata-war/src/test/java/org/zanata/ArquillianTest.java

Refactor DBUnitProvider

---

server/services/src/main/java/org/zanata/rest/service/ProjectVersionService.java
server/services/src/test/java/org/zanata/rest/service/ProjectVersionTest.java
server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeModal.js

Allow 75% fuzzy threshold

---

server/services/src/main/java/org/zanata/action/ContactAdminAction.java
server/services/src/main/java/org/zanata/action/ContactLanguageTeamMembersAction.java
server/services/src/main/java/org/zanata/action/LanguageContactCoordinatorAction.java
server/services/src/main/java/org/zanata/action/LanguageJoinAction.java
server/services/src/main/java/org/zanata/action/VersionGroupJoinAction.java
server/services/src/main/java/org/zanata/email/ActivationEmailStrategy.java
server/services/src/main/java/org/zanata/email/ContactAdminAnonymousEmailStrategy.java
server/services/src/main/java/org/zanata/email/ContactAdminEmailStrategy.java
server/services/src/main/java/org/zanata/email/ContactLanguageCoordinatorEmailStrategy.java
server/services/src/main/java/org/zanata/email/ContactLanguageTeamMembersEmailStrategy.java
server/services/src/main/java/org/zanata/email/DeclineLanguageRequestEmailStrategy.java
server/services/src/main/java/org/zanata/email/EmailBuilder.java
server/services/src/main/java/org/zanata/email/EmailValidationEmailStrategy.java
server/services/src/main/java/org/zanata/email/LanguageTeamPermissionChangeEmailStrategy.java
server/services/src/main/java/org/zanata/email/PasswordResetEmailStrategy.java
server/services/src/main/java/org/zanata/email/RequestToJoinLanguageEmailStrategy.java
server/services/src/main/java/org/zanata/email/RequestToJoinVersionGroupEmailStrategy.java
server/services/src/main/java/org/zanata/email/UsernameChangedEmailStrategy.java
server/services/src/main/java/org/zanata/email/VelocityEmailStrategy.java
server/services/src/main/java/org/zanata/service/EmailService.java
server/services/src/main/java/org/zanata/service/impl/EmailServiceImpl.java
server/services/src/main/java/org/zanata/service/impl/RequestServiceImpl.java
server/services/src/test/java/org/zanata/action/ContactAdminActionTest.java
server/services/src/test/java/org/zanata/email/VelocityEmailStrategyTest.java

refactor: EmailStrategy to VelocityEmailStrategy

---

server/services/src/main/java/org/zanata/service/TransMemoryMergeService.java
server/services/src/main/java/org/zanata/service/tm/merge/TransMemoryMergeServiceImpl.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2567
- JIRA link
----

fix(ZNTA-2567) allow TM Merge (project version) to be cancelled

---

server/services/src/main/java/org/zanata/email/TMMergeEmailStrategy.kt
server/services/src/main/java/org/zanata/service/tm/merge/TransMemoryMergeServiceImpl.java
server/services/src/main/resources/messages.properties
server/services/src/test/java/org/zanata/email/HtmlEmailBuilderTest.kt

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2569
Include locale ID in TM Merge report email.
- JIRA link
----

fix(ZNTA-2569): add locale ID to the TM Merge report

---

server/functional-test/src/main/java/org/zanata/page/AbstractPage.kt
server/zanata-frontend/src/app/styles/style.less
server/zanata-war/src/main/webapp/WEB-INF/template/template.xhtml
server/zanata-war/src/main/webapp/WEB-INF/template/template_nobanner.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2552
Cookie consent banner for GDPR. Notification only.
- JIRA link
----

fix(ZNTA-2552): Cookie consent banner

---

server/zanata-frontend/src/app/containers/UserProfile/index.jsx
server/zanata-frontend/src/app/containers/UserProfile/index.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2522
added spacing between languages on user profile
- JIRA link
----

 fix(ZNTA-2522) added spacing between languages on user profile

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/groups-tab.xhtml

https://zanata.atlassian.net/browse/ZNTA-2577
- JIRA link
----

fix: invalid group link in version page

---

Jenkinsfile

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2561
- JIRA link
----

fix(ZNTA-2561): Jenkinsfile: preprocess node should be kept minimal

---

client/zanata-client-commands/src/main/java/org/zanata/client/commands/ConfigurableOptionsImpl.java
client/zanata-rest-client/src/main/java/org/zanata/rest/client/TraceDebugFilter.java
client/zanata-rest-client/src/test/java/org/zanata/rest/client/FileResourceClientTest.java

Improve TraceDebugFilter; add debug for FileResourceClientTest

---

server/zanata-war/src/main/webapp/WEB-INF/layout/project/languages-list.xhtml
server/zanata-war/src/main/webapp/resources/zanata/select-all-checkbox.xhtml

https://zanata.atlassian.net/browse/ZNTA-2549
- JIRA link
----

fix: unique html id for checkbox

---

server/services/pom.xml
server/zanata-war/pom.xml

Update JavaMelody to 1.72.0

---

server/zanata-frontend/src/app/styles/frontend-jsf.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2574
Group pages styling fixes for release: 
* language dropdown (autoSuggest) height corrected, 
* container width corrected (rootMain)
_Tested in FF & Chrome_
- JIRA link
----

fix(ZNTA-2574) group pages styling fixes

---

server/functional-test/pom.xml
server/functional-test/src/test/resources/liquibase.properties

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2532
Configure functional tests to run 'liquibase' script before starting app server.
- JIRA link
----

test(ZNTA-2532): run liquibase script for tests

---

server/functional-test/src/main/java/org/zanata/page/dashboard/DashboardProjectsTab.java
server/services/src/main/java/org/zanata/action/DashboardAction.java
server/services/src/main/java/org/zanata/dao/ProjectDAO.java
server/services/src/main/resources/messages.properties
server/services/src/test/java/org/zanata/dao/ProjectDAOTest.java
server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/projects.xhtml

https://zanata.atlassian.net/browse/ZNTA-2578
- JIRA link
----

feat: display projects in dashboard for member and maintainer

---

server/zanata-frontend/src/app/styles/frontend-jsf.less
server/zanata-war/src/main/webapp/WEB-INF/layout/version-group/delete_group_confirmation_modal.xhtml

Fix merge conflicts when merging release into master
- JIRA link
----

fix: release-to-master merge conflicts

---

server/services/src/main/java/org/zanata/dao/VersionGroupDAO.java
server/services/src/main/java/org/zanata/rest/search/dto/GroupSearchResult.java
server/services/src/main/java/org/zanata/rest/search/service/SearchService.java
server/services/src/main/java/org/zanata/security/SecurityFunctions.java
server/services/src/main/resources/db/changelogs/db.changelog-4.6.xml
server/services/src/main/resources/db/db.changelog.xml
server/zanata-frontend/src/app/containers/Explore/GroupTeaser.jsx
server/zanata-model-test/src/main/resources/org/zanata/test/model/CopyVersionData.dbunit.xml
server/zanata-model-test/src/main/resources/org/zanata/test/model/GroupsTestData.dbunit.xml
server/zanata-model/src/main/java/org/zanata/model/HIterationGroup.java

https://zanata.atlassian.net/browse/ZNTA-2588
- JIRA link
----

fix: cleanup obsolete groups

---

server/zanata-frontend/src/app/containers/Glossary/Entry.js

Give it back its circle.
- JIRA link
----

fix(UI): glossary entry details icon

---

server/services/src/main/java/org/zanata/action/VersionHome.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2596
Value of HProject retrieved from ProjectDAO was not validated before being used.
- JIRA link
----

fix(ZNTA-2596): detect invalid project slug in url

---

parent/pom.xml
server/pom.xml

#also change aggregate phase to site
This should fix both mvn site and deploy
- JIRA link
----

remove(profile): doclint-java8-disable

---

server/services/src/main/java/org/zanata/dao/ProjectIterationDAO.java
server/services/src/main/java/org/zanata/rest/service/StatisticsServiceImpl.java

https://zanata.atlassian.net/browse/ZNTA-968
- JIRA link
----

fix: improve stats collection

---

server/zanata-frontend/src/app/editor/containers/KeyShortcutCheatSheet/index.css

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2590
decrease height of keyboard shortcut modal, add scrolling
- JIRA link
----

fix(ZNTA-2590) decrease height of keyboard shortcut modal, add scrolling

---

server/zanata-frontend/src/app/actions/version-actions.js
server/zanata-frontend/src/app/components/Icons/Readme.md
server/zanata-frontend/src/app/containers/Languages/DeleteEntry.js
server/zanata-frontend/src/app/containers/UserProfile/DayMatrix.jsx
server/zanata-frontend/src/app/editor/components/RejectTranslationModal/PriorityDropdown.js
server/zanata-frontend/src/app/editor/components/Suggestion.js
server/zanata-frontend/src/app/editor/components/TransUnitStatus.tsx
server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx
server/zanata-frontend/src/app/editor/containers/TranslationInfoPanel/DetailsPane.tsx
server/zanata-frontend/src/app/editor/reducers/header-data-reducer.js
server/zanata-frontend/src/app/editor/reducers/review-trans-reducer.js
server/zanata-frontend/src/app/editor/reducers/ui-reducer.test.js
server/zanata-frontend/src/app/editor/utils/phrase-util.ts
server/zanata-frontend/src/app/editor/utils/status-util.test.js
server/zanata-frontend/src/app/editor/watchers/phrase-detail.js
server/zanata-frontend/src/app/editor/watchers/phrase-list.js
server/zanata-frontend/src/app/reducers/admin-reducer.js
server/zanata-frontend/src/app/require-all.test.ts
server/zanata-frontend/src/app/utils/GlossaryHelper.js
server/zanata-frontend/src/app/utils/StringUtils.test.js
server/zanata-frontend/src/tsconfig.json
server/zanata-frontend/src/webpack.config.js

Enable strictNullChecks for TypeScript

---

server/services/src/main/java/org/zanata/webtrans/server/rpc/LoadOptionsHandler.java

https://zanata.atlassian.net/browse/ZNTA-2618
- JIRA link
----

fix: GWT editor option

---

server/zanata-frontend/src/app/editor/actions/header-actions.js
server/zanata-frontend/src/app/editor/actions/phrases-actions.js
server/zanata-frontend/src/app/editor/reducers/phrase-reducer/index.js
server/zanata-frontend/src/app/editor/reducers/phrase-reducer/phrase-reducer.test.js

https://zanata.atlassian.net/browse/ZNTA-2616
- JIRA link
----

fix: statistics update after save

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/ui/TranslatorListWidget.ui.xml
server/zanata-frontend/src/app/containers/Languages/NewLanguageModal.js
server/zanata-frontend/src/app/containers/Languages/index.js
server/zanata-frontend/src/app/containers/Languages/index.less
server/zanata-frontend/src/app/editor/containers/ActivityTab.tsx
server/zanata-frontend/src/app/styles/antd.less
server/zanata-frontend/src/app/styles/style.less

Resolve merge conflicts from release / master
- JIRA link
----

merge release master

---

server/etc/scripts/configure-app-server.js
server/etc/scripts/runJbossCli.groovy
server/etc/scripts/types.d.ts
server/functional-test/pom.xml
server/zanata-war/src/main/webapp/WEB-INF/liquibase

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2532
Maven build wasn't failing when liquibase failed. Now passes required config in, and fails build if liquibase script fails.
- JIRA link
----

fix(ZNTA-2532) fix liquibase configuration

---

server/functional-test/src/main/java/org/zanata/page/administration/ServerConfigurationPage.java
server/functional-test/src/test/java/org/zanata/feature/account/InactiveUserLoginTest.java
server/functional-test/src/test/java/org/zanata/feature/administration/ManageSearchTest.java
server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java
server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java
server/functional-test/src/test/java/org/zanata/feature/project/EditProjectGeneralTest.java

Found using IntelliJ IDEA's structural search:
assertThat($actual$)
.$as$($description$);
where `$as$` is the regex: `(as|describedAs)`
- JIRA link
----

Add some missing assertions

---

server/services/src/main/resources/messages.properties
server/zanata-war/src/main/webapp/account/google_password_reset_request.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2605
Fix contact admin on Google login page
- JIRA link
----

fix(ZNTA-2605): fix contact admin on Google log in

---

server/zanata-frontend/src/app/components/LogoLoader/index.less
server/zanata-frontend/src/app/styles/frontend-nav.less
server/zanata-frontend/src/app/styles/style.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2589
Set nav icon size to fixed font-size so that it doesn't fluctuate between react and jsf pages
- JIRA link
----

fix(ZNTA-2589) consistency of nav icons

---

server/zanata-frontend/src/app/components/TMX/TMXExportModal.js
server/zanata-frontend/src/app/entrypoint/index.js
server/zanata-frontend/src/app/styles/ant-theme-vars.less
server/zanata-frontend/src/app/styles/antd.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2607
Remove non-existent antd Badge component
Minor styling fixes
- JIRA link
----

fix(ZNTA-2607) TMX modal styling

---

server/zanata-frontend/src/app/components/TMX/TMXExportModal.js
server/zanata-frontend/src/app/entrypoint/index.js
server/zanata-frontend/src/app/styles/ant-theme-vars.less
server/zanata-frontend/src/app/styles/antd.less

fix release-to-master conflicts

---

server/zanata-frontend/src/app/containers/Glossary/ViewHeader.js

https://zanata.atlassian.net/browse/ZNTA-2609
- JIRA link
----

fix: project url in glossary page

---

server/functional-test/src/main/java/org/zanata/page/BasePage.java

Update the AddLanguageTest notification close button selenium id
- JIRA link
----

fix: AddLanguageTest selenium id for notifications

---

server/zanata-frontend/src/app/containers/Glossary/Entry.js
server/zanata-frontend/src/app/containers/Glossary/EntryModal.js
server/zanata-frontend/src/app/containers/Glossary/ExportModal.js
server/zanata-frontend/src/app/containers/Glossary/ImportModal.js
server/zanata-frontend/src/app/containers/Glossary/NewEntryModal.js
server/zanata-frontend/src/app/styles/style.less

https://zanata.atlassian.net/browse/ZNTA-2627
- JIRA link
----

fix: loader text in button

---

server/pom.xml

https://blog.jetbrains.com/kotlin/2018/06/kotlin-1-2-50-is-out/
- JIRA link
----

Update to Kotlin 1.2.50; enable -Xprogressive

---

common/zanata-adapter-glossary/src/test/java/org/zanata/adapter/glossary/GlossaryCSVReaderTest.java
server/functional-test/src/main/java/org/zanata/page/CorePage.java
server/functional-test/src/test/java/org/zanata/feature/account/InactiveUserLoginTest.java
server/functional-test/src/test/java/org/zanata/feature/administration/ManageSearchTest.java
server/functional-test/src/test/java/org/zanata/feature/administration/ServerSettingsTest.java
server/functional-test/src/test/java/org/zanata/feature/dashboard/DashboardTest.java
server/functional-test/src/test/java/org/zanata/feature/document/DownloadDocumentTest.java
server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java
server/functional-test/src/test/java/org/zanata/feature/editor/EditorAlphaTest.java
server/functional-test/src/test/java/org/zanata/feature/endtoend/AdminEndToEndTest.java
server/functional-test/src/test/java/org/zanata/feature/endtoend/UserEndToEndTest.java
server/functional-test/src/test/java/org/zanata/feature/project/EditProjectGeneralTest.java
server/services/src/test/java/org/zanata/adapter/AbstractAdapterTest.java
server/services/src/test/java/org/zanata/adapter/TSAdapterTest.java
server/services/src/test/java/org/zanata/adapter/XliffAdapterTest.java

Include .as descriptions in end to end tests. Also fixes some missing assertions.
- JIRA link
----

fix(test): Update e2e assert descriptions

---

server/etc/scripts/configure-app-server.js

Relates to https://zanata.atlassian.net/browse/ZNTA-2281
- JIRA link
----

Fix console logger for EAP tests

---

server/gwt-editor/src/main/java/org/zanata/webtrans/client/view/SideMenuView.java

https://zanata.atlassian.net/browse/ZNTA-2625
- JIRA link
----

fix: remove '0' notification label in gwt editor

---

server/zanata-frontend/src/app/containers/Admin/Review.js
server/zanata-frontend/src/app/containers/Admin/index.js

fix: use link component in admin home

---

common/zanata-adapter-glossary/src/test/java/org/zanata/adapter/glossary/GlossaryCSVReaderTest.java
server/etc/scripts/configure-app-server.js
server/functional-test/src/main/java/org/zanata/page/CorePage.java
server/functional-test/src/test/java/org/zanata/feature/dashboard/DashboardTest.java
server/functional-test/src/test/java/org/zanata/feature/document/DownloadDocumentTest.java
server/functional-test/src/test/java/org/zanata/feature/document/MultiFileUploadTest.java
server/functional-test/src/test/java/org/zanata/feature/editor/EditorAlphaTest.java
server/functional-test/src/test/java/org/zanata/feature/endtoend/AdminEndToEndTest.java
server/functional-test/src/test/java/org/zanata/feature/endtoend/UserEndToEndTest.java
server/services/src/test/java/org/zanata/adapter/AbstractAdapterTest.java
server/services/src/test/java/org/zanata/adapter/TSAdapterTest.java

Just resolving some merge conflicts around calls to `serverConfigurationPage.expectFieldValue`.
- JIRA link
----

Merge release to master

---

server/zanata-model/src/main/java/org/zanata/model/type/TranslationSourceType.java

Related to https://zanata.atlassian.net/browse/ZNTA-2487
- JIRA link
----

Add MACHINE_TRANS to AUTOMATED_ENTRIES

---

server/zanata-frontend/src/app/containers/UserProfile/index.less
server/zanata-frontend/src/app/styles/antd.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2638
- JIRA link
----

fix(ZNTA-2638) remove borders from antd buttons using btn-link styling

---

server/zanata-frontend/src/app/components/Link/index.js
server/zanata-frontend/src/app/components/Nav/index.jsx

https://zanata.atlassian.net/browse/ZNTA-2600
- JIRA link
----

fix: nav link

---

server/zanata-frontend/src/.eslintrc
server/zanata-frontend/src/app/actions/common-actions.ts
server/zanata-frontend/src/app/actions/glossary-actions.js
server/zanata-frontend/src/app/actions/tmx-actions.js
server/zanata-frontend/src/app/reducers/admin-reducer.js
server/zanata-frontend/src/app/reducers/common-reducer.js
server/zanata-frontend/src/app/reducers/explore-reducer.js
server/zanata-frontend/src/app/reducers/glossary-reducer.js
server/zanata-frontend/src/app/reducers/languages-reducer.js
server/zanata-frontend/src/app/reducers/profile-reducer.js
server/zanata-frontend/src/app/reducers/state.ts
server/zanata-frontend/src/app/reducers/tmx-reducer.js
server/zanata-frontend/src/app/utils/DateHelper.ts
server/zanata-frontend/src/app/utils/DeepReadonly.d.ts
server/zanata-frontend/src/app/utils/prop-types-util.ts
server/zanata-frontend/src/tslint.json

Add incomplete types for Redux state

---

server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java

In DEV mode, MT may return DEV pseudo-translations when GOOGLE translations were requested. This change ensures that they are attributed as DEV.
- JIRA link
----

Fix attribution for DEV mode MT

---

server/zanata-frontend/src/app/reducers/version-reducer.js

Successful(+l)y
- JIRA link
----

fix(string): Successfuly fix a typo

---

server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2671
Continue.
- JIRA link
----

fix(ZNTA-2671): skip loop on failed attribution check

---

server/zanata-war/src/main/webapp/iteration/view.xhtml
server/zanata-war/src/main/webapp/version-group/version_group.xhtml

https://zanata.atlassian.net/browse/ZNTA-2687
- JIRA link
----

fix: refresh project list on language selection

---

server/zanata-frontend/src/app/containers/Languages/index.js

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2681
Fixed update functions for Language page search and sort to accept correct inputs.
- JIRA link
----

fix(ZNTA-2681): language page sort and search

---

server/zanata-frontend/src/.storybook-editor/__snapshots__/storyshots-editor.test.js.snap
server/zanata-frontend/src/app/editor/components/ActivitySelectList/index.js
server/zanata-frontend/src/app/editor/containers/Sidebar/index.css

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2685
* increase margin between editor sidebar and header
* add spacing between activity tab selector buttons
- JIRA link
----

fix(ZNTA-2685) minor editor css fixes

---

server/zanata-frontend/src/app/containers/Explore/TeaserListHeader.jsx
server/zanata-frontend/src/app/styles/antd.less

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2677
Fix Next button in Explore page pagination so it works
- JIRA link
----

fix(ZNTA-2677) explore page pagination next button fixed

---

server/zanata-frontend/src/app/styles/frontend-jsf.less
server/zanata-war/src/main/webapp/WEB-INF/layout/version/edit_form.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab-languages.xhtml
server/zanata-war/src/main/webapp/WEB-INF/layout/version/settings-tab.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2674
https://zanata.atlassian.net/browse/ZNTA-2675
Fix height of buttons on settings pages and colours of validation buttons
- JIRA link
----

fix(ZNTA-2674)(ZNTA-2675) ui fixes to project version settings

---

client/pom.xml
client/zanata-maven-plugin/pom.xml
parent/pom.xml
server/pom.xml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2478
- JIRA link
----

chore(ZNTA-2478): enable ossindex audit to fail build

---

server/zanata-war/src/main/webapp/account/create_user.xhtml
server/zanata-war/src/main/webapp/account/register.xhtml

https://zanata.atlassian.net/browse/ZNTA-2695
- JIRA link
----

fix(ZNTA-2695): terms url

---

server/zanata-frontend/src/app/containers/Languages/index.js

https://zanata.atlassian.net/browse/ZNTA-2696
- JIRA link
----

fix: language search

---

.mvn/wrapper/maven-wrapper.properties

Partly because of https://issues.apache.org/jira/browse/MNG-6382
- JIRA link
----

chore: update to Maven 3.5.4

---

server/zanata-frontend/src/app/containers/UserProfile/RecentContributions.jsx
server/zanata-frontend/src/app/styles/antd.less
server/zanata-frontend/src/app/styles/frontend-jsf.less
server/zanata-war/src/main/webapp/admin/cachestats.xhtml
server/zanata-war/src/main/webapp/admin/create_user.xhtml
server/zanata-war/src/main/webapp/admin/processmanager.xhtml
server/zanata-war/src/main/webapp/admin/roledetail.xhtml
server/zanata-war/src/main/webapp/admin/rolemanager.xhtml
server/zanata-war/src/main/webapp/admin/roleruledetails.xhtml
server/zanata-war/src/main/webapp/admin/rolerules.xhtml
server/zanata-war/src/main/webapp/admin/search.xhtml
server/zanata-war/src/main/webapp/admin/stats.xhtml
server/zanata-war/src/main/webapp/admin/userdetail.xhtml
server/zanata-war/src/main/webapp/admin/usermanager.xhtml
server/zanata-war/src/main/webapp/tm/create.xhtml
server/zanata-war/src/main/webapp/tm/home.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2712
admin breadcrumb links - same size, spacing and links working
width of admin cache page header
- JIRA link
----

fix(ZNTA-2712) admin breadcrumbs

---

server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2721
Pushing 30k strings through MT proved to be excessive force. Batch to 1000.
- JIRA link
----

fix(ZNTA-2721): batch requests to server

---

server/zanata-war/src/main/webapp/iteration/view.xhtml

https://zanata.atlassian.net/browse/ZNTA-2731
- JIRA link
----

fix: disable trans merge if empty document

---

server/services/src/main/java/org/zanata/action/VersionHomeAction.java
server/zanata-war/src/main/webapp/iteration/view.xhtml

https://zanata.atlassian.net/browse/ZNTA-2743
- JIRA link
----

fix: hide MT merge option if without URL

---

server/services/src/main/java/org/zanata/service/mt/dto/TypeString.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2735
Pass Zanata content to MT as XML for correct handling of XML tags in strings.
Requires https://github.com/zanata/zanata-mt/pull/85
- JIRA link
----

fix(ZNTA-2735): pass strings to MT as text/xml

---

server/zanata-war/src/main/webapp/admin/roledetail.xhtml

JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-2740*
- JIRA link
----

fix: ZNTA-2740: role details exception

---

server/services/src/main/java/org/zanata/action/CopyTransManager.java
server/services/src/main/java/org/zanata/action/CopyVersionManager.java
server/services/src/main/java/org/zanata/action/DashboardAction.java
server/services/src/main/java/org/zanata/action/MergeTranslationsManager.java
server/services/src/main/java/org/zanata/async/AsyncTaskHandle.java
server/services/src/main/java/org/zanata/async/AsyncTaskHandleManager.java
server/services/src/main/java/org/zanata/async/handle/CopyTransTaskHandle.java
server/services/src/main/java/org/zanata/async/handle/CopyVersionTaskHandle.java
server/services/src/main/java/org/zanata/async/handle/MachineTranslationPrefillTaskHandle.java
server/services/src/main/java/org/zanata/async/handle/MergeTranslationsTaskHandle.java
server/services/src/main/java/org/zanata/async/handle/TransMemoryMergeTaskHandle.java
server/services/src/main/java/org/zanata/rest/editor/service/TransMemoryMergeManager.java
server/services/src/main/java/org/zanata/rest/service/MachineTranslationsManager.java
server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
server/services/src/main/resources/messages.properties
server/services/src/test/java/org/zanata/async/AsyncTaskHandleManagerTest.kt
server/services/src/test/java/org/zanata/rest/editor/service/TransMemoryMergeManagerTest.java
server/services/src/test/java/org/zanata/rest/service/AsyncProcessServiceTest.java
server/zanata-war/src/main/webapp/WEB-INF/layout/dashboard/tasks.xhtml
server/zanata-war/src/main/webapp/dashboard/home.xhtml

Identify user tasks and display in dashboard.
- JIRA link
----

feat(async): add a Tasks tab to dashboard

---

server/zanata-war/src/main/webapp/WEB-INF/layout/version/languages-tab.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2751
Fix selected locale in version documents list.
- JIRA link
----

fix(ZNTA-2751): translation file upload permission

---

server/services/src/main/java/org/zanata/action/VersionHomeAction.java
server/services/src/test/java/org/zanata/action/VersionHomeActionTest.kt
server/zanata-war/src/main/webapp/iteration/view.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2745
Don't access documents property directly, use function
- JIRA link
----

fix(ZNTA-2745): use function to check for documents in version

---

server/pom.xml
server/services/pom.xml
server/services/src/test/java/org/zanata/action/FrontendAssetsTest.kt
server/services/src/test/java/org/zanata/action/VersionHomeActionTest.kt
server/services/src/test/java/org/zanata/dao/CredentialsDAOTest.kt
server/services/src/test/java/org/zanata/rest/RestLimitingFilterTest.kt
server/services/src/test/java/org/zanata/security/AuthenticationManagerTest.kt
server/services/src/test/java/org/zanata/security/SamlAccountServiceTest.kt
server/services/src/test/java/org/zanata/servlet/SAMLFilterTest.kt
server/services/src/test/java/org/zanata/ui/faces/FacesMessagesTest.kt
server/zanata-war/pom.xml

chore: upgrade to Mockito-Kotlin 2

---

server/services/src/test/java/org/zanata/rest/RestLimitingFilterTest.kt

chore: use argumentCaptor

---

parent/pom.xml
server/services/src/main/java/org/zanata/action/ProjectHome.java
server/services/src/main/java/org/zanata/action/ProjectHomeAction.java
server/services/src/main/java/org/zanata/action/VersionHome.java
server/services/src/main/java/org/zanata/action/VersionHomeAction.java
server/services/src/main/java/org/zanata/file/DocumentUploadUtil.java
server/services/src/main/java/org/zanata/file/SourceDocumentUpload.java
server/services/src/main/java/org/zanata/file/TranslationDocumentUpload.java
server/services/src/main/java/org/zanata/rest/editor/service/TranslationReviewService.java
server/services/src/main/java/org/zanata/service/impl/SecurityServiceImpl.java
server/services/src/main/java/org/zanata/webtrans/server/TranslationWorkspaceManagerImpl.java
server/services/src/main/java/org/zanata/webtrans/server/rpc/ActivateWorkspaceHandler.java
server/services/src/main/resources/messages.properties
server/services/src/test/java/org/zanata/action/VersionHomeActionTest.kt
server/services/src/test/java/org/zanata/file/DocumentUploadTest.java
server/services/src/test/java/org/zanata/file/DocumentUploadUtilTest.java
server/services/src/test/java/org/zanata/file/SourceDocumentUploadTest.java
server/services/src/test/java/org/zanata/webtrans/server/rpc/ActivateWorkspaceHandlerTest.java
server/zanata-model/src/main/java/org/zanata/model/HProjectIteration.java
server/zanata-war/src/main/webapp/resources/zanata/version-label.xhtml

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2753
Use one function everywhere for project and version status ACTIVE, rather than specifying it repeatedly and potentially getting it wrong.
- JIRA link
----

fix(ZNTA-2753): unify the version is active check

---

server/services/src/main/java/org/zanata/rest/ZanataRestSecurityInterceptor.java

refactor: use Either.bipeek

---

common/zanata-common-util/src/test/java/org/zanata/util/HashUtilTest.java
server/gwt-editor/src/test/java/org/zanata/webtrans/client/service/TransUnitSaveServiceTest.java
server/pom.xml
server/services/src/test/java/org/zanata/adapter/TSAdapterTest.kt
server/services/src/test/java/org/zanata/rest/service/ResourceUtilsTest.java
server/services/src/test/java/org/zanata/service/impl/CopyVersionServiceImplTest.java
server/zanata-model/src/test/java/org/zanata/util/OkapiUtilTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2694
- JIRA link
----

chore(ZNTA-2694): Upgrade Okapi to M36

---

parent/pom.xml

https://github.com/jacoco/jacoco/releases/tag/v0.8.2
- JIRA link
----

Update JaCoCo (filters out Kotlin codegen)

---

server/pom.xml

chore: update to CDI-Unit 4.1.0

---

server/services/src/main/java/org/zanata/async/handle/MachineTranslationPrefillTaskHandle.java
server/services/src/main/java/org/zanata/service/impl/MachineTranslationServiceImpl.java
server/services/src/test/java/org/zanata/async/MachineTranslationPrefillTaskHandleTest.kt
server/services/src/test/java/org/zanata/service/impl/MachineTranslationServiceImplTest.java

JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-2710
Use the overall TF count and batches to determine progress.
- JIRA link
----

fix(ZNTA-2710) Increase MT progress granularity

---

server/docker/docker-compose.yml

Since Fedora 27 is definitely out by now...
- JIRA link
----

chore: update docker-compose.yml to add healthcheck

---

server/zanata-war/pom.xml
server/zanata-war/src/main/webapp/WEB-INF/layout/project/person-permissions-modal.xhtml
server/zanata-war/src/main/webapp/resources/script/jsf-ajax-viewstate-fix.js

chore: remove omnifaces

---

server/zanata-frontend/src/app/containers/ProjectVersion/ProjectVersionPanels.js
server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeModal.js
server/zanata-frontend/src/app/containers/ProjectVersion/TMMergeProjectSources.js
server/zanata-frontend/src/app/reducers/state.ts
server/zanata-frontend/src/app/reducers/version-reducer.js
server/zanata-frontend/src/app/reducers/version-reducer.test.js

Insert a "select all" checkbox in tm merge modal to select all listed project/versions
https://zanata.atlassian.net/browse/ZNTA-2758
- JIRA link
----

feat: add select all option in tm merge

---

server/build.sh
server/docker/Dockerfile.zanata
server/docker/docker-compose.yml
server/docker/rundb.sh
server/docker/rundev-compose.sh
server/docker/rundev.sh

Update rundev scripts
